<?php
declare(strict_types=1);

function event_text($value,int $max=180): string {
    if(!is_string($value))api_error('VALIDATION_ERROR','Enter valid event details.',422);
    $value=trim($value);if($value===''||mb_strlen($value)>$max)api_error('VALIDATION_ERROR','Complete the required fields within the displayed limits.',422);return $value;
}
function event_date($value): string {
    if(!is_string($value))api_error('VALIDATION_ERROR','Choose a valid date.',422);
    $d=DateTimeImmutable::createFromFormat('!Y-m-d',$value);
    if(!$d||$d->format('Y-m-d')!==$value)api_error('VALIDATION_ERROR','Choose a valid date.',422);return $value;
}
function event_time($value): string {
    if(!is_string($value))api_error('VALIDATION_ERROR','Choose a valid session time.',422);
    $value=str_replace('T',' ',$value);$d=DateTimeImmutable::createFromFormat('!Y-m-d H:i',$value,new DateTimeZone('Africa/Lagos'));
    if(!$d||$d->format('Y-m-d H:i')!==$value)api_error('VALIDATION_ERROR','Choose a valid session time.',422);return $value.':00';
}
function event_allowed(PDO $db,array $actor,int $id): array {
    $s=$db->prepare('SELECT * FROM ministry_events WHERE id=? AND campus_id=?');$s->execute([$id,$actor['campus_id']]);$event=$s->fetch();
    if(!$event)api_error('EVENT_NOT_FOUND','This event is not available at your campus.',404);return $event;
}
function event_operator(PDO $db,array $actor,int $id,string $duty=''): bool {
    if($actor['access_level']==='TPK_SUPER_ADMIN')return true;
    $s=$db->prepare('SELECT duty FROM event_volunteers WHERE event_id=? AND staff_user_id=?');$s->execute([$id,$actor['id']]);$assigned=$s->fetchColumn();
    return $duty?($assigned==='LEAD'||$assigned===$duty):in_array($assigned,['LEAD','CHECK_IN','PICKUP'],true);
}
function event_summary(PDO $db,int $id): array {
    $s=$db->prepare('SELECT COUNT(*) AS registered,SUM(c.care_notes IS NOT NULL AND c.care_notes<>\'\') AS careNotes FROM event_children c JOIN event_registrations r ON r.id=c.registration_id WHERE r.event_id=?');$s->execute([$id]);$counts=$s->fetch();
    $s=$db->prepare('SELECT COUNT(*) FROM event_volunteers WHERE event_id=?');$s->execute([$id]);$counts['volunteers']=(int)$s->fetchColumn();
    $s=$db->prepare('SELECT COUNT(*) AS checkedIn,SUM(a.picked_up_at IS NULL) AS awaitingPickup FROM event_attendance a JOIN event_sessions s ON s.id=a.session_id WHERE s.event_id=? AND DATE(s.starts_at)=?');$s->execute([$id,(new DateTimeImmutable('now',new DateTimeZone('Africa/Lagos')))->format('Y-m-d')]);return array_merge($counts,$s->fetch());
}
function api_events(PDO $db,int $id=0): never {
    $actor=api_actor($db);$super=$actor['access_level']==='TPK_SUPER_ADMIN';
    if(!$id){$s=$db->prepare('SELECT id,name,event_type AS type,starts_on AS startDate,ends_on AS endDate,status,countdown_enabled AS countdown FROM ministry_events WHERE campus_id=? ORDER BY starts_on DESC,id DESC');$s->execute([$actor['campus_id']]);$items=$s->fetchAll();foreach($items as &$e)$e['summary']=event_summary($db,(int)$e['id']);unset($e);api_ok(['items'=>$items,'canManage'=>$super]);}
    $e=event_allowed($db,$actor,$id);$operate=event_operator($db,$actor,$id);
    $data=['event'=>['id'=>$e['id'],'name'=>$e['name'],'type'=>$e['event_type'],'startDate'=>$e['starts_on'],'endDate'=>$e['ends_on'],'registrationOpens'=>$e['registration_opens'],'registrationCloses'=>$e['registration_closes'],'description'=>$e['description'],'status'=>$e['status'],'countdown'=>(bool)$e['countdown_enabled'],'publicRegistration'=>(bool)$e['public_registration'],'publicKey'=>$super?$e['public_key']:null],'summary'=>event_summary($db,$id),'canManage'=>$super,'canOperate'=>$operate,'canCheckIn'=>event_operator($db,$actor,$id,'CHECK_IN'),'canPickUp'=>event_operator($db,$actor,$id,'PICKUP')];
    $s=$db->prepare('SELECT s.id,s.name,s.starts_at AS startsAt,s.ends_at AS endsAt,COALESCE(cs.expected,0) AS expected,COALESCE(a.attended,0) AS attended,COALESCE(a.awaitingPickup,0) AS awaitingPickup FROM event_sessions s LEFT JOIN (SELECT session_id,COUNT(*) AS expected FROM event_child_sessions GROUP BY session_id) cs ON cs.session_id=s.id LEFT JOIN (SELECT session_id,COUNT(*) AS attended,SUM(picked_up_at IS NULL) AS awaitingPickup FROM event_attendance GROUP BY session_id) a ON a.session_id=s.id WHERE s.event_id=? ORDER BY s.starts_at,s.id');$s->execute([$id]);$data['sessions']=$s->fetchAll();
    $s=$db->prepare('SELECT id,name,min_age AS minAge,max_age AS maxAge FROM event_groups WHERE event_id=? ORDER BY min_age');$s->execute([$id]);$data['groups']=$s->fetchAll();
    $s=$db->prepare('SELECT v.staff_user_id AS userId,u.name,v.duty,p.profile_image_url AS profileImageUrl FROM event_volunteers v JOIN staff_users u ON u.id=v.staff_user_id LEFT JOIN teacher_profiles p ON p.staff_user_id=u.id WHERE v.event_id=? ORDER BY u.name');$s->execute([$id]);$data['volunteers']=$s->fetchAll();
    $data['children']=[];$data['attendance']=[];$data['staff']=[];
    if($operate){$s=$db->prepare('SELECT c.id,c.name,c.date_of_birth AS dateOfBirth,c.care_notes AS careNotes,c.group_id AS groupId,g.name AS groupName,r.guardian_name AS guardianName,r.guardian_phone AS guardianPhone,r.emergency_phone AS emergencyPhone,r.home_campus AS homeCampus,r.reference_code AS referenceCode,(SELECT GROUP_CONCAT(cs.session_id) FROM event_child_sessions cs WHERE cs.child_id=c.id) AS sessionIds FROM event_children c JOIN event_registrations r ON r.id=c.registration_id LEFT JOIN event_groups g ON g.id=c.group_id WHERE r.event_id=? ORDER BY c.name');$s->execute([$id]);$data['children']=$s->fetchAll();
      $s=$db->prepare('SELECT a.id,a.child_id AS childId,a.session_id AS sessionId,a.checked_in_at AS checkedInAt,a.picked_up_at AS pickedUpAt,a.pickup_code AS pickupCode,a.collector_name AS collectorName FROM event_attendance a JOIN event_sessions s ON s.id=a.session_id WHERE s.event_id=? ORDER BY a.checked_in_at DESC');$s->execute([$id]);$data['attendance']=$s->fetchAll();}
    if($super){$s=$db->prepare("SELECT u.id,u.name FROM staff_users u WHERE u.campus_id=? AND u.is_active=1 AND u.account_status='VERIFIED' AND u.team_status<>'INACTIVE' ORDER BY u.name");$s->execute([$actor['campus_id']]);$data['staff']=$s->fetchAll();}
    api_ok($data);
}
function api_event_save(PDO $db,int $id=0): never {
    $actor=api_actor($db,true);$v=api_input();if($id)event_allowed($db,$actor,$id);
    $name=event_text($v['name']??'');$type=event_text($v['type']??'',30);if(!in_array($type,['CONFERENCE','VBS','CAMP','SPECIAL_SERVICE','OTHER'],true))api_error('VALIDATION_ERROR','Choose an event type.',422);
    $start=event_date($v['startDate']??'');$end=event_date($v['endDate']??'');$opens=event_date($v['registrationOpens']??'');$closes=event_date($v['registrationCloses']??'');$status=$v['status']??'DRAFT';
    if($end<$start||$closes<$opens||$closes>$end||!in_array($status,['DRAFT','PUBLISHED','CANCELLED'],true))api_error('VALIDATION_ERROR','Check the event dates, registration window and status.',422);
    $description=trim((string)($v['description']??''));if(mb_strlen($description)>4000)api_error('VALIDATION_ERROR','Keep the event description under 4,000 characters.',422);
    if($id){$s=$db->prepare('SELECT MIN(DATE(starts_at)) AS firstDate,MAX(DATE(ends_at)) AS lastDate FROM event_sessions WHERE event_id=?');$s->execute([$id]);$bounds=$s->fetch();if($bounds['firstDate']&&($bounds['firstDate']<$start||$bounds['lastDate']>$end))api_error('VALIDATION_ERROR','Event dates must include its existing sessions.',422);
      $db->prepare('UPDATE ministry_events SET name=?,event_type=?,starts_on=?,ends_on=?,registration_opens=?,registration_closes=?,countdown_enabled=?,public_registration=?,status=?,description=? WHERE id=?')->execute([$name,$type,$start,$end,$opens,$closes,(int)!empty($v['countdown']),(int)!empty($v['publicRegistration']),$status,$description,$id]);}
    else{$db->prepare('INSERT INTO ministry_events(campus_id,name,event_type,starts_on,ends_on,registration_opens,registration_closes,countdown_enabled,public_registration,status,description,public_key,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$actor['campus_id'],$name,$type,$start,$end,$opens,$closes,(int)!empty($v['countdown']),(int)!empty($v['publicRegistration']),$status,$description,bin2hex(random_bytes(24)),$actor['id']]);$id=(int)$db->lastInsertId();}
    api_audit($db,$actor,'EVENT_SAVED','Event',$id);api_ok(['id'=>$id],201);
}
function api_event_setup(PDO $db,int $id,string $kind): never {
    $actor=api_actor($db,true);$event=event_allowed($db,$actor,$id);$v=api_input();
    if($kind==='sessions'){$name=event_text($v['name']??'',120);$start=event_time($v['startsAt']??'');$end=event_time($v['endsAt']??'');if($end<=$start||substr($start,0,10)<$event['starts_on']||substr($end,0,10)>$event['ends_on'])api_error('VALIDATION_ERROR','Session times must fall within the event dates.',422);$db->prepare('INSERT INTO event_sessions(event_id,name,starts_at,ends_at) VALUES(?,?,?,?)')->execute([$id,$name,$start,$end]);}
    elseif($kind==='groups'){$min=filter_var($v['minAge']??null,FILTER_VALIDATE_INT);$max=filter_var($v['maxAge']??null,FILTER_VALIDATE_INT);if($min===false||$max===false||$min<3||$max<$min||$max>19)api_error('VALIDATION_ERROR','Use an age range between 3 and 19.',422);$s=$db->prepare('SELECT id FROM event_groups WHERE event_id=? AND min_age<=? AND max_age>=?');$s->execute([$id,$max,$min]);if($s->fetch())api_error('VALIDATION_ERROR','Use non-overlapping event group ages.',422);$db->prepare('INSERT INTO event_groups(event_id,name,min_age,max_age) VALUES(?,?,?,?)')->execute([$id,event_text($v['name']??'',120),$min,$max]);}
    elseif($kind==='volunteers'){$uid=(int)($v['userId']??0);$duty=$v['duty']??'TEACHER';if(!in_array($duty,['TEACHER','LEAD','CHECK_IN','PICKUP'],true))api_error('VALIDATION_ERROR','Choose a supported duty.',422);$s=$db->prepare("SELECT id FROM staff_users WHERE id=? AND campus_id=? AND is_active=1 AND account_status='VERIFIED' AND team_status<>'INACTIVE'");$s->execute([$uid,$actor['campus_id']]);if(!$s->fetch())api_error('VALIDATION_ERROR','Choose an active campus teacher.',422);$db->prepare('INSERT INTO event_volunteers(event_id,staff_user_id,duty) VALUES(?,?,?) ON DUPLICATE KEY UPDATE duty=VALUES(duty)')->execute([$id,$uid,$duty]);}
    else api_error('ROUTE_NOT_FOUND','Unknown event section.',404);
    api_audit($db,$actor,'EVENT_SETUP_SAVED','Event',$id,['section'=>$kind]);api_ok(['id'=>$id],201);
}
function api_event_family(PDO $db,int $id): never {
    $actor=api_actor($db,true);event_allowed($db,$actor,$id);$phone=api_phone($_GET['phone']??null);if(!$phone)api_error('VALIDATION_ERROR','Enter a valid guardian phone.',422);
    $s=$db->prepare('SELECT g.id,g.family_id,g.first_name,g.last_name,g.phone,g.secondary_phone,f.surname,ca.name AS homeCampus FROM guardians g JOIN families f ON f.id=g.family_id JOIN campuses ca ON ca.id=f.campus_id WHERE f.is_active=1 AND f.campus_id=? ORDER BY g.is_primary DESC,g.id');$s->execute([$actor['campus_id']]);$match=null;foreach($s->fetchAll() as $g)if(api_phone($g['phone'])===$phone||api_phone($g['secondary_phone']??null)===$phone){$match=$g;break;}
    if(!$match)api_error('FAMILY_NOT_FOUND','No registered family found. Use new event registration for a guest.',404);
    $s=$db->prepare('SELECT id,CONCAT(first_name,\' \',last_name) AS name,date_of_birth AS dateOfBirth,medical_notes AS careNotes FROM children WHERE family_id=? AND is_active=1 ORDER BY first_name');$s->execute([$match['family_id']]);api_ok(['guardianName'=>trim($match['first_name'].' '.$match['last_name']),'guardianPhone'=>$phone,'emergencyPhone'=>$match['secondary_phone']?:$phone,'homeCampus'=>$match['homeCampus'],'children'=>$s->fetchAll()]);
}
function event_register(PDO $db,array $event,array $v,bool $public): array {
    $guardian=event_text($v['guardianName']??'');$phone=api_phone($v['guardianPhone']??null);$emergency=api_phone($v['emergencyPhone']??null);$campus=event_text($v['homeCampus']??'',120);
    $children=$v['children']??[];$sessions=$v['sessionIds']??[];if(!$phone||!$emergency||!is_array($children)||!$children||count($children)>10||!is_array($sessions)||!$sessions||count($sessions)>100)api_error('VALIDATION_ERROR','Add contact numbers, at least one child, and their event sessions.',422);
    $ids=array_values(array_unique(array_map('intval',$sessions)));$marks=implode(',',array_fill(0,count($ids),'?'));$s=$db->prepare("SELECT id FROM event_sessions WHERE event_id=? AND id IN ($marks)");$s->execute(array_merge([$event['id']],$ids));if(count($s->fetchAll())!==count($ids))api_error('VALIDATION_ERROR','Choose sessions belonging to this event.',422);
    $prepared=[];foreach($children as $c){$name=event_text($c['name']??'');$dob=event_date($c['dateOfBirth']??'');if($dob>(new DateTimeImmutable('now',new DateTimeZone('Africa/Lagos')))->format('Y-m-d')||tpk_registration_eligibility($dob,$event['starts_on'])!=='ELIGIBLE')api_error('CHILD_TOO_YOUNG','Children must be at least three years old on the event start date.',422);$age=(new DateTimeImmutable($dob))->diff(new DateTimeImmutable($event['starts_on']))->y;if($age>19)api_error('VALIDATION_ERROR','Event childcare registrations are for children aged 3–19.',422);$care=trim((string)($c['careNotes']??''));if(mb_strlen($care)>4000)api_error('VALIDATION_ERROR','Keep care information under 4,000 characters.',422);$source=null;$family=null;
      if(!$public&&!empty($c['id'])){$s=$db->prepare('SELECT c.id,c.family_id,c.first_name,c.last_name,c.date_of_birth,c.medical_notes FROM children c JOIN families f ON f.id=c.family_id WHERE c.id=? AND f.campus_id=? AND c.is_active=1');$s->execute([(int)$c['id'],$event['campus_id']]);$saved=$s->fetch();if(!$saved)api_error('VALIDATION_ERROR','This saved child is not available at the host campus.',422);$s=$db->prepare('SELECT phone,secondary_phone FROM guardians WHERE family_id=?');$s->execute([$saved['family_id']]);$linked=false;foreach($s->fetchAll() as $g)if(api_phone($g['phone'])===$phone||api_phone($g['secondary_phone']??null)===$phone)$linked=true;if(!$linked)api_error('VALIDATION_ERROR','Use the selected child’s registered guardian phone.',422);$source=(int)$saved['id'];$family=(int)$saved['family_id'];$name=trim($saved['first_name'].' '.$saved['last_name']);$dob=$saved['date_of_birth'];$care=$saved['medical_notes'];}
      $s=$db->prepare('SELECT c.id FROM event_children c JOIN event_registrations r ON r.id=c.registration_id WHERE r.event_id=? AND r.guardian_phone=? AND c.name=? AND c.date_of_birth=?');$s->execute([$event['id'],$phone,$name,$dob]);if($s->fetch())api_error('ALREADY_REGISTERED','This child is already registered for this event. Ask the event desk to review their sessions.',409);
      $s=$db->prepare('SELECT id FROM event_groups WHERE event_id=? AND min_age<=? AND max_age>=?');$s->execute([$event['id'],$age,$age]);$prepared[]=[$source,$name,$dob,$care?:null,$s->fetchColumn()?:null,$family];}
    $reference=strtoupper(bin2hex(random_bytes(8)));$db->beginTransaction();try{$db->prepare('INSERT INTO event_registrations(event_id,reference_code,guardian_name,guardian_phone,emergency_phone,home_campus,family_id) VALUES(?,?,?,?,?,?,?)')->execute([$event['id'],$reference,$guardian,$phone,$emergency,$campus,$prepared[0][5]]);$rid=(int)$db->lastInsertId();foreach($prepared as $c){
      $age=(new DateTimeImmutable($c[2]))->diff(new DateTimeImmutable($event['starts_on']))->y;
      if(tpk_registration_eligibility($c[2],$event['starts_on'])!=='ELIGIBLE'||$age>19)api_error('VALIDATION_ERROR','Every child must be aged 3–19 on the event start date.',422);
      $s=$db->prepare('SELECT id FROM event_groups WHERE event_id=? AND min_age<=? AND max_age>=?');$s->execute([$event['id'],$age,$age]);$group=$s->fetchColumn()?:null;
      $key=hash('sha256',$phone.'|'.mb_strtolower(preg_replace('/\s+/u',' ',trim($c[1]))).'|'.$c[2]);
      $db->prepare('INSERT INTO event_children(event_id,identity_key,registration_id,child_id,name,date_of_birth,care_notes,group_id) VALUES(?,?,?,?,?,?,?,?)')->execute([$event['id'],$key,$rid,$c[0],$c[1],$c[2],$c[3],$group]);$cid=(int)$db->lastInsertId();foreach($ids as $sid)$db->prepare('INSERT INTO event_child_sessions(child_id,session_id) VALUES(?,?)')->execute([$cid,$sid]);}$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($e instanceof PDOException&&$e->getCode()==='23000')api_error('ALREADY_REGISTERED','This child is already registered for the event.',409);throw $e;}return ['referenceCode'=>$reference,'children'=>count($prepared)];
}
function api_event_registration(PDO $db,int $id): never {$actor=api_actor($db,true);$event=event_allowed($db,$actor,$id);if($event['status']==='CANCELLED')api_error('EVENT_CLOSED','This event is cancelled.',409);$result=event_register($db,$event,api_input(),false);api_audit($db,$actor,'EVENT_REGISTRATION_CREATED','Event',$id);api_ok($result,201);}
function api_public_event(PDO $db,string $key,bool $register=false): never {
    $s=$db->prepare("SELECT * FROM ministry_events WHERE public_key=? AND status='PUBLISHED' AND public_registration=1");$s->execute([$key]);$e=$s->fetch();if(!$e)api_error('EVENT_NOT_FOUND','This registration page is not available.',404);$today=(new DateTimeImmutable('now',new DateTimeZone('Africa/Lagos')))->format('Y-m-d');$open=$today>=$e['registration_opens']&&$today<=$e['registration_closes'];
    if($register){if(!$open)api_error('REGISTRATION_CLOSED','Event registration is not currently open.',409);
      $ip=hash('sha256','event-registration|'.($_SERVER['REMOTE_ADDR']??'unknown'));
      $s=$db->prepare('SELECT COUNT(*) FROM event_registration_attempts WHERE ip_hash=? AND attempted_at>DATE_SUB(NOW(),INTERVAL 1 HOUR)');$s->execute([$ip]);if((int)$s->fetchColumn()>=20)api_error('TOO_MANY_ATTEMPTS','Too many registration attempts. Please try again later or speak to the event desk.',429);
      $db->prepare('INSERT INTO event_registration_attempts(ip_hash) VALUES(?)')->execute([$ip]);
      api_ok(event_register($db,$e,api_input(),true),201);}
    $s=$db->prepare('SELECT id,name,starts_at AS startsAt,ends_at AS endsAt FROM event_sessions WHERE event_id=? ORDER BY starts_at');$s->execute([$e['id']]);api_ok(['name'=>$e['name'],'description'=>$e['description'],'startDate'=>$e['starts_on'],'endDate'=>$e['ends_on'],'registrationOpens'=>$e['registration_opens'],'registrationCloses'=>$e['registration_closes'],'open'=>$open,'sessions'=>$s->fetchAll()]);
}
function api_event_arrival(PDO $db,int $id,bool $pickup=false): never {
    $actor=api_actor($db);$e=event_allowed($db,$actor,$id);if(!event_operator($db,$actor,$id,$pickup?'PICKUP':'CHECK_IN'))api_error('FORBIDDEN','An assigned event operator is required.',403);if($e['status']==='CANCELLED')api_error('EVENT_CLOSED','This event is cancelled.',409);$v=api_input();
    if($pickup){$code=strtoupper(trim((string)($v['pickupCode']??'')));$collector=event_text($v['collectorName']??'');if(empty($v['guardianVerified']))api_error('VERIFICATION_REQUIRED','Verify the registered guardian in person before release.',422);$db->beginTransaction();try{$s=$db->prepare('SELECT a.id,a.picked_up_at,r.guardian_name FROM event_attendance a JOIN event_children c ON c.id=a.child_id JOIN event_registrations r ON r.id=c.registration_id WHERE a.pickup_code=? AND r.event_id=? FOR UPDATE');$s->execute([$code,$id]);$a=$s->fetch();if(!$a)api_error('PICKUP_NOT_FOUND','No event pickup matches this code.',404);if($a['picked_up_at'])api_error('ALREADY_PICKED_UP','This child has already been released.',409);if(mb_strtolower($collector)!==mb_strtolower(trim($a['guardian_name'])))api_error('COLLECTOR_NOT_AUTHORISED','Only the registered guardian can collect. Refer any change to the event lead.',422);$db->prepare('UPDATE event_attendance SET picked_up_at=NOW(),picked_up_by=?,collector_name=? WHERE id=?')->execute([$actor['id'],$collector,$a['id']]);api_audit($db,$actor,'EVENT_PICKUP','EventAttendance',(int)$a['id']);$db->commit();}catch(Throwable $err){if($db->inTransaction())$db->rollBack();throw $err;}api_ok(['pickedUp'=>true]);}
    $cid=(int)($v['childId']??0);$sid=(int)($v['sessionId']??0);$s=$db->prepare('SELECT s.starts_at,s.ends_at FROM event_child_sessions cs JOIN event_children c ON c.id=cs.child_id JOIN event_registrations r ON r.id=c.registration_id JOIN event_sessions s ON s.id=cs.session_id WHERE cs.child_id=? AND cs.session_id=? AND r.event_id=? AND s.event_id=r.event_id');$s->execute([$cid,$sid,$id]);$session=$s->fetch();if(!$session)api_error('NOT_REGISTERED','The child must be registered for this event session.',422);$now=(new DateTimeImmutable('now',new DateTimeZone('Africa/Lagos')))->format('Y-m-d H:i:s');if(substr($now,0,10)!==substr($session['starts_at'],0,10)||$now>$session['ends_at'])api_error('SESSION_CLOSED','Check-in is available only on the session day before it ends.',409);
    $code=strtoupper(bin2hex(random_bytes(6)));$db->prepare('INSERT INTO event_attendance(child_id,session_id,pickup_code,checked_in_at,checked_in_by) VALUES(?,?,?,NOW(),?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)')->execute([$cid,$sid,$code,$actor['id']]);$aid=(int)$db->lastInsertId();$s=$db->prepare('SELECT pickup_code AS pickupCode,picked_up_at AS pickedUpAt FROM event_attendance WHERE id=?');$s->execute([$aid]);api_audit($db,$actor,'EVENT_CHECK_IN','EventAttendance',$aid);api_ok($s->fetch(),201);
}
function api_event_group_assignment(PDO $db,int $id): never {$actor=api_actor($db,true);event_allowed($db,$actor,$id);$v=api_input();$cid=(int)($v['childId']??0);$gid=(int)($v['groupId']??0);$s=$db->prepare('SELECT c.id FROM event_children c JOIN event_registrations r ON r.id=c.registration_id JOIN event_groups g ON g.event_id=r.event_id WHERE r.event_id=? AND c.id=? AND g.id=?');$s->execute([$id,$cid,$gid]);if(!$s->fetch())api_error('VALIDATION_ERROR','Choose a child and group from this event.',422);$db->prepare('UPDATE event_children SET group_id=? WHERE id=?')->execute([$gid,$cid]);api_audit($db,$actor,'EVENT_GROUP_ASSIGNED','EventChild',$cid);api_ok(['id'=>$cid]);}
function api_event_duplicate(PDO $db,int $id): never {
    $actor=api_actor($db,true);$e=event_allowed($db,$actor,$id);$v=api_input();$name=event_text($v['name']??'');$start=event_date($v['startDate']??'');$offset=(new DateTimeImmutable($e['starts_on']))->diff(new DateTimeImmutable($start));$move=fn($value)=>(new DateTimeImmutable($value))->add($offset)->format(strlen($value)>10?'Y-m-d H:i:s':'Y-m-d');
    $db->beginTransaction();try{$db->prepare("INSERT INTO ministry_events(campus_id,name,event_type,starts_on,ends_on,registration_opens,registration_closes,countdown_enabled,public_registration,status,description,public_key,created_by) VALUES(?,?,?,?,?,?,?,?,0,'DRAFT',?,?,?)")->execute([$actor['campus_id'],$name,$e['event_type'],$start,$move($e['ends_on']),$move($e['registration_opens']),$move($e['registration_closes']),$e['countdown_enabled'],$e['description'],bin2hex(random_bytes(24)),$actor['id']]);$new=(int)$db->lastInsertId();$s=$db->prepare('SELECT * FROM event_sessions WHERE event_id=?');$s->execute([$id]);foreach($s->fetchAll() as $row)$db->prepare('INSERT INTO event_sessions(event_id,name,starts_at,ends_at) VALUES(?,?,?,?)')->execute([$new,$row['name'],$move($row['starts_at']),$move($row['ends_at'])]);$s=$db->prepare('SELECT name,min_age,max_age FROM event_groups WHERE event_id=?');$s->execute([$id]);foreach($s->fetchAll() as $group)$db->prepare('INSERT INTO event_groups(event_id,name,min_age,max_age) VALUES(?,?,?,?)')->execute([$new,$group['name'],$group['min_age'],$group['max_age']]);api_audit($db,$actor,'EVENT_DUPLICATED','Event',$new,['sourceId'=>$id]);$db->commit();}catch(Throwable $err){if($db->inTransaction())$db->rollBack();throw $err;}api_ok(['id'=>$new],201);
}
