<?php
declare(strict_types=1);

// Raw JSON is staging/provenance only. Committed facts go into relational tables.
function event_import_campus_code(string $code):string{return $code==='PETRA-WUSE'?'PETRA-MABUSHI':$code;}
function event_import_issues(PDO $db,int $event,array $row,string $kind): array {
    $errors=[];
    if(!empty($row['requiresReview']))$errors[]='Source ambiguity needs review; correct the row and clear requiresReview, or skip it.';
    foreach(['sourceKey'=>180,'name'=>180,'guardianName'=>180,'guardianPhone'=>40,'emergencyPhone'=>40,'alternatePhone'=>40,'ageQualifier'=>30,'homeCampusRaw'=>120,'homeAddress'=>4000,'careNotes'=>4000,'responsibility'=>120,'email'=>150,'phone'=>40,'whatsapp'=>40] as $key=>$limit)if(isset($row[$key])&&(!is_string($row[$key])||mb_strlen($row[$key])>$limit))$errors[]="Invalid $key (max $limit characters).";
    foreach(['days','contacts'] as $key)if(isset($row[$key])&&!is_array($row[$key]))return ["$key must be a list of records."];
    if(empty($row['sourceKey'])||strlen((string)$row['sourceKey'])>180)$errors[]='A stable sourceKey is required.';
    if(empty(trim((string)($row['name']??'')))||mb_strlen((string)($row['name']??''))>180)$errors[]='Child / volunteer name is required (max 180 characters).';
    if($kind==='VOLUNTEERS'){
        if(empty($row['userId'])&&!filter_var($row['email']??'',FILTER_VALIDATE_EMAIL))$errors[]='Supply an existing staff ID or a valid email. Passwords are never imported.';
        if(!empty($row['userId'])){$q=$db->prepare('SELECT id FROM staff_users WHERE id=?');$q->execute([(int)$row['userId']]);if(!$q->fetchColumn())$errors[]='Existing staff ID was not found.';}
        if(!in_array($row['duty']??'TEACHER',['TEACHER','LEAD','CHECK_IN','PICKUP'],true))$errors[]='Invalid event access duty.';
    }else{
        $q=$db->prepare('SELECT id FROM event_children WHERE event_id=? AND source_key=?');$q->execute([$event,is_string($row['sourceKey']??null)?$row['sourceKey']:'']);if($q->fetchColumn())$errors[]='Source child already imported.';
        if(isset($row['age'])&&(!is_numeric($row['age'])||$row['age']<0||$row['age']>19))$errors[]='Reported age must be 0–19 or null; do not invent a birth date.';
        if(!empty($row['dateOfBirth'])){$d=DateTimeImmutable::createFromFormat('!Y-m-d',(string)$row['dateOfBirth']);if(!$d||$d->format('Y-m-d')!==$row['dateOfBirth'])$errors[]='Invalid birth date.';}
        if(!empty($row['existingChildId'])){$q=$db->prepare('SELECT c.id FROM children c JOIN families f ON f.id=c.family_id JOIN ministry_events e ON e.campus_id=f.campus_id WHERE e.id=? AND c.id=?');$q->execute([$event,(int)$row['existingChildId']]);if(!$q->fetchColumn())$errors[]='The selected existing child is not in the host campus.';}
        if(!empty($row['gender'])&&!in_array($row['gender'],['MALE','FEMALE'],true))$errors[]='Invalid gender.';
        foreach(['scholarship','food'] as $key)if(isset($row[$key])&&!is_bool($row[$key]))$errors[]="$key must be true, false or null.";
        $seen=[];foreach($row['days']??[] as $day){if(!is_array($day)){ $errors[]='Invalid day record.';continue; }$number=(int)($day['dayNumber']??0);if(isset($seen[$number]))$errors[]='Each attendance day must occur only once per child.';$seen[$number]=true;$q=$db->prepare('SELECT id FROM event_days WHERE event_id=? AND day_number=?');$q->execute([$event,$number]);if(!$q->fetchColumn())$errors[]='Map every attendance day to a saved event day.';foreach(['present','pickedUp','food'] as $key)if(isset($day[$key])&&!is_bool($day[$key]))$errors[]="$key must be true, false or null.";if(isset($day['cardNumber'])&&(!is_string($day['cardNumber'])||strlen($day['cardNumber'])>50))$errors[]='Invalid card number.';}
        foreach($row['contacts']??[] as $contact)if(!is_array($contact)||!in_array($contact['type']??'',['GUARDIAN','EMERGENCY','DOCTOR','PICKUP'],true)||mb_strlen((string)($contact['name']??''))>180||strlen((string)($contact['phone']??''))>40||mb_strlen((string)($contact['sourceText']??''))>4000)$errors[]='Invalid contact details.';
    }
    if(!empty($row['homeCampusId'])){$q=$db->prepare('SELECT id FROM campuses WHERE id=?');$q->execute([(int)$row['homeCampusId']]);if(!$q->fetchColumn())$errors[]='Home campus does not exist.';}
    elseif(!empty($row['homeCampusCode'])){$q=$db->prepare('SELECT id FROM campuses WHERE code=?');$q->execute([event_import_campus_code($row['homeCampusCode'])]);if(!$q->fetchColumn())$errors[]='Map the homeCampusCode to a saved campus.';}
    foreach(['sessionId'=>'event_sessions','groupId'=>'event_groups'] as $key=>$table)if(!empty($row[$key])){$q=$db->prepare("SELECT id FROM $table WHERE id=? AND event_id=?");$q->execute([(int)$row[$key],$event]);if(!$q->fetchColumn())$errors[]="Invalid $key for this event.";}
    if(strlen(json_encode($row))>100000)$errors[]='Source row too large.';
    return array_values(array_unique($errors));
}
function event_import_child(PDO $db,array $actor,int $event,array $row): int {
    $q=$db->prepare('SELECT id FROM event_children WHERE event_id=? AND source_key=?');$q->execute([$event,$row['sourceKey']]);if($q->fetchColumn())api_error('SOURCE_ALREADY_IMPORTED','This source child already exists. Edit the record rather than importing it twice.',409);
    $campus=isset($row['homeCampusId'])?(int)$row['homeCampusId']:null;if(!$campus&&!empty($row['homeCampusCode'])){$q=$db->prepare('SELECT id FROM campuses WHERE code=?');$q->execute([event_import_campus_code($row['homeCampusCode'])]);$campus=(int)$q->fetchColumn();}
    $core=!empty($row['existingChildId'])?(int)$row['existingChildId']:null;$family=null;$guardian=null;
    if($core){$q=$db->prepare('SELECT c.family_id,g.id AS guardian_id FROM children c LEFT JOIN guardians g ON g.family_id=c.family_id AND g.is_primary=1 WHERE c.id=?');$q->execute([$core]);$linked=$q->fetch();$family=$linked['family_id'];$guardian=$linked['guardian_id'];}
    // Do not auto-link by name alone. Only an exact child + guardian phone match
    // can reuse a record; uncertain matches remain event guests for admin review.
    if(!$core&&!empty($row['guardianPhone'])){$q=$db->prepare('SELECT DISTINCT c.id,c.family_id,g.id AS guardian_id,g.phone FROM children c JOIN families f ON f.id=c.family_id JOIN guardians g ON g.family_id=f.id WHERE f.campus_id=? AND LOWER(TRIM(CONCAT(c.first_name,\' \',c.last_name)))=LOWER(TRIM(?))');$q->execute([$actor['campus_id'],$row['name']]);$matches=array_values(array_filter($q->fetchAll(),fn($c)=>api_phone($c['phone'])&&api_phone($c['phone'])===api_phone($row['guardianPhone'])));if(count($matches)===1){$core=(int)$matches[0]['id'];$family=$matches[0]['family_id'];$guardian=$matches[0]['guardian_id'];}}
    $q=$db->prepare('INSERT INTO event_registrations(event_id,reference_code,guardian_name,guardian_phone,emergency_phone,home_campus,home_campus_id,family_id,guardian_id,home_address,alternate_phone) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$event,strtoupper(bin2hex(random_bytes(8))),$row['guardianName']??'Not recorded',$row['guardianPhone']??null,$row['emergencyPhone']??null,$row['homeCampusRaw']??'Not recorded',$campus,$family,$guardian,$row['homeAddress']??null,$row['alternatePhone']??null]);$rid=(int)$db->lastInsertId();
    $db->prepare('INSERT INTO event_children(event_id,identity_key,registration_id,child_id,name,date_of_birth,care_notes,group_id,home_campus_id,reported_age,age_qualifier,gender,scholarship,food,source_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$event,hash('sha256','archive|'.$row['sourceKey']),$rid,$core,$row['name'],$row['dateOfBirth']??null,$row['careNotes']??null,$row['groupId']??null,$campus,$row['age']??null,$row['ageQualifier']??null,$row['gender']??null,isset($row['scholarship'])?(int)$row['scholarship']:null,isset($row['food'])?(int)$row['food']:null,$row['sourceKey']]);$cid=(int)$db->lastInsertId();
    foreach($row['contacts']??[] as $c)$db->prepare('INSERT INTO event_registration_contacts(registration_id,child_id,contact_type,name,phone,relationship,source_text) VALUES(?,?,?,?,?,?,?)')->execute([$rid,$cid,$c['type'],$c['name']??null,$c['phone']??null,$c['relationship']??null,$c['sourceText']??null]);
    foreach($row['days']??[] as $day){$q=$db->prepare('SELECT id FROM event_days WHERE event_id=? AND day_number=?');$q->execute([$event,$day['dayNumber']]);$did=(int)$q->fetchColumn();$db->prepare('INSERT INTO event_historical_attendance(child_id,day_id,present,picked_up,food,source_key,recorded_by) VALUES(?,?,?,?,?,?,?)')->execute([$cid,$did,isset($day['present'])?(int)$day['present']:null,isset($day['pickedUp'])?(int)$day['pickedUp']:null,isset($day['food'])?(int)$day['food']:null,$row['sourceKey'],$actor['id']]);if(!empty($day['cardNumber']))$db->prepare('INSERT INTO event_registration_cards(child_id,day_id,card_number) VALUES(?,?,?)')->execute([$cid,$did,(string)$day['cardNumber']]);
      $q=$db->prepare('SELECT id FROM event_sessions WHERE event_id=? AND day_id=?');$q->execute([$event,$did]);foreach($q->fetchAll() as $s)$db->prepare('INSERT IGNORE INTO event_child_sessions(child_id,session_id) VALUES(?,?)')->execute([$cid,$s['id']]);}
    return $cid;
}
function api_event_import(PDO $db,int $event,int $batch=0,string $action=''): never {
    $actor=api_actor($db,true);$e=event_allowed($db,$actor,$event);$method=api_method();$v=$method==='GET'?[]:api_input();
    if(!$batch){if($method!=='POST')api_error('METHOD_NOT_ALLOWED','Create an import preview first.',405);$rows=$v['rows']??[];$kind=$v['kind']??'CHILDREN';if(!is_array($rows)||!$rows||count($rows)>1000||!in_array($kind,['CHILDREN','VOLUNTEERS'],true)||strlen(json_encode($rows))>4*1024*1024)api_error('VALIDATION_ERROR','Preview 1–1,000 structured children or volunteer rows (max 4 MB).',422);
      $hash=hash('sha256',json_encode($rows));$q=$db->prepare('SELECT id,state FROM event_import_batches WHERE event_id=? AND source_hash=? AND import_kind=?');$q->execute([$event,$hash,$kind]);if($existing=$q->fetch())api_ok(['id'=>(int)$existing['id'],'state'=>$existing['state'],'duplicate'=>true]);
      $db->beginTransaction();try{$db->prepare('INSERT INTO event_import_batches(event_id,source_name,source_hash,import_kind,created_by) VALUES(?,?,?,?,?)')->execute([$event,event_text($v['sourceName']??'Historical import',255),$hash,$kind,$actor['id']]);$batch=(int)$db->lastInsertId();$keys=[];foreach($rows as $i=>$row){if(!is_array($row))api_error('VALIDATION_ERROR','Every row must be an object.',422);$key=(string)($row['sourceKey']??('row-'.($i+1)));if(isset($keys[$key]))api_error('VALIDATION_ERROR','Source keys must be unique within the file.',422);$keys[$key]=true;$issues=event_import_issues($db,$event,$row,$kind);$db->prepare('INSERT INTO event_import_rows(batch_id,source_key,payload,issues,resolution) VALUES(?,?,?,?,?)')->execute([$batch,$key,json_encode($row),json_encode($issues),$issues?'PENDING':'READY']);}$db->commit();}catch(Throwable $err){if($db->inTransaction())$db->rollBack();throw $err;}api_ok(['id'=>$batch],201);
    }
    $q=$db->prepare('SELECT * FROM event_import_batches WHERE id=? AND event_id=?');$q->execute([$batch,$event]);$b=$q->fetch();if(!$b)api_error('IMPORT_NOT_FOUND','Import not found for this event.',404);
    if($method==='GET'){$q=$db->prepare('SELECT id,source_key AS sourceKey,payload,issues,resolution FROM event_import_rows WHERE batch_id=? ORDER BY id');$q->execute([$batch]);$rows=$q->fetchAll();foreach($rows as &$r){$r['payload']=json_decode($r['payload'],true);$r['issues']=json_decode($r['issues'],true);}unset($r);api_ok(['id'=>$batch,'state'=>$b['state'],'kind'=>$b['import_kind'],'rows'=>$rows]);}
    if($b['state']==='COMMITTED')api_ok(['id'=>$batch,'alreadyCommitted'=>true]);
if($action==='row'&&$method==='PATCH'){$db->beginTransaction();$q=$db->prepare('SELECT state FROM event_import_batches WHERE id=? FOR UPDATE');$q->execute([$batch]);if($q->fetchColumn()==='COMMITTED'){$db->commit();api_ok(['id'=>$batch,'alreadyCommitted'=>true]);}$q=$db->prepare('SELECT source_key,resolution FROM event_import_rows WHERE id=? AND batch_id=? FOR UPDATE');$q->execute([(int)($v['rowId']??0),$batch]);$saved=$q->fetch();$sourceKey=$saved['source_key']??null;if(!$sourceKey)api_error('IMPORT_ROW_NOT_FOUND','Source row not found.',404);if($saved['resolution']==='IMPORTED')api_error('IMPORT_ROW_COMMITTED','Imported source rows are immutable; edit the event record instead.',409);$row=$v['payload']??null;if(!is_array($row))api_error('VALIDATION_ERROR','Supply the corrected structured row.',422);if(($row['sourceKey']??null)!==$sourceKey)api_error('VALIDATION_ERROR','The stable source key cannot be changed.',422);$issues=event_import_issues($db,$event,$row,$b['import_kind']);$resolution=($v['skip']??false)?'SKIPPED':($issues?'PENDING':'READY');$db->prepare('UPDATE event_import_rows SET payload=?,issues=?,resolution=? WHERE id=? AND batch_id=?')->execute([json_encode($row),json_encode($issues),$resolution,(int)($v['rowId']??0),$batch]);$db->commit();api_ok(['issues'=>$issues,'resolution'=>$resolution]);}
    if($action!=='commit'||$method!=='POST'||($v['confirm']??false)!==true)api_error('CONFIRMATION_REQUIRED','Review and confirm the import before committing.',422);
    if($b['import_kind']==='CHILDREN'&&event_lifecycle($e)!=='COMPLETED'&&$e['status']!=='ARCHIVED')api_error('HISTORICAL_EVENT_REQUIRED','Historical attendance imports require a completed or archived event.',422);
    $db->beginTransaction();try{$q=$db->prepare('SELECT state FROM event_import_batches WHERE id=? FOR UPDATE');$q->execute([$batch]);if($q->fetchColumn()==='COMMITTED'){$db->commit();api_ok(['id'=>$batch,'alreadyCommitted'=>true]);}
      $q=$db->prepare('SELECT * FROM event_import_rows WHERE batch_id=? ORDER BY id FOR UPDATE');$q->execute([$batch]);$rows=$q->fetchAll();$count=0;
foreach($rows as $r){if(in_array($r['resolution'],['SKIPPED','IMPORTED'],true))continue;$row=json_decode($r['payload'],true);$issues=event_import_issues($db,$event,$row,$b['import_kind']);if($issues&&($v['readyOnly']??false)===true){$db->prepare("UPDATE event_import_rows SET resolution='PENDING',issues=? WHERE id=?")->execute([json_encode($issues),$r['id']]);continue;}if($issues)api_error('IMPORT_REVIEW_REQUIRED','Correct or explicitly skip every flagged row before committing.',422);
        $cid=null;$uid=null;if($b['import_kind']==='CHILDREN')$cid=event_import_child($db,$actor,$event,$row);else{$uid=event_volunteer_account($db,$actor,$row);$campus=event_campus($db,$row['homeCampusId']??null);if(!$campus&&!empty($row['homeCampusCode'])){$x=$db->prepare('SELECT id FROM campuses WHERE code=?');$x->execute([event_import_campus_code($row['homeCampusCode'])]);$campus=(int)$x->fetchColumn();}$db->prepare('INSERT IGNORE INTO event_volunteers(event_id,staff_user_id,duty,home_campus_id,membership_status) VALUES(?,?,?,?,\'ACTIVE\')')->execute([$event,$uid,$row['duty']??'TEACHER',$campus]);$db->prepare('INSERT INTO event_volunteer_assignments(event_id,staff_user_id,session_id,group_id,responsibility) VALUES(?,?,?,?,?)')->execute([$event,$uid,$row['sessionId']??null,$row['groupId']??null,$row['responsibility']??'Volunteer']);}
        $db->prepare("UPDATE event_import_rows SET resolution='IMPORTED',event_child_id=?,staff_user_id=? WHERE id=?")->execute([$cid,$uid,$r['id']]);$count++;}
      $pending=$db->prepare("SELECT COUNT(*) FROM event_import_rows WHERE batch_id=? AND resolution='PENDING'");$pending->execute([$batch]);$state=$pending->fetchColumn()?'PARTIAL':'COMMITTED';$db->prepare('UPDATE event_import_batches SET state=?,committed_at=NOW() WHERE id=?')->execute([$state,$batch]);api_audit($db,$actor,'EVENT_HISTORY_IMPORTED','Event',$event,['batchId'=>$batch,'count'=>$count,'kind'=>$b['import_kind']]);$db->commit();
    }catch(Throwable $err){if($db->inTransaction())$db->rollBack();throw $err;}api_ok(['id'=>$batch,'imported'=>$count,'state'=>$state]);
}
