<?php
declare(strict_types=1);

/* REST API v1. Apply database/v1_migration.sql before using these routes. */
require_once dirname(__DIR__) . '/config.php';

function api_ok(mixed $data, int $status = 200, ?array $meta = null): never {
    http_response_code($status); header('Content-Type: application/json; charset=utf-8');
    header('Access-Control-Allow-Origin: ' . tpk_cors_origin()); header('Vary: Origin');
    header('Access-Control-Allow-Headers: Content-Type, Authorization, X-TPK-User-Id');
    header('Access-Control-Allow-Methods: GET, POST, PATCH, DELETE, OPTIONS');
    $payload = ['success' => true, 'data' => $data]; if ($meta) $payload['meta'] = $meta;
    echo json_encode($payload, JSON_UNESCAPED_SLASHES); exit;
}
function api_error(string $code, string $message, int $status = 400): never {
    http_response_code($status); header('Content-Type: application/json; charset=utf-8');
    header('Access-Control-Allow-Origin: ' . tpk_cors_origin()); header('Vary: Origin');
    echo json_encode(['success' => false, 'error' => ['code' => $code, 'message' => $message]], JSON_UNESCAPED_SLASHES); exit;
}
function api_input(): array { $v = json_decode(file_get_contents('php://input') ?: '{}', true); if (!is_array($v)) api_error('INVALID_JSON', 'Request body must be valid JSON.'); return $v; }
function api_path(): string { return rtrim(parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/', '/'); }
function api_method(): string { return strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET'); }
function api_phone(?string $value): ?string { $v = preg_replace('/\D+/', '', (string)$value); if (!$v) return null; if (str_starts_with($v, '234') && strlen($v) === 13) $v = '0' . substr($v, 3); return strlen($v) === 11 && str_starts_with($v, '0') ? $v : null; }
function api_page(): array { $page=max(1,(int)($_GET['page']??1)); $limit=min(100,max(1,(int)($_GET['limit']??25))); return [$page,$limit,($page-1)*$limit]; }
function api_db(): PDO { return db(); }
function api_actor(PDO $db, bool $super = false): array {
    $authorization = $_SERVER['HTTP_AUTHORIZATION'] ?? '';
    if (!preg_match('/^Bearer\\s+([a-f0-9]{64})$/i', $authorization, $match)) api_error('UNAUTHENTICATED','Sign in is required.',401);
    $s=$db->prepare("SELECT s.id,s.campus_id,s.name,s.email,s.is_active,s.access_level,s.team_status,s.account_status FROM staff_sessions ss JOIN staff_users s ON s.id=ss.staff_user_id WHERE ss.token_hash=? AND ss.revoked_at IS NULL AND ss.expires_at>NOW() LIMIT 1");
    $s->execute([hash('sha256', $match[1])]); $user=$s->fetch();
    if (!$user || !(bool)$user['is_active'] || $user['account_status'] !== 'VERIFIED' || $user['team_status'] === 'INACTIVE') api_error('UNAUTHENTICATED','Your account is not active.',401);
    if ($super && $user['access_level'] !== 'TPK_SUPER_ADMIN') api_error('FORBIDDEN','TPK Super Admin access is required.',403);
    return $user;
}
function api_audit(PDO $db, array $actor, string $action, string $entity, int $id, array $meta=[]): void {
    audit($db,(int)$actor['campus_id'],$action,$entity,$id,$meta);
}
function api_permitted_class_ids(PDO $db, array $actor): ?array {
    if ($actor['access_level'] === 'TPK_SUPER_ADMIN') return null;
    $ids=[];
    $s=$db->prepare("SELECT DISTINCT class_id FROM roster_assignments WHERE user_id=? AND class_id IS NOT NULL AND assignment_date >= DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND assignment_date <= DATE_ADD(CURDATE(), INTERVAL 30 DAY) AND status NOT IN ('CANCELLED','REPLACED')"); $s->execute([$actor['id']]);
    foreach($s->fetchAll() as $row) $ids[]=(int)$row['class_id'];
    if (!$ids) { $s=$db->prepare('SELECT class_id FROM staff_class_assignments WHERE staff_user_id=? AND is_active=1'); $s->execute([$actor['id']]); foreach($s->fetchAll() as $row) $ids[]=(int)$row['class_id']; }
    return array_values(array_unique($ids));
}
function api_child_select(): string { return 'c.id,c.first_name AS firstName,c.last_name AS lastName,c.date_of_birth AS dateOfBirth,c.gender,c.school_grade AS schoolGrade,c.class_id AS classId,c.is_active AS active,c.class_assignment_required AS classAssignmentRequired,cl.name AS className'; }
function api_child_allowed(PDO $db, array $actor, int $id): array {
    $s=$db->prepare('SELECT '.api_child_select().' FROM children c LEFT JOIN classes cl ON cl.id=c.class_id WHERE c.id=? LIMIT 1'); $s->execute([$id]); $child=$s->fetch();
    if (!$child) api_error('CHILD_NOT_FOUND','Child not found.',404);
    $allowed=api_permitted_class_ids($db,$actor); if ($allowed !== null && (!in_array((int)$child['classId'],$allowed,true))) api_error('FORBIDDEN','This child is outside your assigned classes.',403);
    return $child;
}
function api_list_campuses(PDO $db): never { api_actor($db); api_ok($db->query('SELECT id,name,code,timezone FROM campuses ORDER BY name')->fetchAll()); }
function api_campus(PDO $db, int $id): never {
    $actor=api_actor($db,api_method()==='PATCH');
    if (api_method()==='GET') { $s=$db->prepare('SELECT id,name,code,timezone FROM campuses WHERE id=?'); $s->execute([$id]); $row=$s->fetch(); if(!$row) api_error('CAMPUS_NOT_FOUND','Campus not found.',404); api_ok($row); }
    $v=api_input(); $allowed=array_intersect_key($v,array_flip(['name','code','timezone'])); if(!$allowed) api_error('VALIDATION_ERROR','No editable campus fields were supplied.',422);
    $set=[];$params=[]; foreach($allowed as $key=>$value){$set[]="$key=?";$params[]=$value;} $params[]=$id; $db->prepare('UPDATE campuses SET '.implode(',',$set).' WHERE id=?')->execute($params); api_audit($db,$actor,'CAMPUS_UPDATED','Campus',$id,$allowed); api_ok(['id'=>$id,'updated'=>true]);
}
function api_list_classes(PDO $db): never {
    $actor=api_actor($db); $allowed=api_permitted_class_ids($db,$actor); $where=['c.is_active=1'];$params=[];
    if(isset($_GET['campusId'])){$where[]='c.campus_id=?';$params[]=(int)$_GET['campusId'];}
    if($allowed!==null){if(!$allowed)api_ok([]);$where[]='c.id IN ('.implode(',',array_fill(0,count($allowed),'?')).')';$params=array_merge($params,$allowed);}
    $s=$db->prepare('SELECT c.id,c.campus_id AS campusId,c.name,c.min_age AS minAge,c.max_age AS maxAge,c.age_label AS ageLabel,c.display_order AS displayOrder,c.is_active AS active FROM classes c WHERE '.implode(' AND ',$where).' ORDER BY c.display_order,c.name');$s->execute($params);api_ok($s->fetchAll());
}
function api_class(PDO $db,int $id): never {
    $actor=api_actor($db,api_method()!=='GET'); if(api_method()==='GET'){ $s=$db->prepare('SELECT id,campus_id AS campusId,name,min_age AS minAge,max_age AS maxAge,age_label AS ageLabel,display_order AS displayOrder,is_active AS active FROM classes WHERE id=?');$s->execute([$id]);$row=$s->fetch();if(!$row)api_error('CLASS_NOT_FOUND','Class not found.',404);api_ok($row); }
    $v=api_input();$allowed=array_intersect_key($v,array_flip(['name','minAge','maxAge','ageLabel','displayOrder','active']));if(!$allowed)api_error('VALIDATION_ERROR','No editable class fields were supplied.',422);$map=['minAge'=>'min_age','maxAge'=>'max_age','ageLabel'=>'age_label','displayOrder'=>'display_order','active'=>'is_active'];$sets=[];$params=[];foreach($allowed as $k=>$value){$sets[]=($map[$k]??$k).'=?';$params[]=$value;}$params[]=$id;$db->prepare('UPDATE classes SET '.implode(',',$sets).' WHERE id=?')->execute($params);api_audit($db,$actor,'CLASS_UPDATED','Class',$id,$allowed);api_ok(['id'=>$id,'updated'=>true]);
}
function api_create_class(PDO $db): never { $actor=api_actor($db,true);$v=api_input();foreach(['campusId','name','ageLabel'] as $key)if(empty($v[$key]))api_error('VALIDATION_ERROR',"$key is required.",422);$s=$db->prepare('INSERT INTO classes(campus_id,name,age_label,min_age,max_age,display_order) VALUES(?,?,?,?,?,?)');$s->execute([(int)$v['campusId'],$v['name'],$v['ageLabel'],$v['minAge']??null,$v['maxAge']??null,$v['displayOrder']??999]);$id=(int)$db->lastInsertId();api_audit($db,$actor,'CLASS_CREATED','Class',$id);api_ok(['id'=>$id],201); }
function api_list_children(PDO $db): never {
    $actor=api_actor($db);[$page,$limit,$offset]=api_page();$where=[];$params=[];$allowed=api_permitted_class_ids($db,$actor);
    if($allowed!==null){if(!$allowed)api_ok([],200,['page'=>$page,'limit'=>$limit,'total'=>0,'totalPages'=>1]);$where[]='c.class_id IN ('.implode(',',array_fill(0,count($allowed),'?')).')';$params=array_merge($params,$allowed);}
    if(($q=trim((string)($_GET['search']??'')))!==''){$where[]='(c.first_name LIKE ? OR c.last_name LIKE ?)';$params[]="%$q%";$params[]="%$q%";}
    foreach(['classId'=>'c.class_id','gender'=>'c.gender'] as $query=>$column)if(isset($_GET[$query])&&$_GET[$query]!==''){$where[]="$column=?";$params[]=$_GET[$query];}
    if(isset($_GET['active'])){$where[]='c.is_active=?';$params[]=filter_var($_GET['active'],FILTER_VALIDATE_BOOLEAN)?1:0;}
    if(isset($_GET['classAssignmentRequired'])){$where[]='c.class_assignment_required=?';$params[]=filter_var($_GET['classAssignmentRequired'],FILTER_VALIDATE_BOOLEAN)?1:0;}
    $filter=$where?' WHERE '.implode(' AND ',$where):'';$sort=['name'=>'c.first_name','firstName'=>'c.first_name','lastName'=>'c.last_name','dateOfBirth'=>'c.date_of_birth','classId'=>'c.class_id'][$_GET['sort']??'name']??'c.first_name';$order=strtolower((string)($_GET['order']??'asc'))==='desc'?'DESC':'ASC';
    $count=$db->prepare("SELECT COUNT(*) FROM children c$filter");$count->execute($params);$total=(int)$count->fetchColumn();$s=$db->prepare('SELECT '.api_child_select()." FROM children c LEFT JOIN classes cl ON cl.id=c.class_id$filter ORDER BY $sort $order,c.last_name LIMIT $limit OFFSET $offset");$s->execute($params);api_ok($s->fetchAll(),200,['page'=>$page,'limit'=>$limit,'total'=>$total,'totalPages'=>max(1,(int)ceil($total/$limit))]);
}
function api_child(PDO $db,int $id): never {
    $actor=api_actor($db,api_method()==='PATCH');$child=api_child_allowed($db,$actor,$id);if(api_method()==='GET'){ $care=$db->prepare('SELECT 1 FROM child_care_profiles WHERE child_id=?');$care->execute([$id]);$child['careInformationAvailable']=(bool)$care->fetchColumn();api_ok($child); }
    $v=api_input();$fields=['firstName'=>'first_name','lastName'=>'last_name','dateOfBirth'=>'date_of_birth','gender'=>'gender','schoolGrade'=>'school_grade','classId'=>'class_id','active'=>'is_active','classAssignmentRequired'=>'class_assignment_required'];$sets=[];$params=[];foreach($fields as $input=>$column)if(array_key_exists($input,$v)){$sets[]="$column=?";$params[]=$v[$input];}if(!$sets)api_error('VALIDATION_ERROR','No editable child fields were supplied.',422);$params[]=$id;$db->prepare('UPDATE children SET '.implode(',',$sets).' WHERE id=?')->execute($params);api_audit($db,$actor,'CHILD_UPDATED','Child',$id,array_keys($v));api_ok(['id'=>$id,'updated'=>true]);
}
function api_create_child(PDO $db): never { $actor=api_actor($db,true);$v=api_input();foreach(['familyId','firstName','lastName'] as $field)if(empty($v[$field]))api_error('VALIDATION_ERROR',"$field is required.",422);$classId=$v['classId']??null;$needs=$classId?0:1;$s=$db->prepare('INSERT INTO children(family_id,class_id,first_name,last_name,date_of_birth,gender,school_grade,is_active,class_assignment_required) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([(int)$v['familyId'],$classId,$v['firstName'],$v['lastName'],$v['dateOfBirth']??null,$v['gender']??'UNSPECIFIED',$v['schoolGrade']??null,1,$needs]);$id=(int)$db->lastInsertId();api_audit($db,$actor,'CHILD_CREATED','Child',$id);api_ok(['id'=>$id,'classAssignmentRequired'=>(bool)$needs],201); }
function api_guardians(PDO $db): never { api_actor($db,true);[$page,$limit,$offset]=api_page();$q=trim((string)($_GET['search']??''));$params=[];$filter='';if($q!==''){$filter=' WHERE first_name LIKE ? OR last_name LIKE ? OR phone LIKE ?';$params=["%$q%","%$q%","%$q%"];}$count=$db->prepare("SELECT COUNT(*) FROM guardians$filter");$count->execute($params);$total=(int)$count->fetchColumn();$s=$db->prepare("SELECT id,family_id AS familyId,first_name AS firstName,last_name AS lastName,phone AS primaryPhone,email,relationship,is_primary AS primaryGuardian,is_authorized AS authorisedPickup FROM guardians$filter ORDER BY first_name,last_name LIMIT $limit OFFSET $offset");$s->execute($params);api_ok($s->fetchAll(),200,['page'=>$page,'limit'=>$limit,'total'=>$total,'totalPages'=>max(1,(int)ceil($total/$limit))]); }
function api_guardian(PDO $db,int $id): never { $actor=api_actor($db,true);if(api_method()==='GET'){$s=$db->prepare('SELECT id,family_id AS familyId,first_name AS firstName,last_name AS lastName,phone AS primaryPhone,email,relationship,is_primary AS primaryGuardian,is_authorized AS authorisedPickup FROM guardians WHERE id=?');$s->execute([$id]);$row=$s->fetch();if(!$row)api_error('GUARDIAN_NOT_FOUND','Guardian not found.',404);api_ok($row);}$v=api_input();$fields=['firstName'=>'first_name','lastName'=>'last_name','primaryPhone'=>'phone','email'=>'email','relationship'=>'relationship','primary'=>'is_primary','authorisedPickup'=>'is_authorized'];$sets=[];$params=[];foreach($fields as $input=>$col)if(array_key_exists($input,$v)){$sets[]="$col=?";$params[]=$input==='primaryPhone'?api_phone($v[$input]):$v[$input];}if(!$sets)api_error('VALIDATION_ERROR','No editable guardian fields were supplied.',422);$params[]=$id;$db->prepare('UPDATE guardians SET '.implode(',',$sets).' WHERE id=?')->execute($params);api_audit($db,$actor,'GUARDIAN_UPDATED','Guardian',$id);api_ok(['id'=>$id,'updated'=>true]); }
function api_families_v1(PDO $db): never { $actor=api_actor($db,true);$q=trim((string)($_GET['search']??''));$params=[$actor['campus_id']];$filter=' WHERE f.campus_id=?';if($q!==''){$filter.=' AND (f.surname LIKE ? OR f.phone LIKE ? OR f.family_code LIKE ?)';$params=array_merge($params,["%$q%","%$q%","%$q%"]);} $s=$db->prepare("SELECT f.id,f.family_code AS familyCode,f.surname,f.phone,COUNT(c.id) AS children FROM families f LEFT JOIN children c ON c.family_id=f.id AND c.is_active=1$filter GROUP BY f.id,f.family_code,f.surname,f.phone ORDER BY f.surname LIMIT 100");$s->execute($params);api_ok($s->fetchAll()); }
function api_child_guardians(PDO $db,int $childId): never { $actor=api_actor($db);api_child_allowed($db,$actor,$childId);$s=$db->prepare('SELECT g.id,g.first_name AS firstName,g.last_name AS lastName,g.phone AS primaryPhone,g.email,cg.relationship,cg.is_primary AS primary,cg.authorised_pickup AS authorisedPickup FROM child_guardians cg JOIN guardians g ON g.id=cg.guardian_id WHERE cg.child_id=?');$s->execute([$childId]);api_ok($s->fetchAll()); }
function api_profile(PDO $db,int $childId,string $table): never { $actor=api_actor($db,true);api_child_allowed($db,$actor,$childId);if(api_method()==='GET'){$s=$db->prepare("SELECT * FROM $table WHERE child_id=?");$s->execute([$childId]);api_ok($s->fetch()?:null);}$v=api_input();$valid=array_column($db->query("SHOW COLUMNS FROM $table")->fetchAll(),'Field');$fields=array_values(array_filter(array_keys($v),fn($key)=>in_array($key,$valid,true)&&!in_array($key,['child_id','created_at','updated_at'],true)));if(!$fields)api_error('VALIDATION_ERROR','No recognised profile fields were supplied.',422);$cols=implode(',', $fields);$marks=implode(',',array_fill(0,count($fields),'?'));$sets=implode(',',array_map(fn($f)=>"$f=VALUES($f)",$fields));$s=$db->prepare("INSERT INTO $table(child_id,$cols) VALUES(?,$marks) ON DUPLICATE KEY UPDATE $sets");$s->execute(array_merge([$childId],array_map(fn($f)=>$v[$f],$fields)));api_audit($db,$actor,'CHILD_PROFILE_UPDATED','Child',$childId,['profile'=>$table]);api_ok(['childId'=>$childId,'updated'=>true]); }
function api_public_lookup(PDO $db): never { $v=api_input();$phone=api_phone($v['phone']??null);$sessionId=(int)($v['serviceSessionId']??0);if(!$phone||!$sessionId)api_error('VALIDATION_ERROR','A valid phone number and service session are required.',422);$s=$db->query('SELECT id,first_name,last_name,phone FROM guardians');$guardian=null;foreach($s->fetchAll() as $row)if(api_phone($row['phone'])===$phone){$guardian=$row;break;}if(!$guardian)api_ok(['guardianFirstName'=>null,'children'=>[]]);$children=$db->prepare("SELECT c.id,c.first_name AS firstName,CONCAT(LEFT(c.last_name,1),'.') AS lastInitial,cl.name AS className,a.checked_in_at AS checkedInAt,CASE WHEN a.status IN ('CHECKED_IN','PICKED_UP') THEN TRUE ELSE FALSE END AS alreadyCheckedIn FROM child_guardians cg JOIN children c ON c.id=cg.child_id LEFT JOIN classes cl ON cl.id=c.class_id LEFT JOIN attendance a ON a.child_id=c.id AND a.service_session_id=? WHERE cg.guardian_id=? ORDER BY c.first_name");$children->execute([$sessionId,$guardian['id']]);api_ok(['guardianFirstName'=>$guardian['first_name'],'children'=>$children->fetchAll()]); }
function api_sessions(PDO $db): never { $actor=api_actor($db);$where=['campus_id=?'];$params=[$actor['campus_id']];if(isset($_GET['date'])){$where[]='service_date=?';$params[]=$_GET['date'];}if(isset($_GET['service'])){$where[]='service_type=?';$params[]=$_GET['service'];}$s=$db->prepare('SELECT id,campus_id AS campusId,name,service_date AS serviceDate,service_type AS serviceType,starts_at AS startsAt,ends_at AS endsAt,is_open AS isOpen FROM service_sessions WHERE '.implode(' AND ',$where).' ORDER BY starts_at DESC');$s->execute($params);api_ok($s->fetchAll()); }
function api_session(PDO $db,int $id): never { $actor=api_actor($db,api_method()!=='GET');if(api_method()==='GET'){$s=$db->prepare('SELECT id,campus_id AS campusId,name,service_date AS serviceDate,service_type AS serviceType,starts_at AS startsAt,ends_at AS endsAt,is_open AS isOpen FROM service_sessions WHERE id=? AND campus_id=?');$s->execute([$id,$actor['campus_id']]);$row=$s->fetch();if(!$row)api_error('SERVICE_SESSION_NOT_FOUND','Service session not found.',404);api_ok($row);}$v=api_input();$fields=['name','startsAt'=>'starts_at','endsAt'=>'ends_at','serviceDate'=>'service_date','serviceType'=>'service_type','isOpen'=>'is_open'];$sets=[];$params=[];foreach($fields as $input=>$col)if(array_key_exists($input,$v)){$sets[]=is_int($input)?"$col=?":"$col=?";$params[]=$v[$input];}if(!$sets)api_error('VALIDATION_ERROR','No editable service-session fields were supplied.',422);$params[]=$id;$db->prepare('UPDATE service_sessions SET '.implode(',',$sets).' WHERE id=?')->execute($params);api_audit($db,$actor,'SERVICE_SESSION_UPDATED','ServiceSession',$id);api_ok(['id'=>$id,'updated'=>true]); }
function api_current_session(PDO $db): never { $actor=api_actor($db);$s=$db->prepare('SELECT id,campus_id AS campusId,name,service_date AS serviceDate,service_type AS serviceType,starts_at AS startsAt,ends_at AS endsAt,is_open AS isOpen FROM service_sessions WHERE campus_id=? AND is_open=1 ORDER BY starts_at DESC LIMIT 1');$s->execute([$actor['campus_id']]);api_ok($s->fetch()?:null); }
function api_roster(PDO $db): never { $actor=api_actor($db,true);$where=['1=1'];$params=[];foreach(['userId'=>'ra.user_id','dutyTypeId'=>'ra.duty_type_id','classId'=>'ra.class_id','serviceSessionId'=>'ra.service_session_id'] as $key=>$col)if(isset($_GET[$key])){$where[]="$col=?";$params[]=(int)$_GET[$key];}if(isset($_GET['month'])){$where[]='MONTH(ra.assignment_date)=?';$params[]=(int)$_GET['month'];}if(isset($_GET['year'])){$where[]='YEAR(ra.assignment_date)=?';$params[]=(int)$_GET['year'];}$s=$db->prepare('SELECT ra.id,ra.user_id AS userId,ra.assignment_date AS assignmentDate,ra.service_session_id AS serviceSessionId,ra.class_id AS classId,ra.status,ra.confirmed_at AS confirmedAt,dt.name AS dutyName,dt.code AS dutyCode,c.name AS className,u.name AS teacherName FROM roster_assignments ra JOIN staff_users u ON u.id=ra.user_id JOIN duty_types dt ON dt.id=ra.duty_type_id LEFT JOIN classes c ON c.id=ra.class_id WHERE '.implode(' AND ',$where).' ORDER BY ra.assignment_date,ra.id');$s->execute($params);api_ok($s->fetchAll()); }
function api_my_roster(PDO $db,string $scope): never { $actor=api_actor($db);$date=$scope==='today'?' AND ra.assignment_date=CURDATE()':($scope==='upcoming'?' AND ra.assignment_date>=CURDATE()':'');$s=$db->prepare("SELECT ra.id,ra.assignment_date AS assignmentDate,ra.service_session_id AS serviceSessionId,ra.status,ra.confirmed_at AS confirmedAt,dt.name AS dutyName,dt.code AS dutyCode,c.name AS className FROM roster_assignments ra JOIN duty_types dt ON dt.id=ra.duty_type_id LEFT JOIN classes c ON c.id=ra.class_id WHERE ra.user_id=?$date ORDER BY ra.assignment_date,ra.id");$s->execute([$actor['id']]);api_ok($s->fetchAll()); }
function api_confirm_presence(PDO $db,int $id): never { $actor=api_actor($db);$s=$db->prepare("UPDATE roster_assignments SET status='PRESENT',confirmed_at=NOW() WHERE id=? AND user_id=? AND status='ASSIGNED'");$s->execute([$id,$actor['id']]);if(!$s->rowCount())api_error('ASSIGNMENT_NOT_AVAILABLE','This assignment cannot be confirmed.',409);api_audit($db,$actor,'ROSTER_PRESENCE_CONFIRMED','RosterAssignment',$id);api_ok(['assignmentId'=>$id,'status'=>'PRESENT']); }
function api_dashboard(PDO $db): never {
    $actor=api_actor($db);$allowed=api_permitted_class_ids($db,$actor);$where=['c.campus_id=?','c.is_active=1'];$params=[$actor['campus_id']];
    if($allowed!==null){if(!$allowed) $where[]='1=0'; else {$where[]='c.id IN ('.implode(',',array_fill(0,count($allowed),'?')).')';$params=array_merge($params,$allowed);}}
    $session=$db->prepare('SELECT id,name,service_type AS serviceType,service_date AS serviceDate FROM service_sessions WHERE campus_id=? AND is_open=1 ORDER BY starts_at DESC LIMIT 1');$session->execute([$actor['campus_id']]);$activeSession=$session->fetch();$sessionId=(int)($activeSession['id']??0);
    $classes=$db->prepare('SELECT c.id,c.name,c.age_label AS ageLabel,COUNT(ch.id) AS total FROM classes c LEFT JOIN children ch ON ch.class_id=c.id AND ch.is_active=1 WHERE '.implode(' AND ',$where).' GROUP BY c.id,c.name,c.age_label ORDER BY c.display_order,c.name');$classes->execute($params);$rows=$classes->fetchAll();$checked=0;$picked=0;
    foreach($rows as &$row){$row['total']=(int)$row['total'];$row['checkedIn']=0;if($sessionId){$a=$db->prepare("SELECT status,COUNT(*) AS amount FROM attendance WHERE service_session_id=? AND class_id=? GROUP BY status");$a->execute([$sessionId,$row['id']]);foreach($a->fetchAll() as $state){$row['checkedIn']+=(int)$state['amount'];$checked+=(int)$state['amount'];if($state['status']==='PICKED_UP')$picked+=(int)$state['amount'];}}}unset($row);
    $personal=$db->prepare("SELECT ra.id,ra.assignment_date AS assignmentDate,dt.name AS dutyName,c.name AS className,ss.name AS serviceName FROM roster_assignments ra JOIN duty_types dt ON dt.id=ra.duty_type_id LEFT JOIN classes c ON c.id=ra.class_id LEFT JOIN service_sessions ss ON ss.id=ra.service_session_id WHERE ra.user_id=? AND ra.status NOT IN ('CANCELLED','REPLACED') AND ra.assignment_date>=CURDATE() ORDER BY ra.assignment_date,ra.id LIMIT 1");$personal->execute([$actor['id']]);$personalAssignment=$personal->fetch()?:null;
    $todayTeam=[];$upcoming=[];$needs=[];$relations=['total'=>0,'contacted'=>0,'pending'=>0];
    if($actor['access_level']==='TPK_SUPER_ADMIN'){
        $team=$db->prepare("SELECT COALESCE(ss.service_type,'UNSCHEDULED') AS serviceType,COUNT(*) AS assigned,SUM(ra.status='PRESENT') AS present,SUM(ra.status='ASSIGNED') AS notConfirmed FROM roster_assignments ra LEFT JOIN service_sessions ss ON ss.id=ra.service_session_id WHERE ra.assignment_date=COALESCE((SELECT service_date FROM service_sessions WHERE id=?),CURDATE()) AND ra.status NOT IN ('CANCELLED','REPLACED') GROUP BY COALESCE(ss.service_type,'UNSCHEDULED')");$team->execute([$sessionId?:null]);$todayTeam=$team->fetchAll();
        $up=$db->prepare("SELECT assignment_date AS assignmentDate,COALESCE(service_session_id,0) AS serviceSessionId,COUNT(*) AS duties,SUM(status NOT IN ('CANCELLED','REPLACED')) AS filled FROM roster_assignments WHERE assignment_date>=CURDATE() AND status NOT IN ('CANCELLED','REPLACED') GROUP BY assignment_date,service_session_id ORDER BY assignment_date LIMIT 2");$up->execute();$upcoming=$up->fetchAll();
        $need=$db->prepare("SELECT 'UNPICKED_UP' AS type,'URGENT' AS severity,CONCAT(COUNT(*),' children are still awaiting pickup') AS message,'Review Pick-Up' AS actionLabel,'/account/pick-up' AS actionDestination FROM attendance WHERE service_session_id=? AND status='CHECKED_IN' HAVING COUNT(*)>0");
        if($sessionId){try{$need->execute([$sessionId]);$needs=$need->fetchAll();}catch(Throwable $e){$needs=[];}}
        $task=$db->prepare("SELECT COUNT(*) AS total,SUM(status='RESOLVED') AS contacted,SUM(status IN ('OPEN','IN_PROGRESS')) AS pending FROM follow_up_tasks WHERE campus_id=?");try{$task->execute([$actor['campus_id']]);$relations=$task->fetch()?:$relations;}catch(Throwable $e){}
        $classNeed=$db->prepare("SELECT COUNT(*) FROM children c JOIN families f ON f.id=c.family_id WHERE f.campus_id=? AND c.class_assignment_required=1 AND c.is_active=1");$classNeed->execute([$actor['campus_id']]);$amount=(int)$classNeed->fetchColumn();if($amount)$needs[]=['type'=>'NEEDS_CLASS_ASSIGNMENT','severity'=>'HIGH','message'=>"{$amount} children need a class assignment",'actionLabel'=>'Assign Class','actionDestination'=>'/account/children'];
    }
    api_ok(['serviceSession'=>$activeSession?:null,'serviceSessionId'=>$sessionId?:null,'metrics'=>['checkedIn'=>$checked,'pickedUp'=>$picked,'stillPresent'=>$checked-$picked,'activeClasses'=>count($rows)],'classes'=>$rows,'personalAssignment'=>$personalAssignment,'todayTeam'=>$todayTeam,'needsAttention'=>$needs,'childrenRelations'=>$relations,'upcomingRoster'=>$upcoming]);
}
function api_checkins(PDO $db): never {
    $actor=api_actor($db);$allowed=api_permitted_class_ids($db,$actor);$sessionId=(int)($_GET['serviceSessionId']??0);
    if(!$sessionId){$current=$db->prepare('SELECT id FROM service_sessions WHERE campus_id=? AND is_open=1 ORDER BY starts_at DESC LIMIT 1');$current->execute([$actor['campus_id']]);$sessionId=(int)$current->fetchColumn();}
    if(!$sessionId)api_ok(['serviceSessionId'=>null,'items'=>[]]);$where=['a.service_session_id=?'];$params=[$sessionId];if($allowed!==null){if(!$allowed)api_ok(['serviceSessionId'=>$sessionId,'items'=>[]]);$where[]='a.class_id IN ('.implode(',',array_fill(0,count($allowed),'?')).')';$params=array_merge($params,$allowed);}
    if(($q=trim((string)($_GET['search']??'')))!==''){$where[]='(c.first_name LIKE ? OR c.last_name LIKE ? OR g.first_name LIKE ? OR g.last_name LIKE ?)';$params=array_merge($params,["%$q%","%$q%","%$q%","%$q%"]);}
    $sql="SELECT a.id,c.id AS childId,c.first_name AS firstName,c.last_name AS lastName,c.gender,cl.name AS className,a.status,a.checked_in_at AS checkedInAt,a.is_first_visit AS firstVisit,g.first_name AS guardianFirstName,g.last_name AS guardianLastName FROM attendance a JOIN children c ON c.id=a.child_id LEFT JOIN classes cl ON cl.id=a.class_id LEFT JOIN child_guardians cg ON cg.child_id=c.id AND cg.is_primary=1 LEFT JOIN guardians g ON g.id=cg.guardian_id WHERE ".implode(' AND ',$where).' ORDER BY a.checked_in_at DESC';$s=$db->prepare($sql);$s->execute($params);api_ok(['serviceSessionId'=>$sessionId,'items'=>$s->fetchAll()]);
}
function api_pickup_code_lookup(PDO $db): never {
    $actor=api_actor($db);$value=trim((string)($_GET['code']??''));if(str_starts_with($value,'TPK-PICKUP:'))$value=substr($value,11);if($value==='')api_error('VALIDATION_ERROR','Scan a pickup QR code or enter a pickup code.',422);
    $where=preg_match('/^[a-f0-9]{64}$/i',$value)?'pc.qr_token=?':'pc.display_code=?';$s=$db->prepare("SELECT pc.id,pc.display_code AS pickupCode,pc.collected_at AS collectedAt,f.surname,ss.name AS serviceName FROM service_pickup_codes pc JOIN families f ON f.id=pc.family_id JOIN service_sessions ss ON ss.id=pc.service_session_id WHERE ss.campus_id=? AND {$where} ORDER BY pc.id DESC LIMIT 1");$s->execute([$actor['campus_id'],$value]);$code=$s->fetch();if(!$code)api_error('PICKUP_CODE_NOT_FOUND','This pickup code is not available at this campus.',404);
    $children=$db->prepare("SELECT a.id AS attendanceId,c.first_name AS firstName,c.last_name AS lastName,cl.name AS className,a.status FROM attendance a JOIN children c ON c.id=a.child_id LEFT JOIN classes cl ON cl.id=a.class_id JOIN service_pickup_codes pc ON pc.service_session_id=a.service_session_id AND pc.family_id=c.family_id WHERE pc.id=? AND a.status='CHECKED_IN' ORDER BY c.first_name");$children->execute([$code['id']]);$code['children']=$children->fetchAll();api_ok($code);
}
function api_assisted_pickup_lookup(PDO $db): never {
    $actor=api_actor($db);$v=api_input();$first=trim((string)($v['firstName']??''));$last=trim((string)($v['lastName']??''));$birthDate=trim((string)($v['dateOfBirth']??''));
    if($first===''||$last===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$birthDate)) api_error('VALIDATION_ERROR','Enter the child’s first name, last name, and date of birth.',422);
    $s=$db->prepare("SELECT pc.id,pc.display_code AS pickupCode,pc.collected_at AS collectedAt,f.surname,ss.name AS serviceName FROM service_pickup_codes pc JOIN service_sessions ss ON ss.id=pc.service_session_id JOIN families f ON f.id=pc.family_id JOIN attendance a ON a.service_session_id=pc.service_session_id JOIN children c ON c.id=a.child_id AND c.family_id=pc.family_id WHERE ss.campus_id=? AND c.first_name=? AND c.last_name=? AND c.date_of_birth=? AND a.status='CHECKED_IN' ORDER BY ss.service_date DESC,pc.id DESC LIMIT 1");$s->execute([$actor['campus_id'],$first,$last,$birthDate]);$code=$s->fetch();
    if(!$code) api_error('ASSISTED_PICKUP_NOT_FOUND','We could not verify a checked-in child with those details.',404);
    $children=$db->prepare("SELECT a.id AS attendanceId,c.first_name AS firstName,c.last_name AS lastName,cl.name AS className,a.status FROM attendance a JOIN children c ON c.id=a.child_id LEFT JOIN classes cl ON cl.id=a.class_id JOIN service_pickup_codes pc ON pc.service_session_id=a.service_session_id AND pc.family_id=c.family_id WHERE pc.id=? AND a.status='CHECKED_IN' ORDER BY c.first_name");$children->execute([$code['id']]);$code['children']=$children->fetchAll();
    api_audit($db,$actor,'PICKUP_ASSISTED_BIRTH_DATE_VERIFIED','PickupCode',(int)$code['id'],['pickupCode'=>$code['pickupCode']]);api_ok($code);
}
function api_complete_pickup_code(PDO $db,int $id): never {
    $v=api_input();$verificationMethod=(string)($v['verificationMethod']??'PICKUP_CODE');if(!in_array($verificationMethod,['PICKUP_CODE','QR_CODE','ASSISTED_BIRTH_DATE'],true))api_error('VALIDATION_ERROR','Use an approved pickup verification method.',422);
    $actor=api_actor($db);$s=$db->prepare("SELECT pc.id,pc.service_session_id,pc.family_id,pc.display_code,pc.collected_at FROM service_pickup_codes pc JOIN service_sessions ss ON ss.id=pc.service_session_id WHERE pc.id=? AND ss.campus_id=? FOR UPDATE");$s->execute([$id,$actor['campus_id']]);$code=$s->fetch();if(!$code)api_error('PICKUP_CODE_NOT_FOUND','This pickup code is not available.',404);if($code['collected_at'])api_error('PICKUP_ALREADY_COMPLETED','This pickup code has already been used.',409);
    $db->beginTransaction();try{$update=$db->prepare("UPDATE attendance a JOIN children c ON c.id=a.child_id SET a.status='PICKED_UP',a.picked_up_at=NOW() WHERE a.service_session_id=? AND c.family_id=? AND a.status='CHECKED_IN'");$update->execute([$code['service_session_id'],$code['family_id']]);$db->prepare('UPDATE service_pickup_codes SET collected_at=NOW(),collected_by_staff_user_id=? WHERE id=? AND collected_at IS NULL')->execute([$actor['id'],$id]);api_audit($db,$actor,'PICKUP_COMPLETED','PickupCode',$id,['pickupCode'=>$code['display_code'],'verificationMethod'=>$verificationMethod,'childrenReleased'=>$update->rowCount()]);$db->commit();api_ok(['pickupCode'=>$code['display_code'],'childrenReleased'=>$update->rowCount(),'completed'=>true]);}catch(Throwable $e){$db->rollBack();throw $e;}
}
function api_set_access(PDO $db,int $id): never { $actor=api_actor($db,true);if($id===(int)$actor['id'])api_error('FORBIDDEN','A Super Admin cannot change their own access level.',403);$v=api_input();$next=$v['accessLevel']??'';if(!in_array($next,['TPK_SUPER_ADMIN','TPK_ADMIN'],true))api_error('VALIDATION_ERROR','Choose TPK_SUPER_ADMIN or TPK_ADMIN.',422);$s=$db->prepare('SELECT access_level FROM staff_users WHERE id=? AND campus_id=?');$s->execute([$id,$actor['campus_id']]);$previous=$s->fetchColumn();if($previous===false)api_error('STAFF_NOT_FOUND','Team member not found.',404);if($previous===$next)api_ok(['id'=>$id,'accessLevel'=>$next]);$db->beginTransaction();try{$db->prepare('UPDATE staff_users SET access_level=? WHERE id=?')->execute([$next,$id]);$db->prepare('INSERT INTO staff_access_audits(staff_user_id,previous_access_level,next_access_level,changed_by_staff_user_id) VALUES(?,?,?,?)')->execute([$id,$previous,$next,$actor['id']]);api_audit($db,$actor,'STAFF_ACCESS_UPDATED','StaffUser',$id,['from'=>$previous,'to'=>$next]);$db->commit();}catch(Throwable $e){$db->rollBack();throw $e;}api_ok(['id'=>$id,'accessLevel'=>$next]); }
function api_my_profile(PDO $db): never {
    $actor=api_actor($db);$s=$db->prepare('SELECT s.id AS staffUserId,s.email,s.access_level AS accessLevel,s.team_status AS teamStatus,s.joined_at AS joinedAt,c.name AS campus,p.title,p.first_name AS firstName,p.last_name AS lastName,p.birth_date AS birthDate,p.whatsapp_number AS whatsappNumber,p.mobile_number AS mobileNumber,p.profile_image_url AS profileImageUrl,p.whatsapp_verified_at AS whatsappVerifiedAt FROM staff_users s JOIN teacher_profiles p ON p.staff_user_id=s.id JOIN campuses c ON c.id=s.campus_id WHERE s.id=?');$s->execute([$actor['id']]);$profile=$s->fetch();if(!$profile)api_error('PROFILE_NOT_FOUND','Your staff profile is not available.',404);
    if(api_method()==='GET') api_ok($profile);
    $v=api_input();$allowed=['title'=>'title','firstName'=>'first_name','lastName'=>'last_name','birthDate'=>'birth_date','email'=>'email','mobileNumber'=>'mobile_number'];$profileSets=[];$userSets=[];$params=[];$userParams=[];
    foreach($allowed as $input=>$column)if(array_key_exists($input,$v)){if($input==='title'&&!in_array($v[$input],['Auntie','Uncle'],true))api_error('VALIDATION_ERROR','Choose Auntie or Uncle.',422);if($input==='email'&&!filter_var($v[$input],FILTER_VALIDATE_EMAIL))api_error('VALIDATION_ERROR','Enter a valid email address.',422);if($input==='mobileNumber'&&$v[$input]!==null&&$v[$input]!==''){ $number=tpk_normalize_nigerian_phone($v[$input]);if(!$number)api_error('VALIDATION_ERROR','Enter a valid Nigerian mobile number.',422);$profileSets[]='mobile_number=?';$params[]=$number;$profileSets[]='mobile_number_normalized=?';$params[]=$number;continue;}if($input==='email'){$userSets[]='email=?';$userParams[]=strtolower(trim($v[$input]));}else{$profileSets[]="$column=?";$params[]=$v[$input];}}
    if(!$profileSets&&!$userSets)api_error('VALIDATION_ERROR','No editable profile fields were supplied.',422);$db->beginTransaction();try{if($profileSets){$params[]=$actor['id'];$db->prepare('UPDATE teacher_profiles SET '.implode(',',$profileSets).' WHERE staff_user_id=?')->execute($params);}if($userSets){$userParams[]=$actor['id'];$db->prepare('UPDATE staff_users SET '.implode(',',$userSets).' WHERE id=?')->execute($userParams);}api_audit($db,$actor,'STAFF_PROFILE_UPDATED','StaffUser',(int)$actor['id'],array_keys($v));$db->commit();}catch(Throwable $e){$db->rollBack();throw $e;}api_ok(['updated'=>true]);
}
function api_profile_photo(PDO $db): never {
    $actor=api_actor($db);if(empty($_FILES['profilePhoto']))api_error('VALIDATION_ERROR','Choose a profile photo to upload.',422);try{$url=tpk_store_profile_photo($_FILES['profilePhoto'],(int)$actor['id']);}catch(Throwable $e){api_error('PROFILE_PHOTO_INVALID',$e->getMessage(),422);}$db->prepare('UPDATE teacher_profiles SET profile_image_url=? WHERE staff_user_id=?')->execute([$url,$actor['id']]);api_audit($db,$actor,'STAFF_PROFILE_PHOTO_UPDATED','StaffUser',(int)$actor['id']);api_ok(['profileImageUrl'=>$url]);
}
function api_remove_profile_photo(PDO $db): never { $actor=api_actor($db);$db->prepare('UPDATE teacher_profiles SET profile_image_url=NULL WHERE staff_user_id=?')->execute([$actor['id']]);api_audit($db,$actor,'STAFF_PROFILE_PHOTO_REMOVED','StaffUser',(int)$actor['id']);api_ok(['profileImageUrl'=>null]); }
function api_team(PDO $db): never {
    $actor=api_actor($db,true);$s=$db->prepare("SELECT s.id,s.name,s.email,s.access_level AS accessLevel,s.team_status AS teamStatus,s.account_status AS accountStatus,s.joined_at AS joinedAt,p.title,p.first_name AS firstName,p.last_name AS lastName,p.profile_image_url AS profileImageUrl,p.whatsapp_number AS whatsappNumber,GROUP_CONCAT(DISTINCT c.name ORDER BY c.name SEPARATOR ', ') AS assignedClasses FROM staff_users s LEFT JOIN teacher_profiles p ON p.staff_user_id=s.id LEFT JOIN staff_class_assignments sca ON sca.staff_user_id=s.id AND sca.is_active=1 LEFT JOIN classes c ON c.id=sca.class_id WHERE s.campus_id=? GROUP BY s.id,p.title,p.first_name,p.last_name,p.profile_image_url,p.whatsapp_number ORDER BY p.first_name,p.last_name");$s->execute([$actor['campus_id']]);api_ok($s->fetchAll());
}
function api_set_team_status(PDO $db,int $id): never {
    $actor=api_actor($db,true);if($id===(int)$actor['id'])api_error('FORBIDDEN','A Super Admin cannot change their own team status.',403);$v=api_input();$next=$v['teamStatus']??'';if(!in_array($next,['ACTIVE','PROBATION','INACTIVE'],true))api_error('VALIDATION_ERROR','Choose ACTIVE, PROBATION, or INACTIVE.',422);$s=$db->prepare('SELECT team_status FROM staff_users WHERE id=? AND campus_id=?');$s->execute([$id,$actor['campus_id']]);$previous=$s->fetchColumn();if($previous===false)api_error('STAFF_NOT_FOUND','Team member not found.',404);if($previous===$next)api_ok(['id'=>$id,'teamStatus'=>$next]);$db->beginTransaction();try{$db->prepare('UPDATE staff_users SET team_status=?,is_active=? WHERE id=?')->execute([$next,$next==='INACTIVE'?0:1,$id]);$db->prepare('INSERT INTO staff_team_status_audits(staff_user_id,previous_team_status,next_team_status,changed_by_staff_user_id) VALUES(?,?,?,?)')->execute([$id,$previous,$next,$actor['id']]);api_audit($db,$actor,'STAFF_TEAM_STATUS_UPDATED','StaffUser',$id,['from'=>$previous,'to'=>$next]);$db->commit();}catch(Throwable $e){$db->rollBack();throw $e;}api_ok(['id'=>$id,'teamStatus'=>$next]);
}

if(api_method()==='OPTIONS') api_ok(null,204);
try { $db=api_db();$path=api_path();$method=api_method();
    if($method==='GET'&&$path==='/api/v1/campuses')api_list_campuses($db);
    if(preg_match('#^/api/v1/campuses/(\d+)$#',$path,$m))api_campus($db,(int)$m[1]);
    if($method==='GET'&&$path==='/api/v1/classes')api_list_classes($db);
    if($method==='POST'&&$path==='/api/v1/classes')api_create_class($db);
    if(preg_match('#^/api/v1/classes/(\d+)$#',$path,$m))api_class($db,(int)$m[1]);
    if($method==='GET'&&preg_match('#^/api/v1/classes/(\d+)/children$#',$path,$m)){$_GET['classId']=$m[1];api_list_children($db);}
    if($method==='GET'&&$path==='/api/v1/children')api_list_children($db);
    if($method==='POST'&&$path==='/api/v1/children')api_create_child($db);
    if(preg_match('#^/api/v1/children/(\d+)$#',$path,$m))api_child($db,(int)$m[1]);
    if(preg_match('#^/api/v1/children/(\d+)/(care-profile|emergency-profile|ministry-profile)$#',$path,$m)){api_profile($db,(int)$m[1],['care-profile'=>'child_care_profiles','emergency-profile'=>'child_emergency_profiles','ministry-profile'=>'child_ministry_profiles'][$m[2]]);}
    if($method==='GET'&&preg_match('#^/api/v1/children/(\d+)/guardians$#',$path,$m))api_child_guardians($db,(int)$m[1]);
    if($method==='GET'&&$path==='/api/v1/guardians')api_guardians($db);
    if($method==='GET'&&$path==='/api/v1/families')api_families_v1($db);
    if(preg_match('#^/api/v1/guardians/(\d+)$#',$path,$m))api_guardian($db,(int)$m[1]);
    if($method==='POST'&&$path==='/api/v1/public/check-in/lookup')api_public_lookup($db);
    if($method==='GET'&&$path==='/api/v1/service-sessions/current')api_current_session($db);
    if($method==='GET'&&$path==='/api/v1/service-sessions')api_sessions($db);
    if(preg_match('#^/api/v1/service-sessions/(\d+)$#',$path,$m))api_session($db,(int)$m[1]);
    if($method==='GET'&&$path==='/api/v1/roster')api_roster($db);
    if($method==='GET'&&$path==='/api/v1/me/roster')api_my_roster($db,'all');
    if($path==='/api/v1/me/profile')api_my_profile($db);
    if($method==='POST'&&$path==='/api/v1/me/profile-photo')api_profile_photo($db);
    if($method==='DELETE'&&$path==='/api/v1/me/profile-photo')api_remove_profile_photo($db);
    if($method==='GET'&&$path==='/api/v1/me/assignments/today')api_my_roster($db,'today');
    if($method==='GET'&&$path==='/api/v1/me/assignments/upcoming')api_my_roster($db,'upcoming');
    if($method==='POST'&&preg_match('#^/api/v1/roster/assignments/(\d+)/confirm-presence$#',$path,$m))api_confirm_presence($db,(int)$m[1]);
    if($method==='GET'&&$path==='/api/v1/dashboard/overview')api_dashboard($db);
    if($method==='GET'&&$path==='/api/v1/check-ins')api_checkins($db);
    if($method==='GET'&&$path==='/api/v1/pickup-codes')api_pickup_code_lookup($db);
    if($method==='POST'&&$path==='/api/v1/pickup-codes/assisted-lookup')api_assisted_pickup_lookup($db);
    if($method==='POST'&&preg_match('#^/api/v1/pickup-codes/(\d+)/complete$#',$path,$m))api_complete_pickup_code($db,(int)$m[1]);
    if($method==='PATCH'&&preg_match('#^/api/v1/staff/(\d+)/access-level$#',$path,$m))api_set_access($db,(int)$m[1]);
    if($method==='GET'&&$path==='/api/v1/team')api_team($db);
    if($method==='PATCH'&&preg_match('#^/api/v1/staff/(\d+)/team-status$#',$path,$m))api_set_team_status($db,(int)$m[1]);
    api_error('ROUTE_NOT_FOUND','The requested API endpoint was not found.',404);
} catch(PDOException $e){error_log('[TPK API v1] '.$e->getMessage());api_error('DATA_UNAVAILABLE','The requested data is not available yet. Confirm that the v1 database migration has been applied.',503);
} catch(Throwable $e){error_log('[TPK API v1] '.$e->getMessage());api_error('SERVER_ERROR','Something went wrong while handling your request.',500);}
