"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { FiSearch, FiUserPlus } from "react-icons/fi";
import { apiBase, authHeaders, readTeacherSession } from "@/lib/session";

type Row = { id: number; firstName: string; lastName: string; className?: string; gender: string; status: string; checkedInAt: string; firstVisit: boolean; guardianFirstName?: string; guardianLastName?: string };
export default function AccountCheckInPage() {
  const session = readTeacherSession(); const [items, setItems] = useState<Row[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!session) return; const timer = window.setTimeout(() => { setLoading(true); fetch(`${apiBase}/api/v1/check-ins?search=${encodeURIComponent(query)}`, { headers: authHeaders(session) }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "We could not load check-ins."); setItems(result.data.items || []); }).catch((reason) => setError(reason instanceof Error ? reason.message : "We could not load check-ins.")).finally(() => setLoading(false)); }, 200); return () => window.clearTimeout(timer); }, [query]); // eslint-disable-line react-hooks/exhaustive-deps
  return <section className="staff-checkin"><header><div><p className="eyebrow">Petra Wuse</p><h1>Check-In</h1><p className="intro">Monitor live arrivals across the classes you can access.</p></div><Link href="/check-in/parent?assisted=1" className="solid-button"><FiUserPlus />Assist a Check-In</Link></header><section className="panel"><div className="checkin-toolbar"><label><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search child or guardian" /></label><span>{loading ? "Loading…" : `${items.length} live check-ins`}</span></div>{error ? <p className="error">{error}</p> : <div className="table-wrap"><table><thead><tr><th>Child</th><th>Class</th><th>Guardian</th><th>Visit</th><th>Check-In</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><b>{item.firstName} {item.lastName}</b></td><td>{item.className || "Class assignment required"}</td><td>{[item.guardianFirstName, item.guardianLastName].filter(Boolean).join(" ") || "—"}</td><td>{item.firstVisit ? "First Visit" : "Returning"}</td><td>{new Intl.DateTimeFormat("en-NG", { timeStyle: "short", timeZone: "Africa/Lagos" }).format(new Date(item.checkedInAt))}</td><td>{item.status.replaceAll("_", " ")}</td></tr>)}{!items.length && !loading && <tr><td colSpan={6} className="empty">No children have checked in for the current service.</td></tr>}</tbody></table></div>}</section><style jsx>{`.staff-checkin header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:22px}.staff-checkin h1{font-family:var(--font-display),Georgia,serif}.checkin-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:18px}.checkin-toolbar label{height:42px;min-width:min(440px,70%);display:flex;align-items:center;gap:8px;padding:0 12px;border:1px solid var(--line);border-radius:8px}.checkin-toolbar input{width:100%;border:0;background:transparent;outline:0;font:13px var(--font-body)}.checkin-toolbar span{font-size:11px;color:var(--muted)}.error{color:#c8452c}@media(max-width:590px){.staff-checkin header{display:grid;gap:13px}.checkin-toolbar{display:grid}.checkin-toolbar label{min-width:0;width:100%}}`}</style></section>;
}
