import { type NoteBlock } from "./curriculum-notes";
import { loadEventReportBranding,type PdfImage } from "./table-pdf";
import { authHeaders,apiBase } from "./session";
import { junglePalette,type EventPalette } from "./event-palette";
export type NoteReport={title:string;eventName:string;scope?:string;type:string;blocks:NoteBlock[];branding?:PdfImage[];pictures?:Record<number,PdfImage>;textPictures?:Record<string,PdfImage>;palette?:EventPalette};
const ascii=(s:string)=>s.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[–—]/g,"-").replace(/[•●]/g,"-").replace(/[^\x20-\x7e]/g," ");
const escape=(s:string)=>ascii(s).replace(/([\\()])/g,"\\$1");
const colour=(s:string)=>[1,3,5].map(i=>(parseInt(s.slice(i,i+2),16)/255).toFixed(3)).join(" ");
// Conservative Helvetica widths keep even long unbroken words inside the margins.
function lines(s:string,width:number,size:number){const graphemes=(value:string)=>Array.from(new Intl.Segmenter(undefined,{granularity:"grapheme"}).segment(value),part=>part.segment);const measure=(value:string)=>graphemes(value).reduce((n,c)=>n+size*(c===' '? .3:/\p{Extended_Pictographic}/u.test(c)?1.2:/[WM]/.test(c)?1:/[A-Z]/.test(c)?.8:/[mw]/.test(c)?.9:/[il.,:;!'|]/.test(c)?.3:.6),0),out:string[]=[];let line="";for(const word of s.split(/\s+/)){let rest=word;if(measure(line+(line?' ':'')+rest)>width&&line){out.push(line);line="";}while(measure(rest)>width){const parts=graphemes(rest);let count=1;while(count<parts.length&&measure(parts.slice(0,count+1).join(""))<=width)count++;out.push(parts.slice(0,count).join(""));rest=parts.slice(count).join("");}line+=(line?' ':'')+rest;}if(line)out.push(line);return out.filter(Boolean);}
const textImageKey=(s:string,size:number,bold:boolean)=>`${size}:${bold?1:0}:${s}`;
export function createNotePdf(report:NoteReport):Blob{
 const w=595,h=842,m=44,width=w-m*2,p=report.palette||junglePalette,pages:string[]=[],images:PdfImage[]=report.branding?.slice(0,2)||[],refs=new Map<number,number>(),textRefs=new Map<string,number>();
 for(const block of report.blocks)if(block.type==="image"&&block.fileId&&!refs.has(block.fileId)){const image=report.pictures?.[block.fileId];if(!image)throw Error("A note picture is unavailable. Try the download again.");refs.set(block.fileId,images.length);images.push(image);}
 for(const [key,image] of Object.entries(report.textPictures||{})){textRefs.set(key,images.length);images.push(image);}
 let commands:string[]=[],y=0;
 const text=(s:string,x:number,top:number,size=11,bold=false)=>{const imageIndex=textRefs.get(textImageKey(s,size,bold));if(imageIndex!==undefined){const image=images[imageIndex],iw=image.width/2,ih=image.height/2;commands.push(`q ${iw.toFixed(2)} 0 0 ${ih.toFixed(2)} ${x.toFixed(2)} ${(h-top-size*.38).toFixed(2)} cm /I${imageIndex} Do Q`);return;}commands.push(`BT /${bold?"F2":"F1"} ${size} Tf 1 0 0 1 ${x.toFixed(2)} ${(h-top).toFixed(2)} Tm (${escape(s)}) Tj ET`);};
 const paint=(image:PdfImage,index:number,x:number,top:number,maxW:number,maxH:number)=>{const scale=Math.min(maxW/image.width,maxH/image.height),iw=image.width*scale,ih=image.height*scale;commands.push(`q ${iw.toFixed(2)} 0 0 ${ih.toFixed(2)} ${x.toFixed(2)} ${(h-top-ih).toFixed(2)} cm /I${index} Do Q`);return ih;};
 const start=()=>{commands=[`${colour(p.secondary)} rg 0 ${h-10} ${w} 10 re f`,`${colour(p.primary)} rg`];(report.branding||[]).slice(0,2).forEach((image,i)=>paint(image,i,m+i*68,28,report.branding?.length===1?128:58,68));const x=report.branding?.length?m+145:m;lines(report.eventName,w-m-x,10).slice(0,2).forEach((line,i)=>text(line,x,44+i*14,10,true));text("TEACHER RESOURCE",x,79,8,true);y=128;if(!pages.length){for(const line of lines(report.title,width,23)){text(line,m,y,23,true);y+=29;}text(report.type.replaceAll("_"," "),m,y+5,9,true);y+=28;for(const line of lines(report.scope||"Whole event",width,10)){text(line,m,y,10);y+=15;}y+=15;}else{for(const line of lines(report.title,width,12).slice(0,3)){text(line,m,y,12,true);y+=16;}y+=10;}commands.push(`${colour(p.accent)} RG 2 w ${m} ${h-y+7} m ${w-m} ${h-y+7} l S`);y+=12;commands.push(`${colour(p.text)} rg`);};
 const finish=()=>{commands.push(`${colour(p.primary)} RG .5 w ${m} 40 m ${w-m} 40 l S`,`${colour(p.text)} rg`);text("TribePetra Kids | Curriculum",m,h-25,8);text(`Page ${pages.length+1}`,w-m-40,h-25,8);pages.push(commands.join("\n"));};
 const ensure=(space:number)=>{if(y+space>h-62){finish();start();}};
 start();
 report.blocks.forEach((block,bi)=>{if(block.type==="image"&&block.fileId){const index=refs.get(block.fileId)!;const image=images[index],height=Math.min(280,width*image.height/image.width);ensure(height+30);paint(image,index,m+(width-Math.min(width,height*image.width/image.height))/2,y,width,height);y+=height+14;if(block.caption)for(const line of lines(block.caption,width,9)){ensure(14);text(line,m,y,9);y+=14;}y+=12;return;}
  const heading=block.type==="heading",size=heading?15:11,step=heading?21:17;const items=heading?[block.text||""]:(block.text||"").split("\n");
  if(heading){const next=report.blocks[bi+1];const nextImage=next?.type==="image"&&next.fileId?images[refs.get(next.fileId)!]:null;const nextSpace=nextImage?Math.min(280,width*nextImage.height/nextImage.width)+40:next?42:0;ensure(lines(block.text||"",width,size).length*step+nextSpace+20);commands.push(`${colour(p.primary)} rg`);y+=8;}
  items.forEach(item=>{if(!item.trim()){ensure(step);y+=step;return;}const wrapped=lines(item,width-(block.type==="list"?16:0),size);if(!heading)ensure(wrapped.length<=12?wrapped.length*step+12:step*2);wrapped.forEach((line,i)=>{ensure(step);text(line,m+(block.type==="list"?16:0),y,size,heading);if(block.type==="list"&&i===0)text("-",m,y,size);y+=step;});if(block.type==="list")y+=5;});y+=heading?8:12;commands.push(`${colour(p.text)} rg`);
 });finish();
 const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>","","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"],imageRefs:string[]=[];
 images.forEach((image,i)=>{const encoded=image.hex+">",id=objects.length+1;objects.push(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter [/ASCIIHexDecode /DCTDecode] /Length ${encoded.length} >>\nstream\n${encoded}\nendstream`);imageRefs.push(`/I${i} ${id} 0 R`);});
 const ids:number[]=[];for(const content of pages){const id=objects.length+1;ids.push(id);objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${w} ${h}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> /XObject << ${imageRefs.join(" ")} >> >> /Contents ${id+1} 0 R >>`);objects.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);}
 objects[1]=`<< /Type /Pages /Kids [${ids.map(id=>`${id} 0 R`).join(" ")}] /Count ${ids.length} >>`;let pdf="%PDF-1.4\n";const offsets=[0];objects.forEach((object,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${object}\nendobj\n`;});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>`${String(n).padStart(10,"0")} 00000 n \n`).join("")}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return new Blob([pdf],{type:"application/pdf"});
}
export async function notePicture(eventId:number,fileId:number){const r=await fetch(`${apiBase}/api/v1/events/${eventId}/files/${fileId}`,{headers:authHeaders(),cache:"no-store"});if(!r.ok)throw Error("A note picture is unavailable for your assignment.");const blob=await r.blob();if(!["image/jpeg","image/png","image/webp"].includes(blob.type)||blob.size>25*1024*1024)throw Error("Unsupported note picture.");return blob;}
async function pdfPicture(blob:Blob):Promise<PdfImage>{const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();if(image.naturalWidth*image.naturalHeight>16000000)throw Error("This picture is too large.");const scale=Math.min(1,1400/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);const ctx=canvas.getContext("2d");if(!ctx)throw Error("Picture rendering unavailable.");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);const bytes=atob(canvas.toDataURL("image/jpeg",.92).split(",")[1]);return {width:canvas.width,height:canvas.height,hex:Array.from(bytes,c=>c.charCodeAt(0).toString(16).padStart(2,"0")).join("")};}finally{URL.revokeObjectURL(url);}}
function rasterText(s:string,size:number,bold:boolean,color:string,maxWidth:number):PdfImage{const canvas=document.createElement("canvas"),scale=2;const ctx=canvas.getContext("2d");if(!ctx)throw Error("Emoji rendering is unavailable in this browser.");ctx.font=`${bold?"700":"400"} ${size*scale}px Arial, Apple Color Emoji, Noto Color Emoji, sans-serif`;const measured=ctx.measureText(s).width;canvas.width=Math.max(1,Math.min(Math.ceil(maxWidth*scale),Math.ceil(measured+4)));canvas.height=Math.ceil(size*scale*1.5);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font=`${bold?"700":"400"} ${size*scale}px Arial, Apple Color Emoji, Noto Color Emoji, sans-serif`;ctx.textBaseline="alphabetic";ctx.fillStyle=color;if(measured>canvas.width-4)ctx.scale((canvas.width-4)/measured,1);ctx.fillText(s,2,size*scale*1.12);const bytes=atob(canvas.toDataURL("image/jpeg",.96).split(",")[1]);return {width:canvas.width,height:canvas.height,hex:Array.from(bytes,c=>c.charCodeAt(0).toString(16).padStart(2,"0")).join("")};}
function emojiTextPictures(report:NoteReport,palette:EventPalette):Record<string,PdfImage>{const pictures:Record<string,PdfImage>={},width=595-88;const add=(value:string,maxWidth:number,size:number,bold:boolean,color:string)=>{for(const line of lines(value,maxWidth,size)){if(!/\p{Extended_Pictographic}/u.test(line))continue;const key=textImageKey(line,size,bold);pictures[key]??=rasterText(line,size,bold,color,maxWidth);}};add(report.eventName,width,10,true,palette.primary);add(report.title,width,23,true,palette.primary);add(report.title,width,12,true,palette.primary);add(report.scope||"Whole event",width,10,false,palette.primary);for(const block of report.blocks){if(block.type==="image"){if(block.caption)add(block.caption,width,9,false,palette.text);continue;}const heading=block.type==="heading",size=heading?15:11;for(const item of (heading?[block.text||""]:(block.text||"").split("\n")))add(item,width-(block.type==="list"?16:0),size,heading,heading?palette.primary:palette.text);}return pictures;}
export async function downloadNotePdf(eventId:number,eventType:string,report:NoteReport){const branding=await loadEventReportBranding(eventType),pictures:Record<number,PdfImage>={};for(const id of [...new Set(report.blocks.filter(b=>b.type==="image"&&b.fileId).map(b=>b.fileId!))])pictures[id]=await pdfPicture(await notePicture(eventId,id));const palette=report.palette||(eventType==="VBS"?junglePalette:{primary:"#203451",secondary:"#203451",accent:"#e95532",surface:"#fffdf9",text:"#203451",onPrimary:"#ffffff",onAccent:"#ffffff"});const blob=createNotePdf({...report,palette,branding,pictures,textPictures:emojiTextPictures(report,palette)}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${report.title.replace(/[^a-z0-9 -]/gi,"").trim()||"Curriculum note"}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
