<?php
declare(strict_types=1);

/* Safe importer for "Tribe Petra Kids General Info Form (Responses) - Form Responses.csv".
 * Usage: php backend/scripts/import_general_info.php "/path/to/Form Responses.csv" [--dry-run]
 * It imports only unambiguous core data and stores every exception in import_issues.
 */
require_once dirname(__DIR__) . '/config.php';

function import_key(string $value): string { return strtolower(trim(preg_replace('/[^a-z0-9]+/i',' ',$value))); }
function import_phone(?string $value): ?string { $digits=preg_replace('/\D+/','',(string)$value); if(!$digits)return null; if(str_starts_with($digits,'234')&&strlen($digits)===13)$digits='0'.substr($digits,3); return strlen($digits)===11&&str_starts_with($digits,'0')?$digits:null; }
function import_date(?string $value): ?string { $value=trim((string)$value); if(!$value)return null; foreach(['d/m/Y','m/d/Y','Y-m-d','d-m-Y','m-d-Y'] as $format){$date=DateTimeImmutable::createFromFormat('!'.$format,$value);if($date&&$date->format($format)===$value)return $date->format('Y-m-d');}$timestamp=strtotime($value);return $timestamp?date('Y-m-d',$timestamp):null; }
function import_bool(?string $value): ?int { $value=strtolower(trim((string)$value));if($value==='')return null;if(in_array($value,['yes','true','1'],true))return 1;if(in_array($value,['no','false','0'],true))return 0;return null; }
function import_name(string $value, bool $surnameFirst=false): array { $parts=preg_split('/\s+/',trim($value));if(count($parts)===1)return[$parts[0],''];if($surnameFirst)return[implode(' ',array_slice($parts,1)),$parts[0]];return[$parts[0],implode(' ',array_slice($parts,1))]; }
function import_value(array $row,array $heads,array $need): ?string { foreach($heads as $i=>$head)foreach($need as $needle)if($head===$needle||str_contains($head,$needle))return trim((string)($row[$i]??''))?:null;return null; }
function import_issue(PDO $db,int $run,int $row,string $code,string $message,?string $raw=null):void{$s=$db->prepare('INSERT INTO import_issues(import_run_id,source_row,issue_code,message,raw_value) VALUES(?,?,?,?,?)');$s->execute([$run,$row,$code,$message,$raw]);}

$source=$argv[1]??'';$dry=in_array('--dry-run',$argv,true);if(!$source||!is_readable($source)){fwrite(STDERR,"Usage: php backend/scripts/import_general_info.php <responses.csv> [--dry-run]\n");exit(1);}
$handle=fopen($source,'rb');$header=fgetcsv($handle);if(!$header)throw new RuntimeException('CSV needs a header row.');$heads=array_map('import_key',$header);$db=db();
$campus=(int)$db->query("SELECT id FROM campuses WHERE code='PETRA-WUSE' LIMIT 1")->fetchColumn();if(!$campus)throw new RuntimeException('Run seed.sql before importing.');
$run=$db->prepare('INSERT INTO import_runs(source_name,source_hash) VALUES(?,?)');$run->execute([basename($source),hash_file('sha256',$source)]);$runId=(int)$db->lastInsertId();
$classRows=$db->query('SELECT id,name FROM classes WHERE is_active=1')->fetchAll();$classes=[];foreach($classRows as $class)$classes[import_key($class['name'])]=(int)$class['id'];
$seen=0;$imported=0;$rowNumber=1;
while(($row=fgetcsv($handle))!==false){$rowNumber++;if(!array_filter($row,fn($v)=>trim((string)$v)!==''))continue;$seen++;
    $childFull=import_value($row,$heads,['child s surname and firstname']);if(!$childFull){import_issue($db,$runId,$rowNumber,'MISSING_CHILD_NAME','Skipped: child name is missing.');continue;}[$first,$last]=import_name($childFull,true);
    $dobRaw=import_value($row,$heads,['child s date of birth']);$dob=import_date($dobRaw);if(!$dob){import_issue($db,$runId,$rowNumber,'MISSING_OR_INVALID_DOB','Skipped: date of birth is missing or invalid.',$dobRaw);continue;}
    $genderRaw=import_value($row,$heads,['child s gender']);$gender=in_array(strtoupper((string)$genderRaw),['MALE','FEMALE'],true)?strtoupper($genderRaw):'UNSPECIFIED';if($genderRaw&&$gender==='UNSPECIFIED')import_issue($db,$runId,$rowNumber,'UNMAPPED_GENDER','Gender was not recognised.',$genderRaw);
    $tribe=import_value($row,$heads,['tribe']);$classId=$tribe?($classes[import_key($tribe)]??null):null;$classReview=$classId?0:1;if($tribe&&!$classId)import_issue($db,$runId,$rowNumber,'UNKNOWN_CLASS','Historical tribe was not mapped to an active current class.',$tribe);if(!$tribe)import_issue($db,$runId,$rowNumber,'CLASS_ASSIGNMENT_REQUIRED','No historical tribe was supplied.');
    $guardianFull=import_value($row,$heads,['parent guardian name']);if(!$guardianFull){import_issue($db,$runId,$rowNumber,'MISSING_GUARDIAN_NAME','Skipped: parent or guardian name is missing.');continue;}[$guardianFirst,$guardianLast]=import_name($guardianFull);
    $phoneRaw=import_value($row,$heads,['parents guardian s mobile number']);$phone=import_phone($phoneRaw);if(!$phone){import_issue($db,$runId,$rowNumber,'MALFORMED_PHONE','Skipped: primary guardian phone could not be normalised.',$phoneRaw);continue;}
    $phone2=import_phone(import_value($row,$heads,['parents guardian s mobile number 2']));$email=import_value($row,$heads,['email address']);$address=import_value($row,$heads,['address']);$grade=import_value($row,$heads,['child s school grade']);
    $neuro=import_value($row,$heads,['neurodevelopmental disorders']);$needs=import_value($row,$heads,['explain the nature of your child']);$severity=import_value($row,$heads,['degree of severity']);$equipment=import_value($row,$heads,['special equipment']);$plan=import_value($row,$heads,['medical plan for emergency']);$emergency=import_value($row,$heads,['person to contact in emergency']);$emergencyPhone=import_phone(import_value($row,$heads,['phone number for emergency']));$feed=import_bool(import_value($row,$heads,['permission to feed']));$feeding=import_value($row,$heads,['special requirements when feeding']);$restroom=import_value($row,$heads,['signs and gestures']);$communication=import_value($row,$heads,['other behavior to communicate']);$behaviours=import_value($row,$heads,['behaviors we should be aware']);$management=import_value($row,$heads,['manage this behavior']);$triggers=import_value($row,$heads,['triggers to disruptive']);$allergies=import_value($row,$heads,['allergies medical conditions']);$colour=import_value($row,$heads,['favorite color']);$hobbies=import_value($row,$heads,['favorite hobbies']);$treat=import_value($row,$heads,['favorite treat']);$prayer=import_value($row,$heads,['prayer request']);
    try{$db->beginTransaction();$families=$db->query('SELECT id,phone FROM families WHERE campus_id='.(int)$campus)->fetchAll();$familyId=null;foreach($families as $family)if(import_phone($family['phone'])===$phone){$familyId=(int)$family['id'];break;}if(!$familyId){$code='IMP-'.strtoupper(substr(hash('sha256',$childFull.$phone.$rowNumber),0,10));$s=$db->prepare('INSERT INTO families(campus_id,family_code,surname,phone,email,notes) VALUES(?,?,?,?,?,?)');$s->execute([$campus,$code,$guardianLast?:$last,$phone,$email,$address]);$familyId=(int)$db->lastInsertId();}
        $guardianId=null;$gs=$db->prepare('SELECT id,phone FROM guardians WHERE family_id=?');$gs->execute([$familyId]);foreach($gs->fetchAll() as $candidate)if(import_phone($candidate['phone'])===$phone){$guardianId=(int)$candidate['id'];break;}if(!$guardianId){$s=$db->prepare('INSERT INTO guardians(family_id,first_name,last_name,phone,email,relationship,is_primary,is_authorized) VALUES(?,?,?,?,?,\'Parent/Guardian\',1,1)');$s->execute([$familyId,$guardianFirst,$guardianLast,$phone,$email]);$guardianId=(int)$db->lastInsertId();}
        $exists=$db->prepare('SELECT id FROM children WHERE family_id=? AND first_name=? AND last_name=? AND date_of_birth=? LIMIT 1');$exists->execute([$familyId,$first,$last,$dob]);if($exists->fetchColumn()){import_issue($db,$runId,$rowNumber,'POSSIBLE_DUPLICATE_CHILD','Skipped: matching child already exists.');$db->commit();continue;}
        $s=$db->prepare('INSERT INTO children(family_id,class_id,first_name,last_name,date_of_birth,gender,school_grade,is_first_visit,class_assignment_required,source_system,source_record_key) VALUES(?,?,?,?,?,?,?,FALSE,?,?,?)');$s->execute([$familyId,$classId,$first,$last,$dob,$gender,$grade,$classReview,'general-info-csv',$runId.':'.$rowNumber]);$childId=(int)$db->lastInsertId();
        $db->prepare('INSERT INTO child_guardians(child_id,guardian_id,relationship,is_primary,authorised_pickup) VALUES(?,?,\'Parent/Guardian\',1,1)')->execute([$childId,$guardianId]);
        $db->prepare('INSERT INTO child_care_profiles(child_id,allergies_or_medical_conditions,neurodevelopmental_conditions,additional_needs_description,severity,special_equipment,feeding_permission,feeding_requirements,restroom_communication,other_communication_methods,behaviours_to_know,behaviour_management,behaviour_triggers) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$childId,$allergies,$neuro,$needs,$severity,$equipment,$feed,$feeding,$restroom,$communication,$behaviours,$management,$triggers]);
        $db->prepare('INSERT INTO child_emergency_profiles(child_id,emergency_contact_name,emergency_contact_phone,medical_emergency_plan) VALUES(?,?,?,?)')->execute([$childId,$emergency,$emergencyPhone,$plan]);
        $db->prepare('INSERT INTO child_ministry_profiles(child_id,favourite_colour,hobbies_and_interests,favourite_snack_or_drink,prayer_request) VALUES(?,?,?,?,?)')->execute([$childId,$colour,$hobbies,$treat,$prayer]);
        if($dry)$db->rollBack();else$db->commit();$imported++;
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();import_issue($db,$runId,$rowNumber,'ROW_IMPORT_FAILED','Row could not be imported; review source values.');}
}
fclose($handle);$db->prepare('UPDATE import_runs SET records_seen=?,records_imported=? WHERE id=?')->execute([$seen,$imported,$runId]);echo json_encode(['runId'=>$runId,'dryRun'=>$dry,'recordsSeen'=>$seen,'recordsImported'=>$imported],JSON_PRETTY_PRINT).PHP_EOL;
