"use client";

import { FormEvent, useState } from "react";
import { FiCamera, FiCheckCircle, FiSearch } from "react-icons/fi";
import { apiBase, authHeaders, readTeacherSession } from "@/lib/session";

type Pickup = { id: number; pickupCode: string; surname: string; serviceName: string; collectedAt?: string | null; children: { attendanceId: number; firstName: string; lastName: string; className?: string; status: string }[] };
export default function AccountPickupPage() {
  const session=readTeacherSession();const [code,setCode]=useState("");const [pickup,setPickup]=useState<Pickup|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  async function lookup(event:FormEvent){event.preventDefault();if(!session)return;setBusy(true);setMessage("");setPickup(null);try{const response=await fetch(`${apiBase}/api/v1/pickup-codes?code=${encodeURIComponent(code.trim())}`,{headers:authHeaders(session)});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||"We could not find that pickup code.");setPickup(result.data);}catch(reason){setMessage(reason instanceof Error?reason.message:"We could not find that pickup code.");}finally{setBusy(false);}}
  async function complete(){if(!session||!pickup)return;setBusy(true);const response=await fetch(`${apiBase}/api/v1/pickup-codes/${pickup.id}/complete`,{method:"POST",headers:authHeaders(session)});const result=await response.json();setBusy(false);if(!response.ok){setMessage(result.error?.message||"We could not complete pickup.");return;}setPickup({...pickup,collectedAt:new Date().toISOString(),children:[]});setMessage(`${result.data.childrenReleased} child${result.data.childrenReleased===1?"":"ren"} safely checked out.`);}
  return <section className="pickup-page"><header><p className="eyebrow">Sunday</p><h1>Pick-Up</h1><p className="intro">Scan the QR with a connected scanner or enter the family pickup code.</p></header><section className="panel pickup-panel"><form onSubmit={lookup}><label><FiCamera/><input autoFocus value={code} onChange={event=>setCode(event.target.value)} placeholder="Scan QR or enter TPK-A-001"/><FiSearch/></label><button className="solid-button" disabled={busy}>{busy?"Checking…":"Find Pickup"}</button></form>{message&&<p className="pickup-message">{message}</p>}{pickup&&<section className="pickup-result"><div><p className="eyebrow">{pickup.pickupCode}</p><h2>{pickup.surname} Family</h2><p>{pickup.serviceName}</p></div>{pickup.collectedAt?<p className="completed"><FiCheckCircle/>Pickup complete</p>:<><div className="pickup-children">{pickup.children.map(child=><span key={child.attendanceId}><b>{child.firstName} {child.lastName}</b><small>{child.className}</small></span>)}</div><button className="solid-button" disabled={busy||!pickup.children.length} onClick={complete}>Complete Pickup</button></>}</section>}</section><style jsx>{`.pickup-page h1,.pickup-page h2{font-family:var(--font-display),Georgia,serif}.pickup-page header{margin-bottom:22px}.pickup-panel{max-width:760px}.pickup-panel form{display:flex;gap:10px}.pickup-panel label{height:46px;display:flex;align-items:center;gap:10px;flex:1;padding:0 12px;border:1px solid var(--line);border-radius:8px}.pickup-panel input{width:100%;border:0;outline:0;background:transparent;font:14px var(--font-body)}.pickup-message{font-size:12px;color:#a63c27}.pickup-result{margin-top:20px;padding-top:20px;border-top:1px solid var(--line)}.pickup-result h2{margin:5px 0}.pickup-result p:not(.eyebrow){color:var(--muted);font-size:12px}.pickup-children{display:grid;gap:8px;margin:16px 0}.pickup-children span{display:flex;justify-content:space-between;padding:10px;border:1px solid var(--line);border-radius:7px;font-size:12px}.pickup-children small{color:var(--muted)}.completed{display:flex;gap:8px;align-items:center;color:var(--green)!important;font-weight:800}@media(max-width:590px){.pickup-panel form{display:grid}.pickup-panel form button{width:100%}}`}</style></section>;
}
