"use client";

import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { FiDownload, FiPrinter } from "react-icons/fi";
import Link from "next/link";
import { apiBase } from "@/lib/session";

type Ticket = { pickupCode: string; qrData: string; serviceName: string; serviceDate: string; surname: string; children: { firstName: string; lastInitial: string; className?: string }[]; collectedAt?: string | null };
export default function PickupTicketPage() {
  const token=useSearchParams().get("token");const [ticket,setTicket]=useState<Ticket|null>(null);const [error,setError]=useState("");
  useEffect(()=>{if(!token){setError("This pickup ticket is incomplete.");return;}fetch(`${apiBase}/api/v1/public/pickup-tickets/${encodeURIComponent(token)}`).then(async(response)=>{const text=await response.text();let result: {success?:boolean;data?:Ticket;error?:{message?:string}}={};try{result=JSON.parse(text);}catch{}if(!response.ok||!result.success)throw new Error(result.error?.message||"We could not load this pickup ticket.");setTicket(result.data||null);}).catch(reason=>setError(reason instanceof Error?reason.message:"We could not load this pickup ticket."));},[token]);
  if(error)return <main className="ticket-page"><section className="ticket ticket-error"><p className="eyebrow">TribePetra Kids · Petra Wuse</p><h1>Pickup ticket unavailable</h1><p>{error}</p><p>Please return to the check-in desk. The team can still verify the family using the pickup code or the child’s date of birth.</p><Link className="solid-button" href="/check-in/parent">Return to check-in</Link></section><style jsx>{`.ticket-page{min-height:100vh;display:grid;place-items:center;padding:28px;background:var(--cream)}.ticket{width:min(100%,520px);padding:34px;background:var(--paper);border:1px solid var(--line);border-radius:14px;text-align:center}.ticket h1{font-family:var(--font-display),Georgia,serif;font-size:38px;margin:8px 0}.ticket>p{color:var(--muted);font-size:13px;line-height:1.55}.ticket-error .solid-button{display:inline-flex;margin-top:12px}`}</style></main>;if(!ticket)return <main className="ticket-page"><p>Loading pickup ticket…</p></main>;
  const qr=`https://api.qrserver.com/v1/create-qr-code/?size=260x260&format=svg&data=${encodeURIComponent(ticket.qrData)}`;
  return <main className="ticket-page"><section className="ticket"><p className="eyebrow">TribePetra Kids · Petra Wuse</p><h1>Pickup Ticket</h1><p>{new Intl.DateTimeFormat("en-NG",{dateStyle:"full"}).format(new Date(ticket.serviceDate))} · {ticket.serviceName}</p><div className="ticket-code"><small>PICKUP CODE</small><b>{ticket.pickupCode}</b></div><img className="ticket-qr" src={qr} alt="QR code for this pickup ticket"/><p className="scan-note">Show this QR code or pickup code to a TPK teacher after service.</p><div className="ticket-children"><b>Children</b>{ticket.children.map(child=><span key={`${child.firstName}-${child.lastInitial}`}>{child.firstName} {child.lastInitial} <small>{child.className}</small></span>)}</div>{ticket.collectedAt?<p className="collected">This ticket has already been used for pickup.</p>:null}<button className="solid-button no-print" onClick={()=>window.print()}><FiPrinter/>Print / Save as PDF</button><p className="no-print ticket-help"><FiDownload/>Choose “Save as PDF” in your phone or browser print dialog.</p></section><style jsx>{`.ticket-page{min-height:100vh;display:grid;place-items:center;padding:28px;background:var(--cream)}.ticket{width:min(100%,520px);padding:34px;background:var(--paper);border:1px solid var(--line);border-radius:14px;text-align:center}.ticket h1{font-family:var(--font-display),Georgia,serif;font-size:38px;margin:8px 0}.ticket>p{color:var(--muted);font-size:13px}.ticket-code{margin:25px auto 18px;padding:16px;border:1px dashed var(--orange);border-radius:10px;background:#fff7f2}.ticket-code small,.ticket-code b{display:block}.ticket-code small{color:var(--orange);font-weight:900;font-size:10px;letter-spacing:.12em}.ticket-code b{font:700 37px var(--font-display),Georgia,serif;margin-top:4px}.ticket-qr{width:260px;height:260px;max-width:100%}.scan-note{max-width:300px;margin:8px auto 20px;line-height:1.5}.ticket-children{display:grid;gap:7px;text-align:left;padding:16px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);font-size:12px}.ticket-children span{display:flex;justify-content:space-between}.ticket-children small{color:var(--muted)}.collected{color:#a33d28!important;font-weight:800}.ticket-help{display:flex;justify-content:center;align-items:center;gap:6px;font-size:11px!important}@media print{.ticket-page{padding:0;background:#fff}.ticket{border:0;box-shadow:none}.no-print{display:none!important}}`}</style></main>;
}
