"use client";
import { useState } from "react";
type Family = { id:string; familyCode:string; surname:string; guardians:{firstName:string;lastName:string}[]; children:{id:string;firstName:string;lastName:string;class:{name:string}}[] };
export function CheckInDesk() {
  const [term,setTerm]=useState(""); const [families,setFamilies]=useState<Family[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function search(e:React.FormEvent){e.preventDefault();setMessage("");const r=await fetch(`/api/families?q=${encodeURIComponent(term)}`);setFamilies(await r.json());}
  async function checkIn(childId:string){setBusy(true);const r=await fetch("/api/attendance/check-in",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({childId})});const data=await r.json();setBusy(false);setMessage(r.ok?`${data.childName} is checked in to ${data.className}.`:data.error);}
  return <div className="card form-card"><div className="notice">Scan a Family Pass / QR with your connected scanner, or enter its opaque token, Family ID, surname, or phone number. QR codes never contain children’s or guardians’ personal details.</div><form className="search-row" onSubmit={search}><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Scan or search family" autoFocus/><button className="btn orange">Find family</button></form>{message&&<div className="notice">{message}</div>}{families.map(f=><div className="result-card" key={f.id}><div><h3>{f.surname} family</h3><p>{f.familyCode} · {f.guardians.map(g=>`${g.firstName} ${g.lastName}`).join(", ")}</p><p>{f.children.map(c=>`${c.firstName} ${c.lastName} — ${c.class.name}`).join(" · ")}</p></div><div className="quick-actions">{f.children.map(c=><button key={c.id} className="btn yellow" disabled={busy} onClick={()=>checkIn(c.id)}>Check in {c.firstName}</button>)}</div></div>)}{term&&!families.length&&<div className="empty">No matching family. Try searching by phone or Family ID.</div>}</div>;
}
