"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { apiBase,authHeaders,clearTeacherSession,readTeacherSession } from "@/lib/session";
import { EventCurriculum, eventRequest, type HistoryData } from "./event-history-panels";
import { EventChildRegister,type EventChild } from "./event-child-register";
import { AppearancePreference } from "./dashboard-appearance";
import { eventDate,type MinistryEvent,type EventSession } from "@/lib/events";
import "./events-workspace.css";
type Detail=HistoryData&{children:EventChild[];event:MinistryEvent;sessions:EventSession[];groups:{id:number;name:string}[];volunteerAssignments:{id:number;responsibility:string;sessionId?:number;groupId?:number;groupName?:string;sessionName?:string}[]};
export function VolunteerNavigation(){return <header><Link href="/account/event-volunteer">TribePetra Kids · Event volunteer</Link><button className="outline-button" onClick={async()=>{await fetch(`${apiBase}/api/teachers/logout`,{method:"POST",headers:authHeaders()}).catch(()=>{});clearTeacherSession();window.location.assign("/teacher/login");}}>Sign out</button></header>;}
export function EventVolunteerDashboard(){const[events,setEvents]=useState<MinistryEvent[]>([]);const[data,setData]=useState<Detail|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{fetch(`${apiBase}/api/v1/events`,{headers:authHeaders(),cache:"no-store"}).then(r=>r.json()).then(b=>{if(!b.success)throw Error(b.error?.message||"Events unavailable.");setEvents(b.data.items);}).catch(e=>setError(e.message));},[]);
 async function open(id:number){setBusy(true);setError("");try{const r=await fetch(`${apiBase}/api/v1/events/${id}`,{headers:authHeaders(),cache:"no-store"});const b=await r.json();if(!r.ok)throw Error(b.error?.message||"Assignment unavailable.");setData(b.data);}catch(e){setError(e instanceof Error?e.message:"Event unavailable.");}finally{setBusy(false);}}
 const assigned=data?.sessions.filter(s=>data.volunteerAssignments.some(a=>!a.sessionId||Number(a.sessionId)===Number(s.id)))||[];
 const groups=data?.groups.filter(g=>data.volunteerAssignments.some(a=>!a.groupId||Number(a.groupId)===Number(g.id)))||[];
 return <div><h1>Hello, {readTeacherSession()?.firstName||"volunteer"}</h1><p>Your assigned event, teaching group, schedule and resources. Sunday administration is not part of this account.</p>{error&&<p role="alert" className="event-error">{error}</p>}{message&&<p role="status" className="event-success">{message}</p>}<div className="event-card-grid">{events.map(e=><article className="event-card" key={e.id}><h2>{e.name}</h2><p>{eventDate(e.startDate)} — {eventDate(e.endDate)}</p><b>{e.lifecycle}</b><button className="outline-button" disabled={busy} onClick={()=>void open(Number(e.id))}>Open my assignments</button></article>)}</div>{!events.length&&!error&&<p>Your event will appear once an administrator activates your assignment.</p>}{data&&<><section className="event-panel"><h2>{data.event.name}</h2><p>{data.event.themeName}</p><div className="event-session-grid">{data.volunteerAssignments.map(a=><article key={a.id}><h3>{a.responsibility}</h3><p>{a.groupName||"Whole event"}</p><small>{a.sessionName||"All assigned event days"}</small></article>)}</div><h3>My schedule</h3><div className="event-session-grid">{assigned.map(s=><article key={s.id}><h3>{s.name}</h3><p>{eventDate(s.startsAt)} · {s.startsAt.slice(11,16)}–{s.endsAt.slice(11,16)} ({data.event.timezone})</p><button className="outline-button" disabled={busy||data.event.lifecycle!=="LIVE"} onClick={async()=>{setBusy(true);try{await eventRequest(Number(data.event.id),"volunteer-attendance","POST",{sessionId:Number(s.id)});setMessage("Your event attendance is confirmed.");}catch(e){setError(e instanceof Error?e.message:"Unable to confirm attendance.");}finally{setBusy(false);}}}>I’m here for this session</button></article>)}</div></section><EventChildRegister id={Number(data.event.id)} children={data.children} data={data} eventName={data.event.name} eventType={data.event.type}/><EventCurriculum id={Number(data.event.id)} data={data} sessions={assigned} groups={groups} manage={false} reload={()=>open(Number(data.event.id))}/></>}<AppearancePreference/></div>;
}
