"use client";
import { useEffect,useState } from "react";
import { resourceNotes,type NoteBlock } from "@/lib/curriculum-notes";
import { downloadNotePdf,notePicture } from "@/lib/curriculum-note-pdf";
import { EventDialog } from "./event-dialog";
import { RecordBadge } from "./record-badge";
import { eventRequest,type CurriculumResource } from "./event-history-panels";
import type { EventPalette } from "@/lib/event-palette";
import "./event-curriculum-note.css";
function Picture({eventId,block}:{eventId:number;block:NoteBlock}){const[url,setUrl]=useState("");const[error,setError]=useState("");useEffect(()=>{let active=true,object="";notePicture(eventId,block.fileId!).then(b=>{if(active){object=URL.createObjectURL(b);setUrl(object);}}).catch(()=>{if(active)setError("Picture unavailable.");});return()=>{active=false;if(object)URL.revokeObjectURL(object);};},[eventId,block.fileId]);return <figure>{url?<img src={url} alt={block.caption||"Curriculum illustration"}/>:<p role="status">{error||"Loading picture…"}</p>}{block.caption&&<figcaption>{block.caption}</figcaption>}</figure>;}
export function NoteSections({eventId,blocks}:{eventId:number;blocks:NoteBlock[]}){return <div className="curriculum-note-document">{blocks.map((b,i)=>b.type==="heading"?<h3 key={i}>{b.text}</h3>:b.type==="list"?<ul key={i}>{b.text?.split("\n").filter(Boolean).map((item,n)=><li key={n}>{item}</li>)}</ul>:b.type==="image"?<Picture key={`${i}:${b.fileId}`} eventId={eventId} block={b}/>:<p key={i}>{b.text}</p>)}</div>;}
export function NoteBlockEditor({blocks,onChange,eventId,onBusyChange}:{blocks:NoteBlock[];onChange:(blocks:NoteBlock[])=>void;eventId:number;onBusyChange?:(busy:boolean)=>void}){
 const[busy,setBusy]=useState(false);const[error,setError]=useState("");const update=(i:number,change:Partial<NoteBlock>)=>onChange(blocks.map((b,n)=>n===i?{...b,...change}:b));
 useEffect(()=>{onBusyChange?.(busy);},[busy,onBusyChange]);
 return <fieldset disabled={busy} className="note-block-editor"><legend>Organised teaching notes</legend><p>Add headings, paragraphs, lists and optional pictures. List items go on separate lines.</p>{blocks.map((b,i)=><article key={i}><header><b>{i+1}. {b.type}</b><div><button type="button" className="outline-button" disabled={i===0||busy} aria-label={`Move section ${i+1} up`} onClick={()=>{const next=[...blocks];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next);}}>↑</button><button type="button" className="outline-button" disabled={i===blocks.length-1||busy} aria-label={`Move section ${i+1} down`} onClick={()=>{const next=[...blocks];[next[i+1],next[i]]=[next[i],next[i+1]];onChange(next);}}>↓</button><button type="button" className="outline-button" disabled={busy} aria-label={`Remove section ${i+1}`} onClick={()=>onChange(blocks.filter((_,n)=>n!==i))}>Remove</button></div></header>{b.type==="image"?<><Picture eventId={eventId} block={b}/><label>Picture caption<input maxLength={1000} value={b.caption||""} onChange={e=>update(i,{caption:e.target.value})}/></label></>:<label>{b.type==="heading"?"Heading":b.type==="list"?"List items":"Paragraph"}{b.type==="heading"?<input maxLength={180} value={b.text||""} onChange={e=>update(i,{text:e.target.value})}/>:<textarea rows={b.type==="list"?8:12} maxLength={100000} value={b.text||""} onChange={e=>update(i,{text:e.target.value})}/>}</label>}</article>)}<div className="note-editor-actions">{(["heading","paragraph","list"]as const).map(type=><button type="button" className="outline-button" disabled={busy||blocks.length>=200} key={type} onClick={()=>onChange([...blocks,{type,text:""}])}>+ {type}</button>)}<label className="outline-button">{busy?"Uploading…":"+ Picture"}<input type="file" disabled={busy||blocks.length>=200} accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setBusy(true);setError("");try{if(file.size>25*1024*1024)throw Error("Choose a picture under 25 MB.");const f=new FormData();f.append("file",file);const saved=await eventRequest(eventId,"files","POST",f);onChange([...blocks,{type:"image",fileId:Number(saved.id),caption:""}]);}catch(e){setError(e instanceof Error?e.message:"Picture upload failed.");}finally{setBusy(false);}}}/></label></div>{error&&<p role="alert" className="event-error">{error}</p>}</fieldset>;
}
export function EventCurriculumNote({id,resource,eventName,eventType,scope,palette,manage,onClose,reload}:{id:number;resource:CurriculumResource;eventName:string;eventType:string;scope:string;palette?:EventPalette;manage:boolean;onClose:()=>void;reload:()=>Promise<void>}){
 const[blocks,setBlocks]=useState(()=>resourceNotes(resource));const[savedBlocks,setSavedBlocks]=useState(()=>resourceNotes(resource));const[editing,setEditing]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 return <EventDialog title={resource.title} onClose={onClose}><div className="curriculum-note-meta"><RecordBadge tone="green">{resource.type.replaceAll("_"," ")}</RecordBadge><small>{scope}</small></div><div className="curriculum-note-actions"><button className="solid-button" disabled={busy||editing||!blocks.length} onClick={async()=>{setBusy(true);setError("");try{await downloadNotePdf(id,eventType,{title:resource.title,eventName,type:resource.type,scope,blocks,palette});}catch(e){setError(e instanceof Error?e.message:"Could not export notes.");}finally{setBusy(false);}}}>{busy?"Working…":"Download styled PDF"}</button>{manage&&!editing&&<button className="outline-button" onClick={()=>setEditing(true)}>Edit note sections</button>}</div>{error&&<p role="alert" className="event-error">{error}</p>}{editing?<form className="event-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const result=await eventRequest(id,`curriculum/${resource.id}/notes`,"PATCH",{noteBlocks:blocks});setBlocks(result.noteBlocks);setSavedBlocks(result.noteBlocks);setEditing(false);await reload();}catch(e){setError(e instanceof Error?e.message:"Could not save sections.");}finally{setBusy(false);}}}><NoteBlockEditor eventId={id} blocks={blocks} onChange={setBlocks} onBusyChange={setBusy}/><div className="note-editor-actions"><button disabled={busy} className="solid-button">Save sections</button><button type="button" disabled={busy} className="outline-button" onClick={()=>{setBlocks(savedBlocks);setEditing(false);}}>Cancel</button></div></form>:<NoteSections eventId={id} blocks={blocks}/>}</EventDialog>;
}
