"use client";
import { useEffect,useState } from "react";
import { FiDownload,FiSearch } from "react-icons/fi";
import { AppSelect } from "./app-dropdown";
import { DirectoryPagination } from "./directory-pagination";
import { RecordBadge } from "./record-badge";
import { EventDialog } from "./event-dialog";
import { eventRequest,type HistoryData } from "./event-history-panels";
import { eventDate } from "@/lib/events";
import { downloadTablePdf,loadEventReportBranding,pdfInitials } from "@/lib/table-pdf";
export type EventChild={id:number;name:string;homeCampus:string;homeCampusId?:number;guardianName:string;guardianPhone?:string;emergencyPhone?:string;careNotes?:string;groupName?:string;dateOfBirth?:string;reportedAge?:number;ageQualifier?:string};
export function EventChildRegister({id,children,data,eventName,eventType,privateDetails=false,manage=false,reload,historical=false}:{id:number;children:EventChild[];data:HistoryData;eventName:string;eventType:string;privateDetails?:boolean;manage?:boolean;reload?:()=>Promise<void>;historical?:boolean}){
 const[day,setDay]=useState(String(data.days[0]?.id||""));const[query,setQuery]=useState("");const[campus,setCampus]=useState("");const[page,setPage]=useState(1);const[size,setSize]=useState(12);const[selected,setSelected]=useState<EventChild|null>(null);const[profileTab,setProfileTab]=useState("Overview");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{setPage(1);},[day,query,campus,size]);
 const marks=data.historicalAttendance.filter(a=>String(a.dayId)===day);
 const rows=children.filter(c=>(!historical||marks.some(m=>Number(m.childId)===Number(c.id)))&&(!campus||c.homeCampus===campus)&&`${c.name} ${c.homeCampus} ${c.guardianName}`.toLowerCase().includes(query.toLowerCase()));
 const contacts=selected?data.contacts.filter(c=>Number(c.childId)===Number(selected.id)):[];
 const guardian=(c:EventChild)=>c.guardianName||data.contacts.find(p=>Number(p.childId)===Number(c.id)&&["GUARDIAN","PICKUP"].includes(p.type))?.name||"Not recorded";
 async function exportPdf(){setBusy(true);try{await downloadTablePdf(`${eventName}-${historical?"attendance":"children"}.pdf`,{branding:await loadEventReportBranding(eventType),title:eventName,subtitle:historical?`${data.days.find(d=>String(d.id)===day)?.label} · Historical attendance · Unchecked does not prove absence`:"Registered children",columns:historical?["Child","Home campus","Parent / guardian","Drop-off","Pickup"]:["Child","Home campus","Parent / guardian"],rows:rows.map(c=>{const m=marks.find(a=>Number(a.childId)===Number(c.id));return historical?[c.name,c.homeCampus,guardian(c),markText(m?.present,"Recorded"),markText(m?.pickedUp,"Recorded")]:[c.name,c.homeCampus,guardian(c)];})});}catch(e){setError(e instanceof Error?e.message:"Download failed.");}finally{setBusy(false);}}
 return <section className="event-panel event-register"><header><div><p className="eyebrow">{historical?"Event archive":"Event directory"}</p><h2>{historical?"Daily attendance register":"Registered children"}</h2><p>{historical?"Original drop-off and pickup marks. Unchecked boxes are not verified absences or outstanding pickups.":"Children, home campuses and parent / guardian names for this event."}</p></div><button className="outline-button" disabled={busy||!rows.length} onClick={()=>void exportPdf()}><FiDownload/>Download PDF</button></header><div className="event-toolbar"><label className="event-search"><FiSearch/><input aria-label="Search event children" placeholder="Search child, campus or guardian…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{historical&&<AppSelect aria-label="Attendance day" value={day} onChange={e=>setDay(e.target.value)}>{data.days.map(d=><option key={d.id} value={d.id}>{d.label} · {eventDate(d.date)}</option>)}</AppSelect>}<AppSelect aria-label="Filter home campus" value={campus} onChange={e=>setCampus(e.target.value)}><option value="">All campuses</option>{[...new Set(children.map(c=>c.homeCampus))].sort().map(c=><option key={c} value={c}>{c}</option>)}</AppSelect></div><p className="event-result-count">{rows.length} children{campus?` · ${campus}`:""}</p><div className="records-table event-table"><table><thead><tr><th>S/N</th><th>Child</th><th>Home campus</th><th>Parent / guardian</th>{historical&&<><th>Drop-off</th><th>Pickup</th></>}<th>Profile</th></tr></thead><tbody>{rows.slice((page-1)*size,page*size).map((c,i)=>{const m=marks.find(a=>Number(a.childId)===Number(c.id));return <tr key={c.id}><td data-label="S/N">{(page-1)*size+i+1}</td><td data-label="Child"><div className="event-child-identity"><span className="event-avatar">{pdfInitials(c.name)}</span><b>{c.name}</b></div></td><td data-label="Home campus"><RecordBadge tone={c.homeCampusId?"green":"neutral"}>{c.homeCampus||"Not recorded"}</RecordBadge></td><td data-label="Parent / guardian">{guardian(c)}</td>{historical&&<><td data-label="Drop-off"><Mark value={m?.present} label="Recorded"/></td><td data-label="Pickup"><Mark value={m?.pickedUp} label="Recorded"/></td></>}<td data-label="View"><button className="records-view-action" onClick={()=>{setSelected(c);setProfileTab("Overview");}}>View →</button></td></tr>;})}</tbody></table></div>{!rows.length&&<div className="event-empty">No children match these filters.</div>}<DirectoryPagination page={page} total={rows.length} pageSize={size} onPageChange={setPage} onPageSizeChange={setSize} noun="children"/>{error&&<p role="alert" className="event-error">{error}</p>}
 {selected&&<EventDialog title={selected.name} drawer onClose={()=>setSelected(null)}><div className="event-profile-hero"><span className="event-avatar">{pdfInitials(selected.name)}</span><div><p>{selected.homeCampus||"Campus not recorded"}</p><RecordBadge tone="green">{eventName}</RecordBadge></div></div>{privateDetails&&<nav className="event-tabs" aria-label="Child event profile">{["Overview","Guardians","Care","Attendance"].map(t=><button key={t} aria-current={profileTab===t?"page":undefined} onClick={()=>setProfileTab(t)}>{t}</button>)}</nav>}{profileTab==="Overview"&&<div className="event-profile-fields"><Field label="Child name" value={selected.name}/><Field label="Home campus" value={selected.homeCampus}/><Field label="Parent / guardian" value={guardian(selected)}/>{privateDetails&&<><Field label="Class / group" value={selected.groupName}/><Field label="Age at event" value={selected.reportedAge!=null?`${selected.reportedAge}${selected.ageQualifier||""} years`:undefined}/></>}{manage&&<label className="event-form">Edit home campus<AppSelect aria-label="Child home campus" disabled={busy} value={String(selected.homeCampusId||"")} onChange={async e=>{setBusy(true);try{const homeCampusId=Number(e.target.value);await eventRequest(id,`children/${selected.id}`,"PATCH",{homeCampusId});setSelected({...selected,homeCampusId,homeCampus:data.campuses.find(c=>Number(c.id)===homeCampusId)?.name||"Not recorded"});await reload?.();}catch(e){setError(e instanceof Error?e.message:"Could not save campus.");}finally{setBusy(false);}}}><option value="" disabled>Not recorded</option>{data.campuses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</AppSelect></label>}</div>}{privateDetails&&profileTab==="Guardians"&&<div className="event-profile-fields"><Field label="Parent / guardian" value={guardian(selected)}/><Field label="Phone" value={selected.guardianPhone}/><Field label="Emergency phone" value={selected.emergencyPhone}/>{contacts.map(c=><div className="event-contact-card" key={c.id}><small>{c.type.replaceAll("_"," ")}</small><b>{c.name||"Name not recorded"}</b><p>{c.phone||"Phone not recorded"}</p>{c.sourceText&&<p>{c.sourceText}</p>}</div>)}</div>}{privateDetails&&profileTab==="Care"&&<div className="event-resource-notes">{selected.careNotes||"No care information recorded."}</div>}{privateDetails&&profileTab==="Attendance"&&<div className="event-profile-fields">{data.historicalAttendance.filter(m=>Number(m.childId)===Number(selected.id)).map(m=><div key={m.dayId}><h3>{data.days.find(d=>Number(d.id)===Number(m.dayId))?.label}</h3><p>Drop-off: <Mark value={m.present} label="Recorded"/> · Pickup: <Mark value={m.pickedUp} label="Recorded"/></p><small>Daily card: {data.cards.find(c=>Number(c.childId)===Number(selected.id)&&Number(c.dayId)===Number(m.dayId))?.number||"Not recorded"}</small></div>)}</div>}{error&&<p role="alert" className="event-error">{error}</p>}</EventDialog>}
 </section>;
}
function Field({label,value}:{label:string;value?:string}){return <div><small>{label}</small><b>{value||"Not recorded"}</b></div>;}
function markText(value:number|null|undefined,label:string){return value==null?"Not recorded":Number(value)===1?label:"Unchecked in source";}
function Mark({value,label}:{value:number|null|undefined;label:string}){return <RecordBadge tone={value==null?"neutral":Number(value)===1?"green":"orange"}>{markText(value,label)}</RecordBadge>;}
