"use client";
import { useState } from "react";
import { AppSelect } from "./app-dropdown";
import { DirectoryPagination } from "./directory-pagination";
import { RecordBadge } from "./record-badge";
import { downloadTablePdf,loadEventReportBranding } from "@/lib/table-pdf";
import { eventDate } from "@/lib/events";
import { eventRequest,type HistoryData } from "./event-history-panels";

export function EventHistoricalRoster({id,data,staff,reload,eventType="VBS"}:{eventType?:string;id:number;data:HistoryData;staff:{id:number;name:string}[];reload:()=>Promise<void>}){
 const[day,setDay]=useState("");const[group,setGroup]=useState("");const[query,setQuery]=useState("");const[page,setPage]=useState(1);const[person,setPerson]=useState("");const[staffId,setStaffId]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const assignments=data.historicalRoster||[];const groups=data.rosterGroups||[];const people=data.rosterPeople||[];
 const volunteerNames=[...new Set(assignments.map(a=>a.name).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
 const rows=data.programme.filter(a=>a.sourceName&&(!day||String(a.dayId)===day)&&(!group||String(a.rosterGroupId)===group||assignments.some(r=>Number(r.activityId)===Number(a.id)&&r.groupName===groups.find(g=>String(g.id)===group)?.name))&&`${a.title} ${a.responsibleRaw} ${assignments.filter(r=>Number(r.activityId)===Number(a.id)).map(r=>r.name).join(" ")}`.toLowerCase().includes(query.toLowerCase()));
 const names=(activityId:number)=>assignments.filter(r=>Number(r.activityId)===Number(activityId)).map(r=>`${r.name}${r.groupName?` (${r.groupName})`:""}`).join(", ");
 async function link(){setBusy(true);setError("");try{await eventRequest(id,`roster-people/${person}`,"PATCH",{staffId:Number(staffId)||null});await reload();setPerson("");setStaffId("");}catch(e){setError(e instanceof Error?e.message:"Could not link identity.");}finally{setBusy(false);}}
 if(!assignments.length)return null;
 return <section className="event-panel event-historical-roster"><header><div><p className="eyebrow">Historical volunteer roster</p><h2>Daily team & programme</h2><p>Planned responsibilities from the original roster—not confirmed volunteer attendance. Call time: 8:00 AM daily.</p></div><button className="outline-button" disabled={busy||!rows.length} onClick={()=>{setBusy(true);void loadEventReportBranding(eventType).then(branding=>downloadTablePdf("event-planned-roster",{branding,title:"VBS 2026 · Planned volunteer roster",subtitle:"24–29 August 2026 · Source: Daily roaster VBS.pdf · Attendance not inferred",columns:["Day","Time","Activity","Responsible"],rows:rows.map(a=>[data.days.find(d=>Number(d.id)===Number(a.dayId))?.label||"",`${a.startsAt?.slice(0,5)}–${a.endsAt?.slice(0,5)}`,a.title,names(a.id)||a.responsibleRaw||"Not recorded"])})).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Download PDF</button></header>
 <p className="event-warning">Saturday’s roster ends at 1:00 PM; the separate proposed finale outline ends at 2:30 PM. Both sources are retained. Name variants remain separate until reviewed.</p>
 <h3>Volunteers named in the original roster</h3><p>These are planned names from the archived roster, not confirmed attendance or active accounts.</p><div className="event-detail-grid">{volunteerNames.map(name=><div key={name}><b>{name}</b><small>Historical roster</small></div>)}</div>
 <div className="event-detail-grid">{assignments.filter(r=>!r.activityId&&(!day||String(r.dayId)===day)).map(r=><div key={r.id}><small>{data.days.find(d=>Number(d.id)===Number(r.dayId))?.label} · Day lead</small><b>{r.name}</b></div>)}</div>
 <div className="event-toolbar"><label className="event-search"><input aria-label="Search historical roster" placeholder="Search activity or volunteer…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><AppSelect aria-label="Historical roster day" value={day} onChange={e=>{setDay(e.target.value);setPage(1);}}><option value="">All days</option>{data.days.map(d=><option key={d.id} value={d.id}>{d.label} · {eventDate(d.date)}</option>)}</AppSelect><AppSelect aria-label="Historical roster class or rotation" value={group} onChange={e=>{setGroup(e.target.value);setPage(1);}}><option value="">All classes & rotations</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}{g.classes?` · ${g.classes}`:""}</option>)}</AppSelect></div>
 <div className="event-table"><table><thead><tr><th>Day / Time</th><th>Activity</th><th>Planned team</th><th>Source</th></tr></thead><tbody>{rows.slice((page-1)*12,page*12).map(a=><tr key={a.id}><td><b>{data.days.find(d=>Number(d.id)===Number(a.dayId))?.label}</b><small>{a.startsAt?.slice(0,5)}–{a.endsAt?.slice(0,5)}</small></td><td><b>{a.title}</b><RecordBadge tone="blue">Planned</RecordBadge></td><td>{names(a.id)||a.responsibleRaw||"Not recorded"}{assignments.some(r=>Number(r.activityId)===Number(a.id)&&Number(r.reviewRequired))&&<small>Source name block needs review</small>}</td><td>{a.sourceName}<small>Page {a.sourcePage}</small></td></tr>)}</tbody></table></div>
 <DirectoryPagination page={page} total={rows.length} pageSize={12} onPageChange={setPage} noun="planned activities"/>
 {staff.length>0&&<details><summary>Review volunteer identities ({people.length} source names)</summary><p>Link a confirmed source name to an existing teacher. This does not create an account, confirm attendance or grant event access. First-name matches are never automatic.</p><div className="event-toolbar"><AppSelect aria-label="Source volunteer identity" value={person} onChange={e=>{setPerson(e.target.value);setStaffId(String(people.find(p=>String(p.id)===e.target.value)?.staffId||""));}}><option value="">Choose source name</option>{people.map(p=><option key={p.id} value={p.id} disabled={Boolean(Number(p.reviewRequired))}>{p.name}{p.staffName?` → ${p.staffName}`:""}{Number(p.reviewRequired)?" · ambiguous block":""}</option>)}</AppSelect><AppSelect aria-label="Link existing staff identity" value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Unlinked source identity</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</AppSelect><button className="outline-button" disabled={!person||busy} onClick={()=>void link()}>Save identity link</button></div></details>}{error&&<p className="event-error" role="alert">{error}</p>}</section>;
}
