"use client";
import { useState,type CSSProperties } from "react";
import { scanEventImage,junglePalette,paletteStyle,type EventPalette } from "@/lib/event-palette";
import { eventLifecycle,type MinistryEvent } from "@/lib/events";
import { AppSelect } from "./app-dropdown";
import { eventRequest,type HistoryData } from "./event-history-panels";
export function EventAppearanceEditor({id,data,event,reload}:{id:number;data:HistoryData;event:MinistryEvent;reload:()=>Promise<void>}){
 const a=data.appearance;const[f,setF]=useState({preset:a.preset,enabled:Boolean(Number(a.enabled)),applyDashboard:Boolean(Number(a.apply_dashboard)),preserveAfter:Boolean(Number(a.preserve_after)),artworkUrl:a.artwork_url||"",artworkFileId:Number(a.artwork_file_id)||null,palette:a.palette||junglePalette});const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[pending,setPending]=useState<File|null>(null);
 const past=["COMPLETED","ARCHIVED"].includes(eventLifecycle(event,new Date()));
 async function scan(file?:File){if(!file)return;setBusy(true);setMessage("");try{const palette=await scanEventImage(file);setPending(file);setF({...f,preset:"CUSTOM",palette,enabled:true});setMessage("Colours extracted. Readable text colours have been checked. Save to attach this image and palette to the event.");}catch(e){setMessage(e instanceof Error?e.message:"Could not read image colours.");}finally{setBusy(false);}}
 return <section className="event-panel"><header><div><p className="eyebrow">Event appearance</p><h2>A look for this event</h2><p>{past?"Keep this appearance in the event archive. Staff can choose it in Settings; it will not replace current dashboards automatically.":"Offer a temporary dashboard appearance during the event, and optionally keep it available afterwards."}</p></div></header><form className="event-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{let fileId=f.artworkFileId;if(pending){const body=new FormData();body.append("file",pending);fileId=(await eventRequest(id,"files","POST",body)).id;}await eventRequest(id,"appearance","POST",{...f,artworkFileId:fileId});setF({...f,artworkFileId:fileId});setPending(null);await reload();setMessage("Event appearance saved.");window.dispatchEvent(new Event("tpk-appearance-changed"));}catch(e){setMessage(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false);}}}><div className="event-form-grid"><label>Appearance<AppSelect value={f.preset} disabled={busy} onChange={e=>setF({...f,preset:e.target.value,palette:e.target.value==="JUNGLE"?junglePalette:f.palette})}><option value="DEFAULT">Default TPK</option><option value="JUNGLE">Great Jungle Journey · forest, brown & gold</option><option value="CUSTOM" disabled={f.preset!=="CUSTOM"}>Colours from uploaded artwork</option></AppSelect></label><label>Upload artwork to generate colours<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>void scan(e.target.files?.[0])}/><small>PNG, JPG or WebP · up to 25 MB. Scanned in your browser; saved privately with the event.</small></label></div>{f.preset!=="DEFAULT"&&<ThemePreview palette={f.palette}/>}<label className="event-checkbox"><input type="checkbox" checked={f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/>Enable this event appearance</label>{!past&&<label className="event-checkbox"><input type="checkbox" checked={f.applyDashboard} onChange={e=>setF({...f,applyDashboard:e.target.checked})}/>Offer on dashboards during this event</label>}<label className="event-checkbox"><input type="checkbox" checked={f.preserveAfter} onChange={e=>setF({...f,preserveAfter:e.target.checked})}/>{past?"Preserve this event appearance after event":"Keep this appearance available after the event dates"}</label>{!past&&<small>Automatic event mode can continue afterwards when both options are enabled. Default TPK remains available.</small>}<button className="solid-button" disabled={busy}>{busy?"Preparing…":"Save appearance"}</button>{message&&<p role="status">{message}</p>}</form></section>;
}
function ThemePreview({palette}:{palette:EventPalette}){return <div className="event-theme-preview" style={paletteStyle(palette) as CSSProperties}><div><b>Event dashboard</b><span>Forest-inspired colours · readable text</span></div><section><h3>Your event, your team</h3><p>Default TPK stays one choice away.</p><button type="button">Preview action</button><div className="event-colour-chips">{[palette.primary,palette.secondary,palette.accent].map(c=><span key={c}><i style={{background:c}}/>{c}</span>)}</div></section></div>;}
