"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
type Class = { id: string; name: string; ageLabel: string };
export function FamilyRegistration() {
  const router = useRouter(); const [classes, setClasses] = useState<Class[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/classes").then((r) => r.json()).then(setClasses); }, []);
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(e.currentTarget)); const res = await fetch("/api/families", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await res.json(); setSaving(false); if (!res.ok) return setMessage(result.error ?? "Could not register family."); setMessage(`Family registered. Family ID: ${result.familyCode}. A secure pass has been created.`); e.currentTarget.reset(); setTimeout(() => router.push("/families"), 1400); }
  return <form className="card form-card" onSubmit={submit}>{message && <div className="notice">{message}</div>}<h2>Family details</h2><div className="field-grid" style={{marginTop:18}}><div className="field"><label>Family surname</label><input required name="surname" placeholder="e.g. Okafor" /></div><div className="field"><label>Primary phone</label><input required name="phone" placeholder="+234 803 000 0000" /></div><div className="field"><label>Guardian first name</label><input required name="guardianFirstName" /></div><div className="field"><label>Guardian last name</label><input required name="guardianLastName" /></div></div><h2 style={{marginTop:16}}>First child</h2><div className="field-grid" style={{marginTop:18}}><div className="field"><label>Child first name</label><input required name="childFirstName" /></div><div className="field"><label>Child last name</label><input required name="childLastName" /></div><div className="field"><label>Class</label><select required name="classId" defaultValue=""><option value="" disabled>Select a class</option>{classes.map((item) => <option value={item.id} key={item.id}>{item.name} — {item.ageLabel}</option>)}</select></div><div className="field"><label>Authorised pickup note (optional)</label><input name="pickupNote" placeholder="e.g. Aunt Amaka may collect" /></div></div><div className="field"><label>Private safeguarding / medical note (optional)</label><textarea name="notes" placeholder="Visible only to authorised children’s team staff." /></div><div className="form-actions"><button type="button" onClick={() => router.back()} className="btn ghost">Cancel</button><button className="btn orange" disabled={saving}>{saving ? "Registering…" : "Create family"}</button></div></form>;
}
