"use client";

import { useMemo, useState } from "react";
import { FiArrowLeft, FiCheck, FiChevronRight, FiLock, FiMinus, FiPlus } from "react-icons/fi";

type ChildDraft = { firstName: string; lastName: string; dob: string; gender: string; care: string };
const returningChildren = [
  { id: 1, name: "David Adebayo", className: "Tribe A", note: "" },
  { id: 2, name: "Sarah Adebayo", className: "Tribe B", note: "" },
  { id: 3, name: "Joshua Adebayo", className: "Tribe C", note: "Already checked in at 8:42 AM" },
];
const blankChild = (): ChildDraft => ({ firstName: "", lastName: "", dob: "", gender: "", care: "" });
function classFor(dob: string) { if (!dob) return "Class assignment pending"; const age = Math.floor((Date.now() - new Date(dob).getTime()) / 31557600000); if (age >= 13 && age <= 17) return "TribePetra Teens"; if (age >= 9 && age <= 12) return "Tribe A"; if (age >= 5 && age <= 8) return "Tribe B"; if (age >= 3 && age <= 4) return "Tribe C"; return "Class assignment pending"; }

export function ParentCheckIn() {
  const [step, setStep] = useState<"phone" | "returning" | "new" | "pickup" | "success">("phone");
  const [phone, setPhone] = useState(""); const [selected, setSelected] = useState<number[]>([]); const [children, setChildren] = useState<ChildDraft[]>([blankChild()]); const [pickup, setPickup] = useState("me"); const [guardian, setGuardian] = useState({ firstName: "", lastName: "", relationship: "Parent", email: "" }); const [other, setOther] = useState({ firstName: "", lastName: "", phone: "", relationship: "" });
  const selectedNames = useMemo(() => returningChildren.filter((child) => selected.includes(child.id)).map((child) => child.name), [selected]);
  const submitPhone = (event: React.FormEvent) => { event.preventDefault(); setStep(phone.replace(/\D/g, "").endsWith("1234567") || phone.includes("0803") ? "returning" : "new"); };
  const updateChild = (index: number, key: keyof ChildDraft, value: string) => setChildren((items) => items.map((child, childIndex) => childIndex === index ? { ...child, [key]: value } : child));
  const readyNew = children.every((child) => child.firstName && child.lastName && child.dob && child.gender) && guardian.firstName && guardian.lastName;
  return <div className="parent-page"><header><div className="parent-mark">TPK</div><div><b>TribePetra Kids</b><span>Petra Wuse</span></div></header><main className="parent-card">
    {step !== "phone" && step !== "success" && <button className="parent-back" onClick={() => setStep("phone")}><FiArrowLeft /> Start again</button>}
    {step === "phone" && <><p className="parent-eyebrow">Sunday check-in</p><h1>Welcome! Let&apos;s get the kids checked in.</h1><p className="parent-copy">Enter your phone number so we can find your children.</p><form onSubmit={submitPhone}><label>Parent or guardian phone number<input inputMode="tel" autoFocus required value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="0803 123 4567" /></label><button className="parent-primary">Continue <FiChevronRight /></button></form><p className="parent-help"><FiLock /> No account or password is needed.</p></>}
    {step === "returning" && <><p className="parent-eyebrow">Welcome back, Grace</p><h1>Who are you checking in today?</h1><p className="parent-copy">Choose every child attending this service.</p><div className="parent-children">{returningChildren.map((child) => <label className={`parent-child ${child.note ? "disabled" : ""}`} key={child.id}><input type="checkbox" checked={selected.includes(child.id)} disabled={Boolean(child.note)} onChange={() => setSelected((ids) => ids.includes(child.id) ? ids.filter((id) => id !== child.id) : [...ids, child.id])} /><span><b>{child.name}</b><small>{child.className}{child.note && ` · ${child.note}`}</small></span></label>)}</div><button className="parent-secondary" onClick={() => setStep("new")}><FiPlus /> Add another child</button><button className="parent-primary" disabled={!selected.length} onClick={() => setStep("pickup")}>Check in {selected.length || ""} child{selected.length === 1 ? "" : "ren"} <FiChevronRight /></button></>}
    {step === "new" && <><p className="parent-eyebrow">Welcome to TribePetra Kids!</p><h1>Register a new child</h1><p className="parent-copy">We&apos;ll keep this short, then check them in today.</p><section className="parent-section"><h2>Guardian</h2><div className="parent-grid"><Field label="First name" value={guardian.firstName} onChange={(value) => setGuardian({ ...guardian, firstName: value })} /><Field label="Last name" value={guardian.lastName} onChange={(value) => setGuardian({ ...guardian, lastName: value })} /><Field label="Phone number" value={phone} onChange={setPhone} /><Field label="Relationship" value={guardian.relationship} onChange={(value) => setGuardian({ ...guardian, relationship: value })} /></div></section>{children.map((child, index) => <section className="parent-section" key={index}><div className="parent-section-title"><h2>Child {index + 1}</h2>{children.length > 1 && <button onClick={() => setChildren((items) => items.filter((_, childIndex) => childIndex !== index))}><FiMinus /> Remove</button>}</div><div className="parent-grid"><Field label="First name" value={child.firstName} onChange={(value) => updateChild(index, "firstName", value)} /><Field label="Last name" value={child.lastName} onChange={(value) => updateChild(index, "lastName", value)} /><Field label="Date of birth" type="date" value={child.dob} onChange={(value) => updateChild(index, "dob", value)} /><label>Gender<select value={child.gender} onChange={(event) => updateChild(index, "gender", event.target.value)}><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><label className="full-field">Important care information <textarea value={child.care} onChange={(event) => updateChild(index, "care", event.target.value)} placeholder="Optional — allergies, accessibility or care needs" /></label></div><p className="class-result">{classFor(child.dob) === "Class assignment pending" ? "A TPK Admin will complete class assignment." : `${child.firstName || "This child"} will join ${classFor(child.dob)}.`}</p></section>)}<button className="parent-secondary" onClick={() => setChildren((items) => [...items, blankChild()])}><FiPlus /> Add another child</button><button className="parent-primary" disabled={!readyNew} onClick={() => setStep("pickup")}>Continue to pickup details <FiChevronRight /></button></>}
    {step === "pickup" && <><p className="parent-eyebrow">One more thing</p><h1>Who will be picking up the children?</h1><p className="parent-copy">A pickup code helps us find the record. The team will still verify the authorised adult.</p><label className="pickup-choice"><input type="radio" checked={pickup === "me"} onChange={() => setPickup("me")} /><span><b>Me</b><small>Use the submitting guardian</small></span></label><label className="pickup-choice"><input type="radio" checked={pickup === "other"} onChange={() => setPickup("other")} /><span><b>Another authorised person</b><small>Add the adult who will collect the children</small></span></label>{pickup === "other" && <div className="parent-grid pickup-fields"><Field label="First name" value={other.firstName} onChange={(value) => setOther({ ...other, firstName: value })} /><Field label="Last name" value={other.lastName} onChange={(value) => setOther({ ...other, lastName: value })} /><Field label="Phone number" value={other.phone} onChange={(value) => setOther({ ...other, phone: value })} /><Field label="Relationship" value={other.relationship} onChange={(value) => setOther({ ...other, relationship: value })} /></div>}<button className="parent-primary" onClick={() => setStep("success")}>Confirm check-in <FiCheck /></button></>}
    {step === "success" && <div className="parent-success"><i><FiCheck /></i><p className="parent-eyebrow">You&apos;re all checked in</p><h1>See you after service!</h1><p>{selectedNames.length ? selectedNames.join(" and ") : children.map((child) => `${child.firstName} ${child.lastName}`).join(" and ")} {selectedNames.length + children.length > 1 ? "are" : "is"} marked present for today.</p><div className="pickup-code"><span>Your pickup code</span><b>TPK-7M4</b></div><button className="parent-primary" onClick={() => { setStep("phone"); setSelected([]); }}>Done</button></div>}
  </main><footer>TRIBEPETRA KIDS · CHECK IN · BELONG · GROW</footer></div>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label>{label}<input type={type} required={label !== "Phone number" || Boolean(value)} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
