"use client";

/** Keeps teacher-only content in the same approved parent-form visual system. */
export function TeacherParentFormParity() {
  return <style jsx global>{`
    .teacher-auth-page{min-height:100vh!important;display:grid!important;grid-template-columns:minmax(360px,44vw) 1fr!important;background:#fffdf9!important;color:#091936!important;font-family:var(--font-body,Arial,sans-serif)!important}
    .teacher-auth-page .parent-photo-slider{position:fixed!important;inset:0 auto 0 0!important;width:min(44vw,710px)!important;overflow:hidden!important;background:#11241c!important;color:#fff!important}
    .teacher-auth-page .parent-photo-slider-image{object-fit:cover!important}.teacher-auth-page .parent-photo-slider-shade{position:absolute!important;inset:0!important;background:linear-gradient(90deg,rgba(1,12,8,.55),rgba(2,14,9,.08) 65%),linear-gradient(0deg,rgba(0,0,0,.53),transparent 54%)!important}
    .teacher-auth-page .parent-photo-slider-brand{position:absolute!important;z-index:1!important;top:42px!important;left:48px!important;display:grid!important;gap:4px!important}.teacher-auth-page .parent-photo-slider-logo{width:175px!important;height:51px!important;object-fit:contain!important;object-position:left!important}.teacher-auth-page .parent-photo-slider-brand span{margin-left:5px!important;text-transform:uppercase!important;letter-spacing:.15em!important;font-size:12px!important;font-weight:800!important}.teacher-auth-page .parent-photo-slider-copy{position:absolute!important;z-index:1!important;left:52px!important;bottom:136px!important;max-width:345px!important}.teacher-auth-page .parent-photo-slider-copy h2{margin:0!important;color:#fff!important;font:700 clamp(36px,4vw,56px)/1.02 Georgia,serif!important;letter-spacing:-.045em!important}.teacher-auth-page .parent-photo-slider-copy i{display:block!important;width:70px!important;height:5px!important;margin:22px 0!important;border-radius:99px!important;background:#ffd26d!important}.teacher-auth-page .parent-photo-slider-copy p{max-width:255px!important;margin:0!important;font-size:17px!important;line-height:1.42!important}.teacher-auth-page .parent-photo-slider-footer{position:absolute!important;z-index:1!important;left:52px!important;bottom:42px!important;text-transform:uppercase!important;letter-spacing:.2em!important;font-size:10px!important;font-weight:900!important}
    .teacher-auth-main{grid-column:2!important;padding:33px clamp(28px,7vw,106px) 46px!important}.teacher-auth-top{display:flex!important;justify-content:space-between!important;color:#566b91!important;font-size:13px!important}.teacher-auth-top a{display:flex!important;align-items:center!important;gap:7px!important;border:0!important;background:none!important;color:inherit!important;text-decoration:none!important;font:700 13px var(--font-body)!important}
    .teacher-auth-progress{width:min(100%,790px)!important;display:grid!important;grid-template-columns:repeat(4,1fr)!important;margin:36px auto 0!important}.teacher-auth-progress span{display:grid!important;justify-items:center!important;gap:8px!important;position:relative!important;color:#5d7093!important;font-size:11px!important}.teacher-auth-progress span:not(:last-child):after{content:""!important;position:absolute!important;top:20px!important;left:62%!important;width:76%!important;height:1px!important;background:#d8d8d4!important}.teacher-auth-progress span.done:not(:last-child):after{background:#ff532e!important}.teacher-auth-progress i{z-index:1!important;width:40px!important;height:40px!important;display:grid!important;place-items:center!important;border:0!important;border-radius:50%!important;background:#eee!important;color:#10203e!important;font-style:normal!important;font-weight:800!important}.teacher-auth-progress .active{color:#0a1730!important}.teacher-auth-progress .active i{border:0!important;background:#ff4b28!important;color:#fff!important}.teacher-auth-progress .done{color:#5d7093!important}.teacher-auth-progress .done i{border:0!important;background:#fff0eb!important;color:#ff4b28!important}
    .teacher-auth-card{width:min(100%,780px)!important;margin:54px auto 0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}.teacher-auth-eyebrow{margin:0 0 11px!important;color:#365687!important;text-transform:uppercase!important;letter-spacing:.3em!important;font-size:13px!important;font-weight:800!important}.teacher-auth-card h1{margin:0!important;color:#091936!important;font:800 clamp(32px,3.5vw,47px)/1.08 var(--font-body)!important;letter-spacing:-.055em!important}.teacher-auth-intro{margin:10px 0 29px!important;color:#5c7197!important;font-size:18px!important;line-height:1.42!important}
    .teacher-auth-form{display:grid!important;grid-template-columns:1fr 1fr!important;gap:15px!important}.teacher-auth-form>label{grid-column:1/-1!important}.teacher-auth-form label{display:grid!important;gap:7px!important;position:relative!important;color:#091936!important;font-size:13px!important;font-weight:800!important}.teacher-auth-grid{grid-column:1/-1!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:15px!important}.teacher-auth-form input,.teacher-auth-form select,.teacher-auth-form textarea{box-sizing:border-box!important;width:100%!important;min-height:46px!important;height:auto!important;border:1px solid #cfd7e3!important;border-radius:8px!important;padding:12px!important;background:#fff!important;color:#10213d!important;font:14px var(--font-body)!important;outline-color:#ff4b28!important}.teacher-auth-form textarea{resize:vertical!important}.teacher-auth-form .app-dropdown{top:20px!important;bottom:auto!important;height:calc(100% - 20px)!important}.teacher-password-field input{padding-right:48px!important}.teacher-auth-actions{grid-column:1/-1!important;display:grid!important;grid-template-columns:1fr 1.25fr!important;gap:15px!important;margin-top:7px!important}.teacher-auth-submit,.teacher-auth-secondary{width:100%!important;height:58px!important;border-radius:9px!important;padding:0!important;font:800 15px var(--font-body)!important}.teacher-auth-secondary{border:1px solid #ff4b28!important;background:#fff!important;color:#f04b28!important}.teacher-auth-submit{margin:0!important;border:0!important;background:#ff4b28!important;color:#fff!important}.teacher-auth-switch{grid-column:1/-1!important;margin:18px 0 0!important;color:#50678d!important;font-size:12px!important}.teacher-auth-error,.teacher-auth-message{grid-column:1/-1!important}
    @media(max-width:920px){.teacher-auth-page{display:block!important;padding:12px 12px 0!important}.teacher-auth-page .parent-photo-slider{position:relative!important;width:100%!important;min-height:210px!important;border-radius:20px!important}.teacher-auth-page .parent-photo-slider-brand{top:20px!important;left:22px!important}.teacher-auth-page .parent-photo-slider-logo{width:150px!important;height:42px!important}.teacher-auth-page .parent-photo-slider-copy{left:23px!important;bottom:24px!important}.teacher-auth-page .parent-photo-slider-copy h2{font-size:31px!important}.teacher-auth-page .parent-photo-slider-copy i,.teacher-auth-page .parent-photo-slider-copy p,.teacher-auth-page .parent-photo-slider-footer{display:none!important}.teacher-auth-main{padding:26px 18px 42px!important}.teacher-auth-card{margin-top:43px!important}}
    @media(max-width:560px){.teacher-auth-page{padding:9px 9px 0!important}.teacher-auth-page .parent-photo-slider{min-height:185px!important;border-radius:18px!important}.teacher-auth-page .parent-photo-slider-brand{top:16px!important;left:17px!important}.teacher-auth-page .parent-photo-slider-logo{width:130px!important;height:37px!important}.teacher-auth-page .parent-photo-slider-brand span{font-size:9px!important}.teacher-auth-page .parent-photo-slider-copy{left:18px!important;bottom:18px!important}.teacher-auth-page .parent-photo-slider-copy h2{font-size:27px!important}.teacher-auth-main{padding:20px 8px 34px!important}.teacher-auth-top{font-size:11px!important}.teacher-auth-progress{margin-top:27px!important}.teacher-auth-progress span{gap:6px!important;font-size:8px!important}.teacher-auth-progress span:not(:last-child):after{top:15px!important}.teacher-auth-progress i{width:31px!important;height:31px!important;font-size:11px!important}.teacher-auth-card{margin-top:36px!important}.teacher-auth-card h1{font-size:30px!important}.teacher-auth-intro{font-size:16px!important}.teacher-auth-form,.teacher-auth-grid,.teacher-auth-actions{grid-template-columns:1fr!important;gap:12px!important}.teacher-auth-submit,.teacher-auth-secondary{height:55px!important}}
  `}</style>;
}
