"use client";
import { FormEvent,useCallback,useEffect,useRef,useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { QRCodeSVG } from "qrcode.react";
import { FiCalendar,FiCheckCircle,FiGrid,FiShield,FiUsers,FiX } from "react-icons/fi";
import { FaWhatsapp } from "react-icons/fa";
import { AppSelect } from "./app-dropdown";
import { MonthPicker } from "./month-picker";
import { RecordBadge } from "./record-badge";
import { StatCard } from "./stat-card";
import { TeacherAttribution } from "./teacher-attribution";
import { apiBase,authHeaders,readTeacherSession } from "@/lib/session";
import { campusToday } from "@/lib/registration-eligibility";
import { parseCampusTime } from "@/lib/campus-time";
import "./teacher-attendance.css";

type TeacherService={id:number;kind:"SUNDAY"|"MDWK";name:string;startsAt:string;endsAt:string;hasQuestion:boolean};
type Arrival={id:number;name:string;checkedInAt:string|null;status:"PRESENT"|"ABSENT"|"AWAITING"};
type WelfareCase={id:number;teacherId:number;teacherName:string;assignedTo:number|null;assignedName:string|null;status:string;note:string|null;serviceName:string;serviceDate:string;phone?:string;absenceReason?:string|null;serviceId:number};
type Workspace={services:TeacherService[];items:Arrival[];cases:WelfareCase[];teachers:{id:number;name:string}[];canManage:boolean;canConfigure:boolean;serverTime:string};
const empty:Workspace={services:[],items:[],cases:[],teachers:[],canManage:false,canConfigure:false,serverTime:""};
export async function teacherAttendanceRequest(path:string,method="GET",body?:unknown){const r=await fetch(`${apiBase}/api/v1/teacher-attendance${path}`,{method,headers:{...authHeaders(),...(body?{"Content-Type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});const b=await r.json();if(!r.ok||!b.success)throw Error(b.error?.message||(r.status===404?"The teacher check-in backend release is not installed yet.":"Teacher attendance could not be loaded."));return b.data;}
function pretty(value:string){return new Intl.DateTimeFormat("en-NG",{day:"numeric",month:"short",year:"numeric",timeZone:"Africa/Lagos"}).format(parseCampusTime(value));}
function TeacherDialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow="hidden";ref.current?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="Tab"){const targets=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href],[tabindex="0"]')||[]).filter(x=>x.getClientRects().length);const first=targets[0],last=targets[targets.length-1];if(!targets.length){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus();}}};document.addEventListener("keydown",keys);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",keys);previous?.focus();};},[onClose]);return <div className="teacher-dialog-backdrop"><div className="teacher-dialog" ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="outline-button" aria-label="Close dialog" onClick={onClose}><FiX/></button></header>{children}</div></div>;}
export function TeacherAttendanceWorkspace(){
 const params=useSearchParams();const scannedService=Number(params.get("service"))||0;const scannedToken=params.get("token")||"";
 const[month,setMonth]=useState(campusToday().slice(0,7));const[kind,setKind]=useState("SUNDAY");const[serviceId,setServiceId]=useState(scannedService);const[data,setData]=useState<Workspace>(empty);const[tab,setTab]=useState("attendance");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[loaded,setLoaded]=useState(false);const[security,setSecurity]=useState(false);const[qr,setQr]=useState<{token:string;serviceId:number;expiresAt:string}|null>(null);const[qrOpen,setQrOpen]=useState(false);const[challenge,setChallenge]=useState<{question:string;teacherName:string;serviceName:string;serviceDate:string}|null>(null);const[answer,setAnswer]=useState("");const[verified,setVerified]=useState("");const[challengeError,setChallengeError]=useState("");const[challengeClosed,setChallengeClosed]=useState(false);const[selected,setSelected]=useState<WelfareCase|null>(null);const[assigned,setAssigned]=useState("");const[outcome,setOutcome]=useState("CONTACTED");const[note,setNote]=useState("");const[caseStatus,setCaseStatus]=useState("OPEN");const[clock,setClock]=useState(Date.now());
 const sequence=useRef(0);
 const load=useCallback(async()=>{const current=++sequence.current;try{const b:Workspace=await teacherAttendanceRequest(`?month=${month}${serviceId?`&serviceId=${serviceId}`:""}`);if(current!==sequence.current)return;setData(b);setError("");const available=b.services.filter(s=>s.kind===kind);if(!available.some(s=>Number(s.id)===serviceId)&&!scannedToken){const chosen=available.find(s=>s.startsAt<=b.serverTime&&s.endsAt>b.serverTime)||available.find(s=>s.startsAt>b.serverTime)||available[available.length-1];setServiceId(Number(chosen?.id||0));}}catch(e){if(current===sequence.current)setError(e instanceof Error?e.message:"Could not load teacher attendance.");}finally{if(current===sequence.current)setLoaded(true);}},[month,serviceId,kind,scannedToken]);
 useEffect(()=>{const generation=sequence;void load();const timer=window.setInterval(()=>void load(),10_000);return()=>{generation.current++;window.clearInterval(timer);};},[load]);
 useEffect(()=>{const timer=window.setInterval(()=>setClock(Date.now()),1000);return()=>window.clearInterval(timer);},[]);
 useEffect(()=>{if(!scannedService||!scannedToken)return;let cancelled=false;teacherAttendanceRequest(`/services/${scannedService}/challenge?token=${encodeURIComponent(scannedToken)}`).then(b=>{if(!cancelled)setChallenge(b);}).catch(e=>{if(!cancelled)setChallengeError(e.message);});return()=>{cancelled=true;};},[scannedService,scannedToken]);
 const closeChallenge=useCallback(()=>setChallengeClosed(true),[]);const closeQr=useCallback(()=>{setQrOpen(false);setQr(null);},[]);const closeSecurity=useCallback(()=>setSecurity(false),[]);const closeCase=useCallback(()=>setSelected(null),[]);
 async function mutate(path:string,method:string,body?:unknown){setBusy(true);setError("");try{await teacherAttendanceRequest(path,method,body);await load();return true;}catch(e){setError(e instanceof Error?e.message:"Could not save.");return false;}finally{setBusy(false);}}
 async function generateQr(){setBusy(true);setError("");try{setQr(await teacherAttendanceRequest(`/services/${serviceId}/qr`,"POST",{}));setQrOpen(true);}catch(e){setError(e instanceof Error?e.message:"QR could not be generated.");}finally{setBusy(false);}}
 async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setChallengeError("");try{const b=await teacherAttendanceRequest(`/services/${scannedService}/sign-in`,"POST",{token:scannedToken,answer});setVerified(`${b.teacherName}, your presence is verified for ${challenge?.serviceName||"this service"}.`);setAnswer("");window.history.replaceState(null,"","/account/teacher-check-in");await load();}catch(e){setChallengeError(e instanceof Error?e.message:"Sign-in failed.");}finally{setBusy(false);}}
 const current=data.services.find(s=>Number(s.id)===serviceId);const shownServices=data.services.filter(s=>!kind||s.kind===kind);const cases=data.cases.filter(c=>data.services.some(s=>Number(s.id)===Number(c.serviceId)&&s.kind===kind)).filter(c=>caseStatus==="ALL"||(caseStatus==="OPEN"?c.status!=="CONTACTED":c.status===caseStatus));const qrSeconds=qr?Math.max(0,Math.floor((parseCampusTime(qr.expiresAt).getTime()-clock)/1000)):0;const session=readTeacherSession();
 return <section className="teacher-attendance"><header className="teacher-attendance-heading"><div><p className="eyebrow">Ministry · Team care</p><h1>Teacher Check-In</h1><p>Verify your presence in church and care for teachers who missed service.</p></div>{data.canConfigure&&<Link className="outline-button" href="/account/settings/sunday-schedule"><FiCalendar/>Sunday schedule</Link>}</header>
 <div className="teacher-attendance-stats"><StatCard icon={<FiUsers/>} value={data.items.length} title="Expected teachers" description="No roster exemptions" tone="blue"/><StatCard icon={<FiCheckCircle/>} value={data.items.filter(r=>r.status==="PRESENT").length} title="Present" description={kind==="MDWK"?"Wednesday attendance confirmed":"QR and answer verified"} tone="green"/><StatCard icon={<FiCalendar/>} value={data.items.filter(r=>r.status==="ABSENT").length} title="Absent" description="After sign-in closes" tone="orange"/></div>
 <section className="panel teacher-attendance-toolbar"><MonthPicker value={new Date(month+"-01T00:00:00Z")} onChange={d=>{setMonth(d.toISOString().slice(0,7));setServiceId(0);}}/><label>Service day<AppSelect value={kind} onChange={e=>{setKind(e.target.value);setServiceId(0);}}><option value="SUNDAY">Sunday</option><option value="MDWK">Wednesday · MDWK</option></AppSelect></label><label>{kind==="SUNDAY"?"Sunday service":"Wednesday date"}<AppSelect value={serviceId} onChange={e=>setServiceId(Number(e.target.value))}><option value={0}>Choose {kind==="SUNDAY"?"a service":"a Wednesday"}</option>{shownServices.map(s=><option key={s.id} value={s.id}>{pretty(s.startsAt)} · {s.name}</option>)}</AppSelect></label>{kind==="SUNDAY"&&data.canManage&&<button className="outline-button" disabled={busy||!current||!current.hasQuestion} onClick={()=>void generateQr()}><FiGrid/>Show church QR</button>}{kind==="SUNDAY"&&data.canConfigure&&<button className="outline-button" disabled={!current} onClick={()=>setSecurity(true)}><FiShield/>Set today’s question</button>}</section>
 {error&&<p className="teacher-attendance-error" role="alert">{error}<button className="outline-button" onClick={()=>void load()}>Retry</button></p>}{!loaded&&<p role="status">Loading teacher attendance…</p>}
 <p className="teacher-attendance-notice"><FiShield/>{kind==="MDWK"?"Confirm Wednesday attendance from Overview before 9pm Lagos time. No QR or security question. After the deadline, leave a private reason if you missed service.":"Scan the QR displayed in church and answer today’s question. Each configured Sunday service has its own attendance register."}</p>
 <nav className="teacher-attendance-tabs" aria-label="Teacher attendance views"><button aria-pressed={tab==="attendance"} onClick={()=>setTab("attendance")}>Attendance register</button><button aria-pressed={tab==="welfare"} onClick={()=>setTab("welfare")}>{data.canManage?"Teacher follow-up":"My assigned follow-ups"}</button></nav>
 {tab==="attendance"?<section className="panel"><h2>{current?current.name:"Attendance register"}</h2>{current&&<p>{pretty(current.startsAt)} · {current.kind==="MDWK"?"Wednesday service":"Sunday service"} · {current.kind==="MDWK"?"Confirm on Overview before 9pm (Lagos)":`Sign-in ${current.startsAt.slice(11,16)}–${current.endsAt.slice(11,16)} (Lagos)`}</p>}<div className="table-wrap operations-table-frame"><table className="operations-table"><thead><tr><th>S/N</th><th>Teacher</th><th>Attendance</th><th>Verified arrival</th></tr></thead><tbody>{data.items.map((r,i)=><tr key={r.id}><td data-label="S/N">{i+1}</td><td data-label="Teacher"><TeacherAttribution name={r.name} staffId={r.id}/></td><td data-label="Attendance"><RecordBadge tone={r.status==="PRESENT"?"green":r.status==="ABSENT"?"orange":"neutral"}>{r.status==="PRESENT"?"Present":r.status==="ABSENT"?"Absent":"Awaiting sign-in"}</RecordBadge></td><td data-label="Verified arrival">{r.checkedInAt?new Intl.DateTimeFormat("en-NG",{timeStyle:"short",timeZone:"Africa/Lagos"}).format(parseCampusTime(r.checkedInAt)):"—"}</td></tr>)}</tbody></table></div>{!data.items.length&&loaded&&!error&&<p>No teacher attendance recorded for this selection. {data.canConfigure?"Sunday services use Sunday Schedule; MDWK appears automatically.":"There are no attendance records for this selection."}</p>}</section>:<section className="panel"><div className="teacher-welfare-heading"><div><h2>{data.canManage?"Teachers to follow up":"My assigned teacher follow-ups"}</h2><p>Absences become welfare tasks after the service closes. Contacted tasks leave the open list.</p></div><AppSelect aria-label="Welfare outcome filter" value={caseStatus} onChange={e=>setCaseStatus(e.target.value)}><option value="OPEN">Needs follow-up</option><option value="CONTACTED">Contacted</option><option value="ALL">All outcomes</option></AppSelect></div><div className="teacher-welfare-grid">{cases.map(c=><article key={c.id}><TeacherAttribution name={c.teacherName} staffId={c.teacherId}/><p>{pretty(c.serviceDate+" 12:00:00")} · {c.serviceName}</p><RecordBadge tone={c.status==="CONTACTED"?"green":"orange"}>{c.status==="CONTACTED"?"Contacted":c.status==="ATTEMPTED"?"Contact attempted":"Needs follow-up"}</RecordBadge><small>Assigned to {c.assignedName||"nobody yet"}</small><button className="outline-button" onClick={()=>{setSelected(c);setAssigned(String(c.assignedTo||""));setNote(c.note||"");setOutcome(c.status==="ATTEMPTED"?"ATTEMPTED":"CONTACTED");}}>View follow-up</button></article>)}</div>{!cases.length&&<p>{data.canManage?"No teacher follow-ups match these filters.":"You have no teacher welfare tasks assigned for this month."}</p>}</section>}
 {security&&current&&<SecuritySetup service={current} onClose={closeSecurity} onSaved={()=>{setSecurity(false);setQr(null);void load();}}/>}
 {qrOpen&&qr&&<TeacherDialog title="Church teacher check-in QR" onClose={closeQr}><p>Display this in church. Scanning never signs someone in automatically.</p>{qrSeconds>0?<div className="teacher-qr"><QRCodeSVG value={`${window.location.origin}/account/teacher-check-in?service=${qr.serviceId}&token=${qr.token}`} size={256} marginSize={2}/><b>Expires in {Math.floor(qrSeconds/60)}:{String(qrSeconds%60).padStart(2,"0")}</b></div>:<p role="alert">QR expired. Generate a fresh code before anyone scans.</p>}<button className="solid-button" disabled={busy} onClick={()=>void generateQr()}>Refresh QR (replaces the previous code)</button></TeacherDialog>}
 {(scannedToken||verified)&&!challengeClosed&&<TeacherDialog title={verified?"Attendance verified":"Verify today’s attendance"} onClose={closeChallenge}>{verified?<div role="status"><FiCheckCircle/><p>{verified}</p><button className="solid-button" onClick={closeChallenge}>Done</button></div>:challenge?<form onSubmit={signIn}>{session&&<TeacherAttribution name={session.name} photo={session.profileImageUrl}/>}<p>{challenge.serviceName} · {pretty(challenge.serviceDate+" 12:00:00")}</p><label>{challenge.question}<input autoComplete="off" value={answer} maxLength={100} required onChange={e=>setAnswer(e.target.value)} placeholder="Your answer"/></label><p>Your name is marked present only after the answer is verified.</p>{challengeError&&<p className="teacher-attendance-error" role="alert">{challengeError}</p>}<button className="solid-button" disabled={busy||!answer.trim()}>{busy?"Verifying…":"Verify and sign me in"}</button></form>:<p role={challengeError?"alert":"status"}>{challengeError||"Loading today’s question…"}</p>}</TeacherDialog>}
 {selected&&<TeacherDialog title={`Follow up · ${selected.teacherName}`} onClose={closeCase}><p>{selected.serviceName} · {pretty(selected.serviceDate+" 12:00:00")}</p>{data.canManage&&selected.absenceReason&&<div className="teacher-private-reason"><b>Private Wednesday absence reason</b><p>{selected.absenceReason}</p><small>Only Super Admins and Teachers Welfare can see this.</small></div>}{selected.phone&&<a className="outline-button" href={`https://wa.me/${selected.phone.replace(/\D/g,"").replace(/^0/,"234")}`} target="_blank" rel="noreferrer"><FaWhatsapp/>WhatsApp teacher</a>}{data.canManage&&<div className="teacher-lead-control"><label>Assigned teacher<AppSelect value={assigned} onChange={e=>setAssigned(e.target.value)}><option value="">Choose a teacher</option>{data.teachers.filter(t=>Number(t.id)!==Number(selected.teacherId)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</AppSelect></label><button className="solid-button" disabled={busy||!assigned} onClick={()=>void mutate(`/cases/${selected.id}`,"PATCH",{assignedTo:Number(assigned)}).then(ok=>{if(ok)closeCase();})}>Assign follow-up</button></div>}<form onSubmit={e=>{e.preventDefault();void mutate(`/cases/${selected.id}`,"PATCH",{status:outcome,note}).then(ok=>{if(ok)closeCase();});}}><label>Outcome<AppSelect value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="CONTACTED">Spoke with the teacher</option><option value="ATTEMPTED">Tried, but no response yet</option></AppSelect></label><label>Follow-up note<textarea value={note} maxLength={4000} rows={3} required onChange={e=>setNote(e.target.value)} placeholder="Add a short factual update"/></label><button className="solid-button" disabled={busy||!note.trim()}>Save follow-up</button></form>{error&&<p role="alert" className="teacher-attendance-error">{error}</p>}</TeacherDialog>}
 </section>;
}
function AcceptedAnswers({value,onChange}:{value:string[];onChange:(value:string[])=>void}){
 const[draft,setDraft]=useState("");const[error,setError]=useState("");
 function add(){const entries=draft.split(",").map(s=>s.trim()).filter(Boolean);const next=[...value];for(const entry of entries){if(entry.length>100){setError("Keep each answer under 100 characters.");return;}if(!next.some(a=>a.toLowerCase()===entry.toLowerCase()))next.push(entry);}if(next.length>5){setError("You can add up to five accepted answers.");return;}onChange(next);setDraft("");setError("");}
 return <div className="teacher-answer-editor"><label htmlFor="accepted-answer">Accepted answers</label><div className="teacher-answer-entry"><input id="accepted-answer" type="text" autoComplete="off" value={draft} maxLength={500} placeholder="e.g. Blue" onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();add();}}}/><button type="button" className="outline-button" disabled={!draft.trim()} onClick={add}>Add answer</button></div><div className="teacher-answer-badges">{value.map((answer,i)=><span key={answer}>{answer}<button type="button" aria-label={`Remove accepted answer ${answer}`} onClick={()=>onChange(value.filter((_,j)=>j!==i))}><FiX/></button></span>)}</div><small>Add each answer as a badge. Up to five alternatives; case and extra spaces are ignored.</small>{error&&<p role="alert">{error}</p>}</div>;
}
function SecuritySetup({service,onClose,onSaved}:{service:TeacherService;onClose:()=>void;onSaved:()=>void}){const[question,setQuestion]=useState("");const[answers,setAnswers]=useState<string[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState("");return <TeacherDialog title="Set today’s question" onClose={onClose}><p>{service.name} · {pretty(service.startsAt)}. Set the in-church question and add the accepted answers below. Previously verified attendance is preserved.</p><form onSubmit={e=>{e.preventDefault();setBusy(true);setError("");void teacherAttendanceRequest(`/services/${service.id}/security`,"PUT",{question,answers}).then(onSaved).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>In-church question<input required maxLength={250} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What colour is Aunty Mafo’s dress today?"/></label><AcceptedAnswers value={answers} onChange={setAnswers}/>{error&&<p role="alert" className="teacher-attendance-error">{error}</p>}<button className="solid-button" disabled={busy||!answers.length}>{busy?"Saving…":"Save question"}</button></form></TeacherDialog>;}
