"use client";

import Link from "next/link";
import { FiCheckCircle, FiChevronRight, FiClock, FiUsers } from "react-icons/fi";
import { QuickActions } from "@/components/quick-actions";
import { UserGreeting } from "@/components/user-greeting";

const classes = [["TribePetra Teens", "Ages 13 – 17", 32, 34], ["Tribe A", "Ages 9 – 12", 47, 55], ["Tribe B", "Ages 5 – 8", 58, 67], ["Tribe C", "Ages 3 – 4", 49, 55]] as const;
export default function AccountOverview() { return <div className="overview"><header className="overview-header"><div><p className="eyebrow">Petra Wuse</p><UserGreeting /><p className="intro">Here’s what’s happening at TribePetra Kids today.</p></div></header><section className="metrics"><Metric icon={<FiUsers />} value="186" title="Checked In" sub="Children checked in this service" tone="orange" /><Metric icon={<FiCheckCircle />} value="131" title="Picked Up" sub="Children safely collected" tone="green" /><Metric icon={<FiClock />} value="55" title="Still Present" sub="Children currently in class" tone="yellow" /><Metric icon={<FiUsers />} value="4" title="Active Classes" sub="Classes receiving children today" tone="dark" /></section><section className="dashboard-grid"><div className="left-column"><section className="panel attendance-panel"><div className="panel-heading"><div><h2>Attendance by Class</h2><p>Children currently checked in by class</p></div><Link href="/account/classrooms" className="outline-button">View classrooms <FiChevronRight /></Link></div><div className="attendance-list">{classes.map(([name, ages, count, total]) => <div className="attendance-row" key={name}><div><b>{name}</b><span>{ages}</span></div><div className="progress"><i style={{ width: `${count / total * 100}%` }} /></div><strong>{count}</strong></div>)}</div></section><section className="panel recent-panel"><div className="panel-heading"><div><h2>Recent Check-Ins</h2><p>The latest children to arrive</p></div><Link href="/account/check-in" className="outline-button">View all check-ins <FiChevronRight /></Link></div><p className="account-empty">Live parent check-ins will appear here.</p></section></div><aside className="right-column"><QuickActions /><section className="panel attention-panel"><div className="panel-heading"><div><h2>Needs Attention</h2><p>Items that need your attention</p></div></div><div className="attention-list"><div className="attention-item"><i className="amber"><FiClock /></i><span>3 children from Tribe A missed church for 2 weeks — call now</span><FiChevronRight /></div></div></section></aside></section><style jsx global>{`.account-empty{padding:24px 0 8px;color:#687184;font-size:12px}.overview-header{padding-top:0}`}</style></div>; }
function Metric({ icon, value, title, sub, tone }: { icon: React.ReactNode; value: string; title: string; sub: string; tone: "orange" | "green" | "yellow" | "dark" }) { return <article className={`metric-card ${tone}`}><span className="metric-icon">{icon}</span><div><strong>{value}</strong><h3>{title}</h3><p>{sub}</p></div></article>; }
