"use client";

import { useEffect, useState } from "react";
import { apiBase, authHeaders, readTeacherSession } from "@/lib/session";

type Member = { id: number; firstName?: string; lastName?: string; name: string; email: string; title?: string; accessLevel: "TPK_SUPER_ADMIN" | "TPK_ADMIN"; teamStatus: "ACTIVE" | "PROBATION" | "INACTIVE"; accountStatus: string; assignedClasses?: string | null; profileImageUrl?: string | null };
export default function TeamPage() {
  const session = readTeacherSession(); const [members, setMembers] = useState<Member[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState<number | null>(null);
  const load = () => { if (!session) return; fetch(`${apiBase}/api/v1/team`, { headers: authHeaders(session) }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "We could not load the team."); setMembers(result.data); }).catch((reason) => setError(reason instanceof Error ? reason.message : "We could not load the team.")); };
  useEffect(load, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function change(id: number, endpoint: "access-level" | "team-status", value: string) { if (!session || id === session.staffUserId) return; setBusy(id); setError(""); const key = endpoint === "access-level" ? "accessLevel" : "teamStatus"; const response = await fetch(`${apiBase}/api/v1/staff/${id}/${endpoint}`, { method: "PATCH", headers: { ...authHeaders(session), "Content-Type": "application/json" }, body: JSON.stringify({ [key]: value }) }); const result = await response.json(); if (!response.ok) setError(result.error?.message || "We could not update this team member."); else load(); setBusy(null); }
  return <section className="team-page"><header><p className="eyebrow">People</p><h1>Team</h1><p className="intro">Manage TPK access and team status. Super Admin access and team status are separate.</p></header>{error && <p className="team-error">{error}</p>}<section className="panel team-table"><div className="panel-heading"><div><h2>TPK Team</h2><p>{members.length ? `${members.length} registered team members` : "Loading registered team members…"}</p></div></div><div className="table-wrap"><table><thead><tr><th>Team Member</th><th>Assignments</th><th>Access Level</th><th>Team Status</th></tr></thead><tbody>{members.map((member) => <tr key={member.id}><td><div className="member"><Avatar member={member} /><span><b>{member.title || ""} {member.firstName || member.name}</b><small>{member.email}{member.accountStatus === "PENDING_VERIFICATION" ? " · Awaiting WhatsApp verification" : ""}</small></span></div></td><td>{member.assignedClasses || "No current class assignment"}</td><td><select disabled={busy === member.id || member.id === session?.staffUserId} value={member.accessLevel} onChange={(event) => change(member.id, "access-level", event.target.value)}><option value="TPK_ADMIN">TPK Admin</option><option value="TPK_SUPER_ADMIN">TPK Super Admin</option></select></td><td><select disabled={busy === member.id || member.id === session?.staffUserId} value={member.teamStatus} onChange={(event) => change(member.id, "team-status", event.target.value)}><option value="ACTIVE">Active</option><option value="PROBATION">Probation</option><option value="INACTIVE">Inactive</option></select></td></tr>)}{!members.length && <tr><td colSpan={4} className="empty">No registered team members are available yet.</td></tr>}</tbody></table></div></section><p className="team-note">Your own access and status are read-only here; use a different TPK Super Admin for leadership changes.</p><style jsx>{`.team-page h1,.team-page h2{font-family:Georgia,serif}.team-page header{margin-bottom:22px}.team-table{max-width:1120px}.member{display:flex;align-items:center;gap:10px}.member span{display:grid;gap:3px}.member small{color:var(--muted);font-size:10px}.member :global(.team-avatar){width:34px;height:34px;border-radius:50%;object-fit:cover}.member :global(.team-initials){width:34px;height:34px;display:grid;place-items:center;border-radius:50%;background:#ffe1c8;color:#8f3a20;font-size:10px;font-weight:900}select{height:34px;border:1px solid var(--line);border-radius:7px;background:#fffdfa;padding:0 8px;font:700 11px var(--font-body)}select:disabled{opacity:.6}.team-error{color:#c8452c;font-size:12px}.team-note{color:var(--muted);font-size:11px}`}</style></section>;
}
function Avatar({ member }: { member: Member }) { const initials = `${member.firstName?.[0] || member.name[0] || ""}${member.lastName?.[0] || ""}`.toUpperCase(); return member.profileImageUrl ? <img className="team-avatar" src={`${apiBase}${member.profileImageUrl}`} alt="" /> : <i className="team-initials">{initials}</i>; }
